### ISSUE TITLE
Handle kombu disconnects

### ISSUE THREAD

**Issue by xarg** [miguelgrinberg/python-socketio#100]
Currently if the connection is lost to the message queue (in my case RabbitMQ), kombu does not try to re-establish the connection. Here's an example project (and the steps) and how to reproduce this: https://github.com/xarg/flask-socketio-reconnect

Pasting them here in case the project disappears:

- Make sure rabbitmq server is started and is accessible via: `amqp://guest:guest@localhost:5672//`
- `python app.py`
- Navigate to http://localhost:5000 and stay there (observe that the ping times change)
- Kill your rabbitmq server
- Look at the console where you started app.py
- Start rabbitmq server

After these above steps, even if the rmq server is restarted the flask-socketio server does not try to reconnect to it and just hangs.

This is one of the tracebacks I get: 

```
127.0.0.1 - - [08/May/2017 13:44:29] "GET /socket.io/?EIO=3&transport=polling&t=1494276269541-2&sid=be76255267064a938f9651e40f31ef5f HTTP/1.1" 200 222 0.000245
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/a/Projects/python-socketio/socketio/pubsub_manager.py", line 130, in _thread
    for message in self._listen():
  File "/Users/a/Projects/python-socketio/socketio/kombu_manager.py", line 88, in _listen
    yield message.payload
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/kombu/simple.py", line 24, in __exit__
    self.close()
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/kombu/simple.py", line 76, in close
    self.consumer.cancel()
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/kombu/messaging.py", line 487, in cancel
    cancel(tag)
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/amqp/channel.py", line 1454, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/amqp/abstract_channel.py", line 64, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/amqp/method_framing.py", line 174, in write_frame
    write(view[:offset])
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/amqp/transport.py", line 269, in write
    self._write(s)
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/eventlet/greenio/base.py", line 397, in sendall
    tail = self.send(data, flags)
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/eventlet/greenio/base.py", line 391, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/Users/a/.virtualenvs/flask-socketio/lib/python2.7/site-packages/eventlet/greenio/base.py", line 378, in _send_loop
    return send_method(data, *args)
```

I'm guessing that kombu manager tries to read from the queue, but can't and the yield fails.

What would be the expected behavior:

Once the RabbitMQ server disconnects, the manager tries to re-establish the connection and read/re-send the pending published messages using the same queue (if it can).

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
