### ISSUE TITLE
EmptyStreamReader is missing __repr__, causes AttributeError

### ISSUE THREAD

**Issue by elonen** [miguelgrinberg/python-socketio#1032]
On version 5.7.1 the following program gives `AttributeError: 'EmptyStreamReader' object has no attribute '_size'`:

```python
from aiohttp import web
from pathlib import Path
import socketio

sio = socketio.AsyncServer(async_mode='aiohttp', logger=True, engineio_logger=True)
app = web.Application()
sio.attach(app)

@sio.event
async def connect(sid, environ):
    print(environ)    # <------- HERE

async def index(request):
    module_dir = Path(__file__).parent.absolute()
    with open(module_dir/'static/index.html') as f:
        return web.Response(text=f.read(), content_type='text/html')

app.router.add_static('/static', Path(__file__).parent.absolute()/'static')
app.router.add_get('/', index)

async def init_app():
    return app

if __name__ == '__main__':
    web.run_app(init_app())
```

Full stacktrace:
```
Server initialized for aiohttp.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
W1yw4p4FtUhMqm8CAAAA: Sending packet OPEN data {'sid': 'W1yw4p4FtUhMqm8CAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
W1yw4p4FtUhMqm8CAAAA: Received packet MESSAGE data 0
message async handler error
Traceback (most recent call last):
  File "/projectdir/_venv/lib/python3.9/site-packages/engineio/asyncio_server.py", line 456, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/projectdir/_venv/lib/python3.9/site-packages/socketio/asyncio_server.py", line 593, in _handle_eio_message
    await self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/projectdir/_venv/lib/python3.9/site-packages/socketio/asyncio_server.py", line 471, in _handle_connect
    success = await self._trigger_event(
  File "/projectdir/_venv/lib/python3.9/site-packages/socketio/asyncio_server.py", line 557, in _trigger_event
    ret = await handler(*args)
  File "/projectdir/my_module/ws_server.py", line 11, in connect
    print(environ)
  File "/projectdir/_venv/lib/python3.9/site-packages/aiohttp/streams.py", line 132, in __repr__
    if self._size:
AttributeError: 'EmptyStreamReader' object has no attribute '_size'
W1yw4p4FtUhMqm8CAAAA: Received request to upgrade to websocket
W1yw4p4FtUhMqm8CAAAA: Upgrade to websocket successful
```

Versions:

> aiohttp==3.8.1
> aiosignal==1.2.0
> async-timeout==4.0.2
> attrs==22.1.0
> bidict==0.22.0
> charset-normalizer==2.1.1
> frozenlist==1.3.1
> idna==3.4
> multidict==6.0.2
> python-engineio==4.3.4
> python-socketio==5.7.1
> yarl==1.8.1

Python 3.9.2

Client uses Javascript socket.io 3.0.3 -- though this obviously shouldn't happen in any case.

**Comment by elonen** [comment]
If I add a dummy __repr__ to the **EmptyStreamReader**, printing environ works as expected. E.g.:

```python
    def __repr__(self) -> str:
        return "<EmptyStreamReader>"
```

**Comment by miguelgrinberg** [comment]
Or remove the `print` statement in the meantime.

If you want to provide a PR I'm happy to merge it.

**Comment by elonen** [comment]
Upon closer inspection, I decided this is actually an aiohttp bug, and no clean workarounds on python-socketio exist. The linked PR above fixes the issue on their side. Closing this here.

**Comment by miguelgrinberg** [comment]
Right! I was actually on the phone and couldn't check, I assumed the affected class was mine, not theirs. Thanks for the update.
