### ISSUE TITLE
Getting following error

### ISSUE THREAD

**Issue by navneetgarggate6** [miguelgrinberg/python-socketio#1046]
I am using python 3.6 and module version is 5.4.1.

I am getting following error regularly and also my server restart automatically after some time.

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/wsgi.py", line 815, in process_request
    proto.__init__(conn_state, self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/wsgi.py", line 346, in __init__
    self.handle()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/wsgi.py", line 379, in handle
    self.handle_one_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/wsgi.py", line 408, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/wsgi.py", line 391, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 253, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 268, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 188, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
OSError: [Errno 0] Error
(31576) accepted ('172.31.31.11', 48876)
wsgi exiting

**Comment by miguelgrinberg** [comment]
I mentioned this before. Please do not open issues on this project when you need help figuring out something that does not work on your application.

**Comment by navneetgarggate6** [comment]
Ok so what is the right place ?

**Comment by miguelgrinberg** [comment]
https://github.com/miguelgrinberg/python-socketio/discussions
