### ISSUE TITLE
Session not found in AsyncNamespace

### ISSUE THREAD

**Issue by devamin** [miguelgrinberg/python-socketio#1101]
**Describe the bug**
Unable to save session in AsyncNamespace handlers

**To Reproduce**
server .py
```python
# server.py
from typing import Any
import uvicorn
from fastapi import FastAPI
from socketio import AsyncNamespace
import socketio

sio: Any = socketio.AsyncServer(async_mode="asgi",logger=True, engineio_logger=True)
socket_app = socketio.ASGIApp(sio)
app = FastAPI()

app.mount("/", socket_app)

class AsyncNS(AsyncNamespace):
    def __init__(self,ns,sio):
        super().__init__(ns)
        self.sio=sio
    
    async def on_connect(self,sid, env):
        print("on connect")
        await self.sio.save_session(sid,{'id':1})
        self.sio.enter_room(sid,"room2")
        print("ok")

    async def broadcast(self,sid,data):
        print(self.sio)
        print(f"broadcast {data}")
        session = await self.sio.get_session(sid)
        print(session)

sio.register_namespace(AsyncNS("/chat/ws",sio=sio))

if __name__ == "__main__":
    kwargs = {"host": "0.0.0.0", "port": 8556}
    uvicorn.run(app, **kwargs)
 ```
 
client
```
import socketio
cl = socketio.Client()
cl.connect(
    "http://127.0.0.1:8556",
    namespaces="/chat/ws",
    transports=["websocket"]) # server prints "on connect"
```

**Expected behavior**
Have a session, this works normal with simple handlers but not with class based one

**Logs**

```
INFO:     Started server process [5057]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8556 (Press CTRL+C to quit)
JZlqLm5gxSJR-t5nAAAA: Sending packet OPEN data {'sid': 'JZlqLm5gxSJR-t5nAAAA', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
JZlqLm5gxSJR-t5nAAAA: Received request to upgrade to websocket
INFO:     ('127.0.0.1', 59937) - "WebSocket /socket.io/?transport=websocket&EIO=4&t=1671253855.206351" [accepted]
JZlqLm5gxSJR-t5nAAAA: Upgrade to websocket successful
INFO:     connection open
JZlqLm5gxSJR-t5nAAAA: Received packet MESSAGE data 0/chat/ws,{}
on connect
message async handler error
Traceback (most recent call last):
  File "/code/project/.venv/lib/python3.10/site-packages/engineio/server.py", line 633, in _get_socket
    s = self.sockets[sid]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/project/.venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 456, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/code/project/.venv/lib/python3.10/site-packages/socketio/asyncio_server.py", line 594, in _handle_eio_message
    await self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/code/project/.venv/lib/python3.10/site-packages/socketio/asyncio_server.py", line 472, in _handle_connect
    success = await self._trigger_event(
  File "/code/project/.venv/lib/python3.10/site-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/code/project/.venv/lib/python3.10/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/code/project/local/socketio_redis/server.py", line 21, in on_connect
    await self.sio.save_session(sid,{'id':1})
  File "/code/project/.venv/lib/python3.10/site-packages/socketio/asyncio_server.py", line 319, in save_session
    eio_session = await self.eio.get_session(eio_sid)
  File "/code/project/.venv/lib/python3.10/site-packages/engineio/asyncio_server.py", line 110, in get_session
    socket = self._get_socket(sid)
  File "/code/project/.venv/lib/python3.10/site-packages/engineio/server.py", line 635, in _get_socket
    raise KeyError('Session not found')
KeyError: 'Session not found'
```

**Comment by miguelgrinberg** [comment]
This is actually your bug. You are saving the session by calling the `save_session()` method of the server object:

    await self.sio.save_session(sid,{'id':1})

This method accepts a `namespace` argument, which you are not passing. So the server attempts to save a session for the global namespace, which your client isn't connected to.

The correct way to save the session from a namespace method is to use the namespace's own `save_session()` method, which configures the namespace for you:

    await self.save_session(sid,{'id':1})

Or if you prefer to use the main `save_session()` method, then pass the namespace youself:

    await self.sio.save_session(sid,{'id':1}, namespace='/chat/ws')
