### ISSUE TITLE
Sanic mode does not shut down cleanly (Task was destroyed but it is pending)

### ISSUE THREAD

**Issue by opatut** [miguelgrinberg/python-socketio#1119]
**Describe the bug**

In `async_mode="sanic"`, when the loop terminates because the server is shut down, some background tasks are (destroyed by the loop -- I think), causing exceptions.

This concerns at least the the Socket's `schedule_ping` task.

**To Reproduce**

* install `python-socketio==5.7.2 python-engineio==4.3.4`
* run the following minimal example script
* navigate to http://localhost:8000 to establish a connection
* press Ctrl+C in the terminal to stop the server and loop
* watch the exception

<details><summary>Click to expand code snippet</summary>

```python
from sanic import Sanic
from sanic.response import html
import socketio

app = Sanic("testapp")
sio = socketio.AsyncServer(async_mode="sanic")
sio.attach(app)


@sio.on("connect")
async def _sio_connect(sid, environ, auth):
    await sio.emit("hello", {"world": True}, room=sid)


INDEX_PAGE = """
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.socket.io/4.5.4/socket.io.min.js"></script>
    <script>
        var socket = io();
        socket.on('hello', (e) => document.write(JSON.stringify(e)))
    </script>
  </head>
  <body></body>
</html>
"""


@app.get("/")
async def _index(req):
    return html(INDEX_PAGE)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, dev=True)
```

</details>

**Expected behavior**

The loop should terminate cleanly.

**Logs**

<details><summary>Click to expand sample log</summary>

```
^C[2023-01-19 15:31:55 +0100] [203940] [INFO] Stopping worker [203940]
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: server.shutdown.before
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] > CLOSE 1001 (going away) [2 bytes]
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] = connection is CLOSING
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.send
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] < CLOSE 1001 (going away) [2 bytes]
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] > EOF
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Websocket task finished. Closing the connection.
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Websocket half-closing TCP connection
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Websocket keepalive ping task was cancelled.
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] < EOF
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] = connection is CLOSED
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.exception
[2023-01-19 15:31:55 +0100] [203940] [ERROR] Exception occurred while handling uri: 'ws://localhost:8000/socket.io/?EIO=4&transport=websocket&sid=MF8PvHxLoRIoTo8hAAAA'
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/sanic/app.py", line 943, in handle_request
    raise ServerError(
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.response
[2023-01-19 15:31:55 +0100] - (sanic.access)[INFO][127.0.0.1:33850]: GET ws://localhost:8000/socket.io/?EIO=4&transport=websocket&sid=MF8PvHxLoRIoTo8hAAAA  500 471
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.exception
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.response
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: http.lifecycle.complete
[2023-01-19 15:31:55 +0100] [203940] [DEBUG] Dispatching signal: server.shutdown.after
[2023-01-19 15:31:55 +0100] [203940] [INFO] Server Stopped
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "test.py", line 36, in <module>
    app.run(host="0.0.0.0", port=8000, dev=True)
  File ".../lib/python3.9/site-packages/sanic/mixins/runner.py", line 169, in run
    self.__class__.serve(primary=self)  # type: ignore
  File ".../lib/python3.9/site-packages/sanic/mixins/runner.py", line 672, in serve
    serve_single(primary_server_info.settings)
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 324, in serve_single
    serve(**server_settings)
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 106, in serve
    return _serve_http_1(
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 265, in _serve_http_1
    _run_server_forever(
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 151, in _run_server_forever
    loop.run_forever()
  File ".../lib/python3.9/site-packages/sanic/server/protocols/http_protocol.py", line 149, in connection_task
    await self._http.http1()
  File ".../lib/python3.9/site-packages/sanic/http/http1.py", line 127, in http1
    await self.protocol.request_handler(self.request)
  File ".../lib/python3.9/site-packages/sanic/app.py", line 901, in handle_request
    response = await response
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 258, in handle_request
    r = await self._handle_connect(environ, transport,
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 396, in _handle_connect
    self.start_background_task(self._service_task)
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 332, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
task: <Task pending name='Task-7' coro=<AsyncServer._service_task() running at .../lib/python3.9/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fbf5ddfd0>()] created at .../lib/python3.9/asyncio/tasks.py:647> created at .../lib/python3.9/site-packages/engineio/asyncio_server.py:332>
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "test.py", line 36, in <module>
    app.run(host="0.0.0.0", port=8000, dev=True)
  File ".../lib/python3.9/site-packages/sanic/mixins/runner.py", line 169, in run
    self.__class__.serve(primary=self)  # type: ignore
  File ".../lib/python3.9/site-packages/sanic/mixins/runner.py", line 672, in serve
    serve_single(primary_server_info.settings)
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 324, in serve_single
    serve(**server_settings)
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 106, in serve
    return _serve_http_1(
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 265, in _serve_http_1
    _run_server_forever(
  File ".../lib/python3.9/site-packages/sanic/server/runners.py", line 151, in _run_server_forever
    loop.run_forever()
  File ".../lib/python3.9/site-packages/sanic/server/protocols/http_protocol.py", line 149, in connection_task
    await self._http.http1()
  File ".../lib/python3.9/site-packages/sanic/http/http1.py", line 127, in http1
    await self.protocol.request_handler(self.request)
  File ".../lib/python3.9/site-packages/sanic/app.py", line 901, in handle_request
    response = await response
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 258, in handle_request
    r = await self._handle_connect(environ, transport,
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 408, in _handle_connect
    s.schedule_ping()
  File ".../lib/python3.9/site-packages/engineio/asyncio_socket.py", line 132, in schedule_ping
    self.server.start_background_task(send_ping)
  File ".../lib/python3.9/site-packages/engineio/asyncio_server.py", line 332, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
task: <Task pending name='Task-8' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() running at .../lib/python3.9/site-packages/engineio/asyncio_socket.py:127> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fbf5dd460>()] created at .../lib/python3.9/asyncio/tasks.py:647> created at .../lib/python3.9/site-packages/engineio/asyncio_server.py:332>
service task canceled
```

</details>

**Additional details**

It seems like the Python documentation explicitly recommends [saving a reference to the task](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task). I'd go further and also properly implement cancellation for *all* background tasks, so that they can properly shut down with the server.

**Comment by miguelgrinberg** [comment]
I don't use Sanic anymore. Would you be interested in writing a graceful shutdown handler to take care of this?
