### ISSUE TITLE
"Invalid transport" when using python-engineio 4.10.0 possibly due transport upgrade fail 

### ISSUE THREAD

**Issue by BobakBaghi** [miguelgrinberg/python-socketio#1396]
**Describe the bug**
When upgrading to the latest release of `python-engineio==4.10.0`, an ASGI socketio server mounted on FastAPI will reject a connection from a socketio async client due to "invalid transport for session" with a 403 Forbidden.

Seems to be directly related to the recent fix https://github.com/miguelgrinberg/python-engineio/commit/4d614e5297ed2291ae97fcf30a3ee7223886440a (issue https://github.com/miguelgrinberg/python-engineio/issues/367).

Everything below is run on `python-socketio==5.11.4`.

**To Reproduce**
server.py
```python
import socketio
import uvicorn
from fastapi import FastAPI

app = FastAPI()

sio = socketio.AsyncServer(async_mode="asgi", logger=True, engineio_logger=True)
sio_app = socketio.ASGIApp(sio)


@sio.event
def connect(sid, environ, auth):
    print("connect ", sid)


@sio.event
def disconnect(sid):
    print("disconnect ", sid)


app.mount("/", sio_app)


def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)


if __name__ == "__main__":
    run_server()
```

client.py
```python
import asyncio

import socketio


async def test_connect():
    async with socketio.AsyncSimpleClient(logger=True, engineio_logger=True) as sio:
        await sio.connect("http://localhost:8000")

        await sio.disconnect()


if __name__ == "__main__":
    asyncio.run(test_connect())

```

Logs if `python-engineio==4.10.0`:
server:
```
Server initialized for asgi.
INFO:     Started server process [73309]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
nj6-gvD8z0Y9bDSsAAAA: Sending packet OPEN data {'sid': 'nj6-gvD8z0Y9bDSsAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
INFO:     127.0.0.1:43712 - "GET /socket.io/?transport=polling&EIO=4&t=1728948242.3482609 HTTP/1.1" 200 OK
Invalid transport for session nj6-gvD8z0Y9bDSsAAAA (further occurrences of this error will be logged with level INFO)
INFO:     ('127.0.0.1', 43712) - "WebSocket /socket.io/?transport=websocket&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA&t=1728948242.350583" 403
INFO:     connection rejected (403 Forbidden)
INFO:     connection closed
nj6-gvD8z0Y9bDSsAAAA: Received packet MESSAGE data 0{}
connect  z6XI1E8PZ8S6e9JbAAAB
nj6-gvD8z0Y9bDSsAAAA: Sending packet MESSAGE data 0{"sid":"z6XI1E8PZ8S6e9JbAAAB"}
INFO:     127.0.0.1:43732 - "POST /socket.io/?transport=polling&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA HTTP/1.1" 200 OK
INFO:     127.0.0.1:43722 - "GET /socket.io/?transport=polling&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA&t=1728948242.3515918 HTTP/1.1" 200 OK
nj6-gvD8z0Y9bDSsAAAA: Received packet MESSAGE data 1
disconnect  z6XI1E8PZ8S6e9JbAAAB
nj6-gvD8z0Y9bDSsAAAA: Received packet CLOSE data
INFO:     127.0.0.1:43736 - "POST /socket.io/?transport=polling&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA HTTP/1.1" 200 OK
```

client:
```
Attempting polling connection to http://localhost:8000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'nj6-gvD8z0Y9bDSsAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to ws://localhost:8000/socket.io/?transport=websocket&EIO=4
WebSocket upgrade failed: connection error
Sending polling GET request to http://localhost:8000/socket.io/?transport=polling&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA
Received packet MESSAGE data 0{"sid":"z6XI1E8PZ8S6e9JbAAAB"}
Sending polling GET request to http://localhost:8000/socket.io/?transport=polling&EIO=4&sid=nj6-gvD8z0Y9bDSsAAAA
Namespace / is connected
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Exiting write loop task
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<AsyncClient._read_loop_polling() done, defined at <pythondir>/lib/python3.11/site-packages/engineio/async_client.py:494> exception=AttributeError("'NoneType' object has no attribute 'connect'")>
Traceback (most recent call last):
  File "<pythondir>/lib/python3.11/site-packages/engineio/async_client.py", line 499, in _read_loop_polling
    r = await self._send_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<pythondir>/lib/python3.11/site-packages/engineio/async_client.py", line 442, in _send_request
    return await http_method(
           ^^^^^^^^^^^^^^^^^^
  File "<pythondir>/lib/python3.11/site-packages/aiohttp/client.py", line 661, in _request
    conn = await self._connector.connect(
                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connect'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x754c2163f3d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x754c210b8c90>, 15882.461154256)]']
connector: <aiohttp.connector.TCPConnector object at 0x754c210d9b10>
```

**Expected behavior**
When downgrading to `python-engineio=4.9.1` everything works normally with client/server showing successful upgrade to websocket.

server:
```
Server initialized for asgi.
INFO:     Started server process [76519]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
AQ3TDzLU53C5QlCpAAAA: Sending packet OPEN data {'sid': 'AQ3TDzLU53C5QlCpAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
INFO:     127.0.0.1:38932 - "GET /socket.io/?transport=polling&EIO=4&t=1728949131.6001027 HTTP/1.1" 200 OK
AQ3TDzLU53C5QlCpAAAA: Received request to upgrade to websocket
INFO:     ('127.0.0.1', 38932) - "WebSocket /socket.io/?transport=websocket&EIO=4&sid=AQ3TDzLU53C5QlCpAAAA&t=1728949131.602416" [accepted]
INFO:     connection open
AQ3TDzLU53C5QlCpAAAA: Upgrade to websocket successful
AQ3TDzLU53C5QlCpAAAA: Received packet MESSAGE data 0{}
connect  TzL2ud8oBGb3ryAjAAAB
AQ3TDzLU53C5QlCpAAAA: Sending packet MESSAGE data 0{"sid":"TzL2ud8oBGb3ryAjAAAB"}
INFO:     connection closed
disconnect  TzL2ud8oBGb3ryAjAAAB
```

client:
```
Attempting polling connection to http://localhost:8000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'AQ3TDzLU53C5QlCpAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to ws://localhost:8000/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet NOOP data
Received packet MESSAGE data 0{"sid":"TzL2ud8oBGb3ryAjAAAB"}
Namespace / is connected
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Write loop: WebSocket connection was closed, aborting
Exiting write loop task
Server sent close packet data None, aborting
Waiting for write loop task to end
Exiting read loop task
```

**Comment by code-haven** [comment]
We use Flask-SocketIO in our backend and we noticed that after a deployment today, all our socketio endpoints switched to HTTP protocol. We tried downgrading direct dependencies but never thought of transitive deps lke python-engineio. Thank you @BobakBaghi 😭

**Comment by miguelgrinberg** [comment]
Please upgrade python-engineio to 4.10.1 for the fix.
