### ISSUE TITLE
CancelledError cannot be handled properly in socketio

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#144]
We can't handle cancellederror correctly therefor our applications receieve so many cancellederros in errorlog. and the service were shutdown sometimes. we asked experts in aiohttp and aiojobs , we were told that the actual cause could be only related with python-socketio.

[The more information are in the thread which were just moved from aiojobs](https://github.com/aio-libs/aiojobs/issues/18)

**Comment by larry-dev** [comment]
Can you help me!!!

**Comment by miguelgrinberg** [comment]
Do you have stack traces that show these errors please?

**Comment by larry-dev** [comment]
'''
[2017-11-05 22:41:04][ERROR][Traceback (most recent call last):
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 19, in poll
    self.server.ping_timeout)]
  File "/usr/local/python36/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wwwroot/ykrealtime/rtgame/middleware.py", line 34, in middleware_handler
    response = await handler(request)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_server.py", line 138, in handle_request
    b64)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_server.py", line 253, in _handle_connect
    return self._ok(await s.poll(), headers=headers, b64=b64)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 22, in poll
    raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty
][middleware.py][59]
'''

**Comment by miguelgrinberg** [comment]
@larry-dev looks like the stack trace that you pasted is not complete. Can you please show me the complete chain of stack traces?

**Comment by larry-dev** [comment]
'''
Traceback (most recent call last):
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aioredis/util.py", line 79, in wait_make_dict
    res = yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 726, in gen_move
    game, err = await self.__get_game_chess_status(hall, room, user_id)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 3276, in __get_game_chess_status
    game = await redis.hgetall(REDIS_KEY['RT_GAME'].format(hall, room))
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aioredis/util.py", line 81, in wait_make_dict
    res = yield from fut
concurrent.futures._base.CancelledError

message async handler error
Traceback (most recent call last):
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aioredis/util.py", line 79, in wait_make_dict
    res = yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 726, in gen_move
    game, err = await self.__get_game_chess_status(hall, room, user_id)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 3276, in __get_game_chess_status
    game = await redis.hgetall(REDIS_KEY['RT_GAME'].format(hall, room))
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aioredis/util.py", line 81, in wait_make_dict
    res = yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/engineio/asyncio_server.py", line 266, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 362, in _handle_eio_message
    await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 292, in _handle_event
    await self._handle_event_internal(self, sid, data, namespace, id)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 295, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/socketio/asyncio_server.py", line 323, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/middleware.py", line 73, in wrapper
    return await job.wait()
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aiojobs/_job.py", line 56, in wait
    raise exc
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/venv/lib/python3.6/site-packages/aiojobs/_job.py", line 53, in wait
    return await self._task
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/views/rtgame.py", line 131, in gen_move
    await factory.gen_move(data)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/factories/siofactory.py", line 326, in gen_move
    result, push_msg = await self.game_logic.gen_move(hall, room, user_id, move)
  File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 829, in gen_move
    raise RTException(e)
rtgame.commons.rtexception.RTException
'''

**Comment by larry-dev** [comment]
@miguelgrinberg 
We have a scenario that requires the user to close the application and continue processing the data.
but the user close application threw cancelled from aioredis.
So it looks like this, and I don't know if you can work it out

**Comment by miguelgrinberg** [comment]
@larry-dev correct me if I'm wrong, but this stack trace generated a `CancelledError` while your application was working with Redis. I don't see anything that indicates that Socket.IO was accessing Redis when the cancellation occurred.

The cancellation occurred here if I'm not mistaken:

```
File "/Users/larryliu/Documents/01-Project/python/ykrealtime/rtgame/logics/gamelogic.py", line 726, in gen_move
game, err = await self.__get_game_chess_status(hall, room, user_id)
```

So shouldn't you catch the `CancelledError` exception and deal with it as appropriate for your application?

**Comment by larry-dev** [comment]
@miguelgrinberg you are right.now i catch the `CancelledError` exception and retry.solved the problem.

**Comment by larry-dev** [comment]
thx a lot
