### ISSUE TITLE
websocket not working with sanic

### ISSUE THREAD

**Issue by myrfy001** [miguelgrinberg/python-socketio#147]
WIth the following environment:
```
python  3.6.1
python-engineio==2.0.0
python-socketio==1.8.3
sanic==0.6.0
websockets==4.0.1
uvloop==0.8.1
```
running the sanic example in `example/sanic` got the following error and the websocket can't be used while the aiohttp example works fine.

```
2017-11-21 20:32:54 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/asyncio_server.py", line 146, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 75, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 116, in _upgrade_websocket
    return await ws(environ)
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/async_sanic.py", line 122, in __call__
    await self.handler(self)
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 124, in _websocket_handler
    pkt = await ws.wait()
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/engineio/async_sanic.py", line 131, in wait
    data = await self._sock.recv()
  File "/Users/mmhh/.pyenv/versions/misc/lib/python3.6/site-packages/websockets/protocol.py", line 309, in recv
    loop=self.loop, return_when=asyncio.FIRST_COMPLETED)
  File "/Users/mmhh/.pyenv/versions/3.6.1/lib/python3.6/asyncio/tasks.py", line 305, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/Users/mmhh/.pyenv/versions/3.6.1/lib/python3.6/asyncio/tasks.py", line 305, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/Users/mmhh/.pyenv/versions/3.6.1/lib/python3.6/asyncio/tasks.py", line 520, in ensure_future
    raise TypeError('A Future, a coroutine or an awaitable is required')
TypeError: A Future, a coroutine or an awaitable is required
```

**Comment by miguelgrinberg** [comment]
Looks like the websockets 4.0 and up versions are causing this problem. Downgrading to 3.4 resolves it for me. I'll have to investigate what changed on that release.
