### ISSUE TITLE
After last disconnect, can't connect again

### ISSUE THREAD

**Issue by Sefirq** [miguelgrinberg/python-socketio#148]
Hello,

I'm using python-socketio which sends jsons generated by my generator and when I run this server, my Apache Flink collects strings as Java socket io-client. Each client from Java connects and on /connect event and I register him to specific room. If there is no thread, whose task is to emit one json, then sleep for 1 second, we create it. Event hello is awaited in Java client, you can see the server code:

```
@sio.on('connect')
async def connect(sid, _):
    sio.enter_room(sid=sid, room='main_room')
    global thread
    print("connect ", sid)
    if thread is None:
        thread = sio.start_background_task(target=emit_constantly)

async def emit_constantly():
    database_connection = DatabaseConnector()
    receipt_creator = ReceiptCreator(database_connection.session)
    while True:
        await sio.emit('hello', data=receipt_creator.construct_receipt(), room='main_room')
        sleep(1)

@sio.on('disconnect')
def disconnect(sid):
    sio.leave_room(sid=sid, room='main_room')
    print('disconnect ', sid)
```

On disconnect event, the client leaves the room.

My issue is that when I have initial state, I can connect to the server and I can see printed "connect [sid]". But always, the first client must connect twice (the first connection is established and immediately closed, but disconnect comes to us after ~1 minute). Then, if I connect with second client before disconnecting the first one (I mean, before we see print('disconnect', sid)), he will generate event connect and he will work. But if I wait till the first one is disconnected, I can't connect again from any client, no matter how long I wait, or how many times I try.

The background task is still emitting events (logger says so) and in **receipt_creator.construct_receipt()**
method, we create an object, which has many fields taken from database and it contains randomizing (we can add a product to the receipt, but it is not necessary, for now we have limited this method to maximally generate 5 products (so the json is not very very very long) but it still won't work.

Additionally, sometimes (especially when we omit this "generate max 5 products"), on the server side we can see following error:

```
Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_socket.py", line 19, in poll
self.server.ping_timeout)]
File "/usr/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 416, in start
resp = yield from self._request_handler(request)
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 323, in _handle
resp = yield from handler(request)
File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_server.py", line 138, in handle_request
b64)
File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_server.py", line 253, in _handle_connect
return self._ok(await s.poll(), headers=headers, b64=b64)
File "/usr/local/lib/python3.6/dist-packages/engineio/asyncio_socket.py", line 22, in poll
raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty
```

Do you have any idea what can be the reason for this? Can it be any kind of error inside the **receipt_creator.construct_receipt()** method (for example with the connection to database), or is it because of clients, or, I don't know...

Best Regards

Sefirq

**Comment by miguelgrinberg** [comment]
First of all, that `sleep(1)` needs to be changed to `await asyncio.sleep(1)`. You can't block with a regular sleep call.

As far as the connection problems, I suggest you enable logging to see if that provides any additional information. It's strange that your first connection gets disconnected immediately, that is not normal. Are you using the official Socket.IO client for Java for this?

**Comment by Sefirq** [comment]
Okay, so firstly, when I change to await scyncio.sleep(1), it generates one event and won't emit more events.

As for logging, I had it enabled via 
```sio = socketio.AsyncServer(logger=True)```

and then the whole output looks like this:
```
======== Running on http://0.0.0.0:2137 ========
(Press CTRL+C to quit)
5694043812294058a3b142869c83e529 is entering room main_room [/]
connect  5694043812294058a3b142869c83e529
emitting event "hello" to main_room [/]
81c6a260990a4517a657fd75ffff5b26 is entering room main_room [/]
connect  81c6a260990a4517a657fd75ffff5b26
```

**Comment by miguelgrinberg** [comment]
> Okay, so firstly, when I change to await asyncio.sleep(1), it generates one event and won't emit more events.

You need to look into this, this is not expected. You probably have other blocking things somewhere else in your application.

As for the logging, add `engineio_logger=True` for more detailed information, but this is not going to be useful until you get your application to run unblocked, so look at the other problem first.

**Comment by Sefirq** [comment]
Sorry, I did not import asyncio module, so I will try to recreate my message so it may help others:

"Okay, so firstly, when I change to await asyncio.sleep(1), it generates one event and won't emit more events." <- just import fail
"I enabled logger and this is the input:

```======== Running on http://0.0.0.0:2137 ========
(Press CTRL+C to quit)
5694043812294058a3b142869c83e529 is entering room main_room [/]
connect  5694043812294058a3b142869c83e529
emitting event "hello" to main_room [/]
81c6a260990a4517a657fd75ffff5b26 is entering room main_room [/]
connect  81c6a260990a4517a657fd75ffff5b26
```

Basically: for now it seems to work with this asyncio sleep, I will test it better and if everything is OK, I will close this issue in a day or two, thanks a lot for responding so quickly :+1:

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Seeing that I haven't responded to your last comment, it is quite possible that I have dropped the ball on this issue and I apologize about that. If that is the case, do not take the closing of the issue personally as it is an automated process doing it, just reopen it and I'll get back to you.
