### ISSUE TITLE
error happens when using socketio with aiohttp3.0.9

### ISSUE THREAD

**Issue by chenray844** [miguelgrinberg/python-socketio#174]
@miguelgrinberg 
run `python3 examples/aiohttp/app.py`

```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
message async handler error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/engineio/asyncio_server.py", line 269, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/asyncio_server.py", line 358, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Client disconnected
```

## versions
```
python 3.6.2
python-socketio 1.9.0
aiohttp 3.0.9
```

**Comment by chenray844** [comment]
sorry, there is already an issue https://github.com/miguelgrinberg/python-engineio/issues/66

**Comment by miguelgrinberg** [comment]
I don't see any errors here when I use the versions you indicate above. How do you get this error to appear?

**Comment by chenray844** [comment]
sorry.  
the example is below.
```javascript
namespace = '/test';
var socket = io.connect('http://' + document.domain + ':' + location.port + namespace);
```

my code 
```javascript
namespace = 'test';
var socket = io.connect('http://' + document.domain + ':' + location.port + namespace);

```
I lost the `/` in `namespace` in client code. 

and the server raise error as below 
```
message async handler error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/engineio/asyncio_server.py", line 269, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/asyncio_server.py", line 358, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It's my mistake, sorry.
