### ISSUE TITLE
ValueError: Invalid async_mode specified

### ISSUE THREAD

**Issue by anshumanvenkatesh** [miguelgrinberg/python-socketio#178]
This issue is similar to #35, but the instantiation is different. I tried adding 'engineio.async_gevent' to hiddenimports in spec file.

My usage is as follows: 

`from flask import Flask
from flask_cors import CORS
from flask_socketio import SocketIO
app = Flask(__name__)
CORS(app)
app.config['SECRET_KEY'] = 'some_secret_string'
socketio = SocketIO(app)
`

Getting the following error trace:
`Traceback (most recent call last):
  File "flask_app.py", line 5, in <module>
    from VBXExport import app, socketio
  File "d:\users\username\appdata\local\continuum\miniconda2\lib\site-packages\pyinstaller-3.3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "VBXExport\__init__.py", line 7, in <module>
    socketio = SocketIO(app)
  File "site-packages\flask_socketio-2.9.6-py2.7.egg\flask_socketio\__init__.py", line 162, in __init__
  File "site-packages\flask_socketio-2.9.6-py2.7.egg\flask_socketio\__init__.py", line 213, in init_app
  File "site-packages\python_socketio-1.9.0-py2.7.egg\socketio\server.py", line 89, in __init__
  File "site-packages\python_engineio-2.0.4-py2.7.egg\engineio\server.py", line 122, in __init__
ValueError: Invalid async_mode specified
[28660] Failed to execute script flask_app`

**Comment by kolinger** [comment]
I did have same issue. Problem was incorrect `hiddenimports` for my `python-engineio` version.

**python-engineio <=3.0 contains `engineio/async_threading.py` 
python-engineio >=3.1 contains `engineio/async_drivers/threading.py`**

In my case `hiddenimports=['engineio.async_drivers.threading']` was the solution.
