### ISSUE TITLE
pip installation fails with Python 3.6.5 and a clean virtual environment

### ISSUE THREAD

**Issue by xvzf** [miguelgrinberg/python-socketio#179]
The pip package seems to be broken for the Python 3.6.5 inside a virtual environment. Manually upgrading `setuptools` and `pkgtools` I can install the library from source but whenever I try to install it breaks some dependecies and downgrades pkgtools.

I haven't yet manage to figure out why that is but If I find the time to have a look I'll do a PR.

Steps to reproduce:
```
xvzf@lola /tmp % python --version
Python 3.6.5
xvzf@lola /tmp % python -m venv --system-site-packages venv
xvzf@lola /tmp % . ./venv/bin/activate
xvzf@lola /tmp % pip install socketio
Collecting socketio
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/72/95/7fa1739c9fd8ef671ebf1bbe7ae55cd1a9be17368a19a56731851311c533/socketio-0.0.7.tar.gz
Collecting setuptools==3.3 (from socketio)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/fc/20/0b304ea9830d53c9068e1e96bbf1ee529283f96ee0ee6ccaaa697f7b2383/setuptools-3.3-py2.py3-none-any.whl
Collecting netifaces==0.10.6 (from socketio)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/72/01/ba076082628901bca750bf53b322a8ff10c1d757dc29196a8e6082711c9d/netifaces-0.10.6.tar.gz
Installing collected packages: setuptools, netifaces, socketio
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Running setup.py install for netifaces ... error
    Complete output from command /tmp/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-odvwiwvr/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u8ker29c-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv/include/site/python3.6/netifaces:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/tmp/venv/lib/python3.6/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "/tmp/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-odvwiwvr/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u8ker29c-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv/include/site/python3.6/netifaces" failed with error code 1 in /tmp/pip-build-odvwiwvr/netifaces/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by miguelgrinberg** [comment]
Just to make sure others understand what happens, this package is called `python-socketio`, not `socketio`.
