### ISSUE TITLE
engineio bug when sending base64 image as data in message?

### ISSUE THREAD

**Issue by ecamaj** [miguelgrinberg/python-socketio#186]
```
2018-06-06 15:09:36,096 - AUTO - ERROR - message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 408, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 516, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/usr/local/lib/python3.5/dist-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/usr/local/lib/python3.5/dist-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 32107 (char 32106)
```
Any help appreciated.
Thanks!

**Comment by miguelgrinberg** [comment]
How can I reproduce this error? Do you have the client code that sends this event?

**Comment by ecamaj** [comment]
Thanks for the feedback. I will try to isolate it, if possible. Will let you know. Also, I have question for you, for private message. Have an email? Or contact me on linkedIn or somewhere. Thanks

**Comment by miguelgrinberg** [comment]
@ecamaj my email is first dot last at gmail.

**Comment by ecamaj** [comment]
Tell me if this helps, without writing client code (which might be complex, react app, ...)...

- JSON content in event is ~160k.
- log starts with:
`2018-06-07 07:32:22,511 - AUTO - INFO - de7ede54a1bf45adb776bbafafb40d19: Received packet MESSAGE data 2/socket,[...JSON DATA...`
**This JSON data is not completed till the end!!!**
- Error is logged:
```
2018-06-07 07:32:22,555 - AUTO - ERROR - message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 408, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 516, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/usr/local/lib/python3.5/dist-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/usr/local/lib/python3.5/dist-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 32230 (char 32229)
```
- **new log that CONTINUES the rest of the JSON data from event above:**
`2018-06-07 07:32:22,556 - AUTO - INFO - de7ede54a1bf45adb776bbafafb40d19: Received packet UNKNOWN data /6MFfN/gzwzJ4s1yPSg5ij2mWZx1CLwcD1JIA+t`

This `UNKNOWN` instead of the event name is also interesting.

So, what it looks to me is that message data is broken into two parts and engineio tries to do JSON decode on the *part* of the data which is not proper JSON since it is broken in two parts.

Makes sense? Helps?

**Comment by ecamaj** [comment]
@miguelgrinberg Is this helping?

**Comment by miguelgrinberg** [comment]
Not really. It's clear that something is off, but without having your code I'm not sure I'll be able to figure it out. Can you just make a simple JS example that sends an image exactly like you do in your real app?

**Comment by ecamaj** [comment]
Ok, I’ll try to isolate it. Thanks

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Seeing that I haven't responded to your last comment, it is quite possible that I have dropped the ball on this issue and I apologize about that. If that is the case, do not take the closing of the issue personally as it is an automated process doing it, just reopen it and I'll get back to you.

**Comment by Seraphli** [comment]
@ecamaj Have you manage to solve this problem? I ran into the same problem this morning. The same package sometimes worked well, and sometimes it was truncated.

**Comment by ecamaj** [comment]
Yes, it is uwsgi problem, I guess you are using uwsgi as python application server?

**Comment by Seraphli** [comment]
@ecamaj But my `async_mode` is set to `aiohttp`. Is `aiohttp` related to `uwsgi`?

**Comment by ecamaj** [comment]
hm, no, I don't think so.

**Comment by Seraphli** [comment]
Strange. How did you fix your problem?

**Comment by ecamaj** [comment]
Created fix in uwsgi and submitted pull request.

**Comment by igoras1993** [comment]
@ecamaj I am experiencing the same issue. Could You link Your PR to uwsgi repo? Cannot find one. I am using uwsgi 2.018

**Comment by ecamaj** [comment]
Here it is. https://github.com/unbit/uwsgi/pull/1853
