### ISSUE TITLE
Error installing for Python 3.7.0

### ISSUE THREAD

**Issue by TensorTom** [miguelgrinberg/python-socketio#190]
Had to switch to Python 3.6 in order to get working. Here's what happened with 3.7:
```
pip install socketio
Collecting socketio
  Using cached https://files.pythonhosted.org/packages/32/fb/8667be5433aa2f54c8111d37f75425789ef7425c1c8aaa65b99c36c460de/socketio-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-na00lkxq/socketio/
```

**Comment by miguelgrinberg** [comment]
The package is called `python-socketio`, you are installing a different package.

**Comment by fatalerrortan** [comment]
Hi, I installed really the right one "python-socketio" in my virtual environment. but I still keep getting this error

**Comment by EricvanLessen** [comment]
First uninstall ;)

**Comment by serge-eric-kalaga** [comment]
THANKS. This solution worked for me.
