### ISSUE TITLE
Invalid HTTP method

### ISSUE THREAD

**Issue by TensorTom** [miguelgrinberg/python-socketio#192]
I got the aio example running but it did throw some errors. I was still able to connect via browser and test everything out. Still, here's what I got when I started up https://github.com/miguelgrinberg/python-socketio/blob/master/examples/aiohttp/app.py

```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/websocket-Vj2iUHRo/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 230, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 297, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
Error handling request
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/websocket-Vj2iUHRo/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 230, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 297, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
