### ISSUE TITLE
How does client reconnect work?

### ISSUE THREAD

**Issue by Bennyhwanggggg** [miguelgrinberg/python-socketio#242]
I currently have a `socketio.Server()` and a `socketio.Client()` and when the server is killed  with `Ctr + C`, the client would just die but from reading the source code, I thought it should at least try to reconnect. 

I am wondering how to trigger reconnect behavior when client detect that the server has being killed?

**Comment by Bennyhwanggggg** [comment]
There is no output on the client side, it just simply stops.

**Comment by Bennyhwanggggg** [comment]
This is easily replicated by using the examples provided in the docs

client.py
````
import socketio

sio = socketio.Client()

@sio.on('connect')
def on_connect():
    print('connection established')

@sio.on('my message')
def on_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})

@sio.on('disconnect')
def on_disconnect():
    print('disconnected from server')

sio.connect('http://localhost:5000')
````

server.py
````
import engineio
import eventlet
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio)

@sio.on('connect')
def connect(sid, environ):
    print('connect ', sid)

@sio.on('message')
def message(sid, data):
    print('message ', data)

@sio.on('disconnect')
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
````

The console output on the server:
````
$python3 server.py
(77736) wsgi starting up on http://0.0.0.0:5000
(77736) accepted ('127.0.0.1', 50676)
connect  3df0a726b9b34c55a2cc7e07a1a23b48
127.0.0.1 - - [23/Jan/2019 23:03:38] "GET /socket.io/?transport=polling&EIO=3&t=1548252218.0137038 HTTP/1.1" 200 357 0.000812
(77736) accepted ('127.0.0.1', 50678)
^Cwsgi exiting
disconnect  3df0a726b9b34c55a2cc7e07a1a23b48
127.0.0.1 - - [23/Jan/2019 23:03:47] "GET /socket.io/?transport=websocket&EIO=3&sid=3df0a726b9b34c55a2cc7e07a1a23b48&t=1548252218.0195808 HTTP/1.1" 200 0 9.407103
(77736) wsgi exited, is_accepting=True
````

Console output on client side
````
$python3 client.py
connection established
$
````

**Comment by miguelgrinberg** [comment]
Yes, working on a fix at the moment. Thanks.

**Comment by miguelgrinberg** [comment]
This is now fixed in the python-engineio package. Please upgrade and let me know if there are still any problems!

**Comment by milteven12** [comment]
Hello Guys, should reconnect work on a AsyncClient if I close the server abruptly? (closing the window)?

**Comment by milteven12** [comment]
Hello @miguelgrinberg , my python-engineio version is 3.3.0 but client doesn't reconnect.

When server is closed, the client script breaks, here is the error:

`websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason`

Reconnection is configured as true, see below:

`sio = socketio.AsyncClient(reconnection=True, reconnection_attempts=100,
                           reconnection_delay=1, reconnection_delay_max=5,
                           randomization_factor=0.5, logger=True,
                           binary=False, json=None)`

Besides that, there is a way for me to make the server detect the disconnection from client when closed abruptly too?

Thank you for your time, have a good day!

**Comment by miguelgrinberg** [comment]
@milteven12 can I ask you to test the master branch of python-engineio and report back if you now get reconnects? To install the fix, use the following command while in your virtualenv:

    pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip

Thanks!

**Comment by miguelgrinberg** [comment]
@milteven12 please provide the full error, including the stack trace.

**Comment by milteven12** [comment]
Full error below:
```
Error in data transfer
Traceback (most recent call last):
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Traceback (most recent call last):
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\Scripts\SocketIO\client.py", line 64, in <module>
    loop.run_until_complete(start_server())
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\Scripts\SocketIO\client.py", line 59, in start_server
    await sio.connect('http://localhost:8080')
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\socketio\asyncio_client.py", line 102, in connect
    engineio_path=socketio_path)
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py", line 73, in connect
    url, headers, engineio_path)
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py", line 206, in _connect_polling
    if await self._connect_websocket(url, headers, engineio_path):
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py", line 247, in _connect_websocket
    pkt = packet.Packet(encoded_packet=await ws.recv())
  File "C:\Users\Casa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
>>>
 ```

**Comment by miguelgrinberg** [comment]
@milteven12 this error wasn't what I expected, I think I need your help in reproducing it here.

Based on what I see on the error, the problem occurred during the connection phase (it could be a first-time or a reconnection attempt, I have no way to know that from the stack trace). The HTTP connection was successful, but then the upgrade to websocket failed. I can make this process a bit more robust, but I fail to see how this is related to reconnections. The HTTP portion of the connection attempt worked fine, which means that your server was up.

**Comment by miguelgrinberg** [comment]
@milteven12 the master branch of python-engineio now handles the error that you are receiving properly. I think it does, at least, I have not been able to reproduce your situation here. Please reopen if the problem still occurs.

**Comment by karanBRAVO** [comment]
🤩 Checkout this code

```python
import socketio
import time


class SocketClient:
    def __init__(self, url: str):
        self.url = url
        self.sio = socketio.Client()

        @self.sio.event
        def connect():
            print("connection established")

        @self.sio.event
        def disconnect():
            print("disconnected from server")

    def send_message(self, evt, data):
        self.sio.emit(evt, data)

    def connect(self, user_details):
        while not self.sio.connected:
            try:
                self.sio.connect(self.url, transports=[
                    "websocket"], auth=user_details)
            except socketio.exceptions.ConnectionError as e:
                print(
                    f"Initial connection failed: {e}. Retrying...")
                time.sleep(5)

    def disconnect(self):
        self.sio.disconnect()

```
