### ISSUE TITLE
When i hit directly using IP, websocket works fine but when routed using nginx give following error. Please help. Can you also give nginx config for sanic.

### ISSUE THREAD

**Issue by sohilfynd** [miguelgrinberg/python-socketio#245]
[<engineio.packet.Packet object at 0x7efc00e69c88>, <engineio.packet.Packet object at 0x7efbfc504c50>] <class 'list'>
[2019-01-30 17:20:33 +0530] [11351] [ERROR] Invalid response object for url b'/ws/store-dashboard-feed/?from_date=2019-01-28T00%3A00%3A00Z&to_date=2019-01-31T23%3A59%3A59Z&brand=&store_id=616&page_no=1&page_length=20&lane=new&is_affiliate_order=true&EIO=3&transport=websocket', Expected Type: HTTPResponse, Actual Type: <class 'list'>
[2019-01-30 17:20:33 +0530] [11351] [ERROR] Exception occurred while handling uri: 'http://api-pre.addsale.com/ws/store-dashboard-feed/?from_date=2019-01-28T00%3A00%3A00Z&to_date=2019-01-31T23%3A59%3A59Z&brand=&store_id=616&page_no=1&page_length=20&lane=new&is_affiliate_order=true&EIO=3&transport=websocket'
Traceback (most recent call last):
  File "/home/deploy/.local/share/virtualenvs/computron-n7i6-y73/lib/python3.6/site-packages/sanic/server.py", line 375, in write_response
    response.output(
AttributeError: 'list' object has no attribute 'output'

**Comment by sohilfynd** [comment]
ac25bfd10344492a909c0e8cc14561f3: Sending packet OPEN data {'sid': 'ac25bfd10344492a909c0e8cc14561f3', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
ac25bfd10344492a909c0e8cc14561f3: Sending packet MESSAGE data 0
[<engineio.packet.Packet object at 0x7fccac82b6a0>, <engineio.packet.Packet object at 0x7fccac82b748>] <class 'list'>
[2019-01-30 17:44:31 +0530] [12927] [ERROR] Invalid response object for url b'/ws/store-dashboard-feed/?from_date=2019-01-28T00%3A00%3A00Z&to_date=2019-01-31T23%3A59%3A59Z&brand=&store_id=616&page_no=1&page_length=20&lane=new&is_affiliate_order=true&EIO=3&transport=websocket', Expected Type: HTTPResponse, Actual Type: <class 'list'>
[2019-01-30 17:44:31 +0530] [12927] [ERROR] Exception occurred while handling uri: 'http://api-pre.addsale.com/ws/store-dashboard-feed/?from_date=2019-01-28T00%3A00%3A00Z&to_date=2019-01-31T23%3A59%3A59Z&brand=&store_id=616&page_no=1&page_length=20&lane=new&is_affiliate_order=true&EIO=3&transport=websocket'
Traceback (most recent call last):
  File "/home/deploy/.local/share/virtualenvs/computron-n7i6-y73/lib/python3.6/site-packages/sanic/server.py", line 375, in write_response
    response.output(
AttributeError: 'list' object has no attribute 'output'

**Comment by miguelgrinberg** [comment]
And you are sure your nginx configuration is appropriate for Socket.IO? Here is an example valid config: https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy

**Comment by sohilfynd** [comment]
location /computron/ws {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade "Websocket";
        proxy_set_header Connection "Upgrade";
        rewrite ^/computron(.*) $1 break;
        proxy_pass http://computron/ws;
    }

This is my nginx config for route. I am getting 101 but Connection header has keep-alive which i think should be "Upgrade".


I am getting this in debug mode:

2bc12be325954499817ce57e7dd2af86: Sending packet OPEN data {'sid': '2bc12be325954499817ce57e7dd2af86', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2bc12be325954499817ce57e7dd2af86: Sending packet MESSAGE data 0
2bc12be325954499817ce57e7dd2af86: Received request to upgrade to websocket
2bc12be325954499817ce57e7dd2af86: Upgrade to websocket successful

**Comment by miguelgrinberg** [comment]
I can't really help you because I do not know what endpoints you have defined. It appears nginx is not routing your Socket.IO endpoint correctly from the logs.

**Comment by sohilfynd** [comment]
Thanks for the help. There was the issue with my office server. It was adding Connection as Keep-alive. One more thing I am getting following Error, when i am using ensure_future to run mongo db watcher in background. Can you suggest some best practice to implement mongodb watcher with sanic and socketio?. I am giving watcher forever task to ensure_future which i cancel on disconnect of client. After some time it stops accepting request and continously gives the below error.
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f82782efef0 state=cancelled>.

Please help me with watcher and socket.io.

**Comment by miguelgrinberg** [comment]
@sohilfynd I don't think this error is related to socket.io at all. You are either using an non-async mongo library, or some error is occurring in that task.
