### ISSUE TITLE
Binary data through AsyncServer and AsyncClient

### ISSUE THREAD

**Issue by maksutovaynur** [miguelgrinberg/python-socketio#251]
How to send/receive binary data?
When I'm trying to send binary using AsyncClient and receive using AsyncServer, an error raises:
"TypeError: Object of type bytes is not JSON serializable".

**Comment by miguelgrinberg** [comment]
Please include the full stack trace of the error.

**Comment by chinnaxs** [comment]
I also have trouble directly putting a 'bytes' object into 'emit' as parameter.

```
            msg = bytes.fromhex('deadbeef')
            self.sio.emit('bytes',msg)
```
TypeError: Object of type 'bytes' is not JSON serializable

Even though the [documentation](https://python-socketio.readthedocs.io/en/latest/) says it should be possible?
`The single argument provided to the method is the data that is passed on to the server. The data can be of type str, bytes, dict or list. The data included inside dictionaries and lists is also constrained to these types.`
Using:
python-socketio==3.1.2
socketIO-client==0.7.2

Trace:
`Traceback (most recent call last):
  File "simple_client.py", line 32, in <module>
    simple_client('127.0.0.1', 5000)
  File "simple_client.py", line 11, in __init__
    self.sio.wait()
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "simple_client.py", line 23, in on_request_bytes
    self.sio.emit('bytes', {"msg": b'asdf'})
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 432, in emit
    socketIO_packet_data = format_socketIO_packet_data(path, ack_id, args)
  File "/home/mlei/anaconda3/lib/python3.6/site-packages/socketIO_client/parsers.py", line 58, in format_socketIO_packet_data
    socketIO_packet_data = json.dumps(args, ensure_ascii=False) if args else ''
  File "/home/mlei/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/mlei/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/mlei/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/mlei/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
`

**Comment by miguelgrinberg** [comment]
@chinnaxs you are using the `socketIO-client==0.7.2` package for your client. You have to ask them about this problem, it's a different project I'm not involved with.

@maksutovaynur Still waiting to see your stack trace. Please reopen when you are ready to provide this additional information.
