### ISSUE TITLE
Connection to a Django-channels server is hanging

### ISSUE THREAD

**Issue by gabrielguerrer** [miguelgrinberg/python-socketio#268]
When running a very basic channels server (https://channels.readthedocs.io/en/latest/tutorial/index.html), although the connection is accepted in the server side, it freezes in the client side when running sio.connect() . Any idea?

**Comment by miguelgrinberg** [comment]
This is Socket.IO, not channels or WebSocket. You have to use a WebSocket client I suppose. With this package you can only connect to a Socket.IO server.

**Comment by felocru** [comment]
Hello @miguelgrinberg I had a little time to experience django-channels.
Actually django-channels implements the ASGI specification and manages a concept called Consumers, basically these consumers are defined with a protocol. For example WebSockets, MQTT, chatbots, amateur radio, and more.

While Channels is built around a basic low-level spec called ASGI, it’s more designed for interoperability than for writing complex applications in.

So on that premise Socket.IO can be a consumer, django channels is responsible for routing the socket.io/ route to the appropriate consumer.

The added value of using django-channels is that it allows Django to be asynchronous, without relying on libraries like gevent or evenlet.

I already made my first tests, when I put in front the `socketio.ASGIApp` works like a charm. Since I understand that socketio routes correctly.
This is my code in asgi.py:
```
import os
import django
# import uvicorn
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "prueba.settings")
django.setup()
application = get_default_application()

# if __name__ == '__main__':
    # from socketio.server import Socket
import socketio
sio = socketio.AsyncServer(async_mode='asgi')
# app = socketio.WSGIApp(application)
application = socketio.ASGIApp(sio,application)



@sio.on('connect', namespace='/test')
async def test_connect(sid, environ):
    print(environ)
    await sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid,
             namespace='/test')


@sio.on('disconnect', namespace='/test')
async def test_disconnect(sid):
    print('Client disconnected')
```
Then: `uvicorn test.asgi:application` Yeah! :)

But when I pass the socketio as a consumer, I do not have much success. Since I receive:
```
from channels.consumer import AsyncConsumer
from channels.generic.websocket import WebsocketConsumer
from engineio.async_drivers.asgi import WebSocket

import socketio
sio = socketio.AsyncServer(async_mode='asgi')
class SocketioNamespace(AsyncConsumer, socketio.AsyncNamespace):
    # async def websocket_connect(self, event):
         
    #     await self.send({
    #         "type": "websocket.accept",
    #     })
    # async def websocket_receive(self, event):
    #     await self.send({
    #         "type": "websocket.send",
    #         "text": event["text"],
    #     })
    def on_connect(self, sid, environ):
        pass

    def on_disconnect(self, sid):
        pass

    async def on_my_event(self, sid, data):
        await self.emit('my_response', data)

SocketioConsumer = SocketioNamespace('/test')
sio.register_namespace(SocketioConsumer)
```
I get on screen:
`AttributeError: 'SocketioNamespace' object has no attribute 'namespace'`
In routing.py
```
websocket_urlpatterns = [
    url(r'socket.io/$', consumers.SocketioConsumer),
]
```

Well, in summary, I have the feeling that it is possible to use it as a consumer. But I do not have much experience to achieve it. Any small ideas that you can give me?
Or do you believe that this is not possible?

**Comment by miguelgrinberg** [comment]
@felocru I need to see the complete stack trace of your error please.

**Comment by felocru** [comment]
I have this:
```
Traceback (most recent call last):
  File "/home/felocru/.virtualenvs/newdjango/bin/uvicorn", line 10, in <module>
    sys.exit(main())
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/main.py", line 256, in main
    run(**kwargs)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/main.py", line 277, in run
    server.run()
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/main.py", line 304, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/main.py", line 311, in serve
    config.load()
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/config.py", line 179, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./prueba/asgi.py", line 13, in <module>
    application = get_default_application()
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/routing.py", line 33, in get_default_application
    module = importlib.import_module(path)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./prueba/routing.py", line 3, in <module>
    import socketio_app.routing
  File "./socketio_app/routing.py", line 3, in <module>
    from . import consumers
  File "./socketio_app/consumers.py", line 28, in <module>
    sio.register_namespace(SocketioConsumer)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/socketio/server.py", line 202, in register_namespace
    namespace_handler
AttributeError: 'SocketioNamespace' object has no attribute 'namespace'
```

But I changed the order of the signature and the problem disappeared:
` class SocketioNamespace(AsyncConsumer, socketio.AsyncNamespace):`
to
`class SocketioNamespace(socketio.AsyncNamespace, AsyncConsumer):`

When I run `uvicorn prueba.asgi: application` everything seems fine.

However when I want to connect to the demo namespace I get:

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 146, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
    instance = self.app(scope)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/routing.py", line 58, in __call__
    return self.application_mapping[scope["type"]](scope)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return self.inner(dict(scope, cookies=cookies))
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/sessions.py", line 145, in __call__
    return SessionMiddlewareInstance(scope, self)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/sessions.py", line 169, in __init__
    self.inner = self.middleware.inner(self.scope)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/middleware.py", line 31, in __call__
    inner_instance = self.inner(scope)
  File "/home/felocru/.virtualenvs/newdjango/lib/python3.6/site-packages/channels/routing.py", line 144, in __call__
    "kwargs": {**outer.get("kwargs", {}), **kwargs},
TypeError: __call__() missing 1 required positional argument: 'send'
```

**Comment by felocru** [comment]
I think it's a problem with the ProtocolTypeRouter.
I have this information from the scope.
`{'type': 'websocket', 'scheme': 'ws', 'server': ('127.0.0.1', 8000), 'client': ('127.0.0.1', 58898), 'root_path': '', 'path': '/socket.io/', 'query_string': b'EIO=3&transport=websocket', 'headers': [(b'host', b'127.0.0.1:8000'), (b'connection', b'Upgrade'), (b'pragma', b'no-cache'), (b'cache-control', b'no-cache'), (b'upgrade', b'websocket'), (b'origin', b'https://amritb.github.io'), (b'sec-websocket-version', b'13'), (b'user-agent', b'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36'), (b'accept-encoding', b'gzip, deflate, br'), (b'accept-language', b'es-US,es;q=0.9,es-419;q=0.8,en-US;q=0.7,en;q=0.6'), (b'sec-websocket-key', b'k9kVrZ8Jb4wFgSH6kkhxmA=='), (b'sec-websocket-extensions', b'permessage-deflate; client_max_window_bits')], 'subprotocols': []}`

I will continue investigating, even if you wish. You can share the test project.
Thank you.

**Comment by felocru** [comment]
In the documentation of channels says:
It’s possible to have routers from third-party apps, too, or write your own, but we’ll go over the built-in Channels ones here.

Example:
from django.conf.urls import url

from channels.routing import ProtocolTypeRouter, URLRouter
from channels.auth import AuthMiddlewareStack

from chat.consumers import AdminChatConsumer, PublicChatConsumer
from aprs_news.consumers import APRSNewsConsumer
```
application = ProtocolTypeRouter({

    # WebSocket chat handler
    "websocket": AuthMiddlewareStack(
        URLRouter([
            url(r"^chat/admin/$", AdminChatConsumer),
            url(r"^chat/$", PublicChatConsumer),
        ])
    ),

    # Using the third-party project frequensgi, which provides an APRS protocol
    "aprs": APRSNewsConsumer,
})
```
Then aprs can be the socket websocket.

Here is more information:
[](https://channels.readthedocs.io/en/latest/topics/routing.html)

**Comment by miguelgrinberg** [comment]
@felocru yes, the error comes from inheriting from two base classes, the AsyncConsumer class is preventing the initialization of the AsyncNamespace side. So you seem to have figured out a way to work around that problem.

Setting that aside, I really don't understand what you are trying to do. It may be possible to implement channels as a driver I guess, but you are trying to run both channels and Socket.IO together and somehow connect them, which I don't see how it would work since they are competing protocols.

**Comment by felocru** [comment]
Hello @miguelgrinberg, I really just wanted to use this library when django-channels detect the websocket protocol. Since the main feature of channels is to route per protocol.

I have not succeeded, however I will handle it like the first time. That is, putting forward socketio, with this:

```
sio = socketio.AsyncServer(async_mode='asgi')
# app = socketio.WSGIApp(application)
application = socketio.ASGIApp(sio,application)
```

Thanks for reading me

**Comment by miguelgrinberg** [comment]
Yes, this is the way I envisioned you would integrate with an ASGI application.

I think using channels as a low-level transport for Socket.IO is possible, but it is a much more complex problem to solve. Basically you would need to add another "async_mode" to Socket.IO. Also note that Socket.IO is not only WebSocket, it uses HTTP as well.

**Comment by felocru** [comment]
Hello, I want shared this repo.
Someone already made it
https://github.com/ly3too/django-channels-with-socket.io
