### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by drewbutcher** [miguelgrinberg/python-socketio#286]
I have a flask application using a factory function 

app\utils\socket_utils.py file
```python
from app import sio
...
@sio.on('message', namespace='/1.0/deep')
def on_message(data):
    print("I have a new set of data = {}".format(data))

@sio.on('connect', namespace='/1.0/deep')
def on_connect():
    print("Connection :)")


@sio.on('disconnect', namespace='/1.0/deep')
def on_disconnect():
    print("Disconnected :(")
```

app\utils\celery_utils.py file
```python
from app import sio, celery
...
@celery.task
def connect_for_trading():
    sio.connect('https://ws-api.iextrading.com', namespaces=['/1.0/deep'])
    sio.sleep(4) # needed this to prevent the emit from executed prior to connection, is there a check that can happen here?
    sio.emit('subscribe', json.dumps({'symbols': ['aapl'], 'channels': ['deep']}), namespace='/1.0/deep')
```
app\\_\_init\_\_.py for the app

```python
import socketio
from celery import Celery
from flask import Flask
...
from flask_sqlalchemy import SQLAlchemy
...

# Celery handler for offloading task to Redis
celery = Celery(__name__, broker=BaseConfig.CELERY_BROKER_URL)
# Socketio Connector
sio = socketio.Client(logger=True, engineio_logger=True)
...
def create_app(config_name):
    """Create an application instance."""
    app = Flask(__name__)
    ...
    return app
```

The terminal output logs showing error: 'No application found. Either work inside a view function or push'.
```
(venv) Computer:folderName user$ celery worker -A celery_worker.celery --loglevel=info --beat
Importing environment from .env-folderName ...
done
 
 -------------- celery@Computer.local v4.2.1 (windowlicker)
---- **** ----- 
--- * ***  * -- Darwin-18.2.0-x86_64-i386-64bit 2019-04-03 14:31:10
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         app:0x105403438
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . app.utils.celery_tasks.connect_for_trading
  . app.utils.celery_tasks.update_securities
  . app.utils.email_utils.send_async_email

[2019-04-03 14:31:10,655: INFO/Beat] beat: Starting...
[2019-04-03 14:31:10,741: INFO/Beat] Scheduler: Sending due task connect_for_trading (app.utils.celery_tasks.connect_for_trading)
[2019-04-03 14:31:10,933: INFO/MainProcess] Connected to redis://localhost:6379/0
[2019-04-03 14:31:10,947: INFO/MainProcess] mingle: searching for neighbors
[2019-04-03 14:31:11,972: INFO/MainProcess] mingle: all alone
[2019-04-03 14:31:11,986: INFO/MainProcess] celery@Computer.local ready.
[2019-04-03 14:31:12,184: INFO/MainProcess] Received task: app.utils.celery_tasks.connect_for_trading[db3a72e9-05ee-4f99-b471-6019253d4638]  
Attempting polling connection to https://ws-api.iextrading.com/socket.io/?transport=polling&EIO=3
[2019-04-03 14:31:12,188: INFO/ForkPoolWorker-3] Attempting polling connection to https://ws-api.iextrading.com/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': '4gpfL46OGg9py0DsACoA', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000}
[2019-04-03 14:31:12,677: INFO/ForkPoolWorker-3] Polling connection accepted with {'sid': '4gpfL46OGg9py0DsACoA', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
[2019-04-03 14:31:12,678: INFO/ForkPoolWorker-3] Engine.IO connection established
Attempting WebSocket upgrade to wss://ws-api.iextrading.com/socket.io/?transport=websocket&EIO=3
[2019-04-03 14:31:12,679: INFO/ForkPoolWorker-3] Attempting WebSocket upgrade to wss://ws-api.iextrading.com/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
[2019-04-03 14:31:12,924: INFO/ForkPoolWorker-3] WebSocket upgrade was successful
Sending packet PING data None
[2019-04-03 14:31:12,925: INFO/ForkPoolWorker-3] Sending packet PING data None
Received packet MESSAGE data 0
[2019-04-03 14:31:13,004: INFO/ForkPoolWorker-3] Received packet MESSAGE data 0
Namespace / is connected
[2019-04-03 14:31:13,006: INFO/ForkPoolWorker-3] Namespace / is connected
Sending packet MESSAGE data 0/1.0/deep
[2019-04-03 14:31:13,006: INFO/ForkPoolWorker-3] Sending packet MESSAGE data 0/1.0/deep
Received packet PONG data None
[2019-04-03 14:31:13,007: INFO/ForkPoolWorker-3] Received packet PONG data None
Received packet MESSAGE data 0/1.0/deep,
[2019-04-03 14:31:13,047: INFO/ForkPoolWorker-3] Received packet MESSAGE data 0/1.0/deep,
Namespace /1.0/deep is connected
[2019-04-03 14:31:13,048: INFO/ForkPoolWorker-3] Namespace /1.0/deep is connected
[2019-04-03 14:31:13,049: WARNING/ForkPoolWorker-3] Connection :)
Emitting event "subscribe" [/1.0/deep]
[2019-04-03 14:31:16,927: INFO/ForkPoolWorker-3] Emitting event "subscribe" [/1.0/deep]
Sending packet MESSAGE data 2/1.0/deep,["subscribe","{\"symbols\": [\"aapl\"], \"channels\": [\"deep\"]}"]
[2019-04-03 14:31:16,928: INFO/ForkPoolWorker-3] Sending packet MESSAGE data 2/1.0/deep,["subscribe","{\"symbols\": [\"aapl\"], \"channels\": [\"deep\"]}"]
[2019-04-03 14:31:16,933: INFO/ForkPoolWorker-3] Task app.utils.celery_tasks.connect_for_trading[db3a72e9-05ee-4f99-b471-6019253d4638] succeeded in 4.746281493000424s: None
Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"securityevent\",\"data\":{\"securityEvent\":\"MarketOpen\",\"timestamp\":1554298200001},\"seq\":1}"]
[2019-04-03 14:31:16,967: INFO/ForkPoolWorker-3] Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"securityevent\",\"data\":{\"securityEvent\":\"MarketOpen\",\"timestamp\":1554298200001},\"seq\":1}"]
Received event "message" [/1.0/deep]
[2019-04-03 14:31:16,968: INFO/ForkPoolWorker-3] Received event "message" [/1.0/deep]
[2019-04-03 14:31:16,969: WARNING/ForkPoolWorker-3] I have a new set of data = {"symbol":"AAPL","messageType":"securityevent","data":{"securityEvent":"MarketOpen","timestamp":1554298200001},"seq":1}
Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"ophaltstatus\",\"data\":{\"isHalted\":false,\"timestamp\":1554290551232},\"seq\":1}"]
[2019-04-03 14:31:16,976: INFO/ForkPoolWorker-3] Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"ophaltstatus\",\"data\":{\"isHalted\":false,\"timestamp\":1554290551232},\"seq\":1}"]
Received event "message" [/1.0/deep]
[2019-04-03 14:31:16,989: INFO/ForkPoolWorker-3] Received event "message" [/1.0/deep]
[2019-04-03 14:31:16,989: WARNING/ForkPoolWorker-3] I have a new set of data = {"symbol":"AAPL","messageType":"ophaltstatus","data":{"isHalted":false,"timestamp":1554290551232},"seq":1}
Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"tradingstatus\",\"data\":{\"status\":\"T\",\"reason\":\"    \",\"timestamp\":1554290551232},\"seq\":1}"]
[2019-04-03 14:31:16,995: INFO/ForkPoolWorker-3] Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"tradingstatus\",\"data\":{\"status\":\"T\",\"reason\":\"    \",\"timestamp\":1554290551232},\"seq\":1}"]
Received event "message" [/1.0/deep]
[2019-04-03 14:31:17,017: INFO/ForkPoolWorker-3] Received event "message" [/1.0/deep]
[2019-04-03 14:31:17,017: WARNING/ForkPoolWorker-3] I have a new set of data = {"symbol":"AAPL","messageType":"tradingstatus","data":{"status":"T","reason":"    ","timestamp":1554290551232},"seq":1}
Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"ssr\",\"data\":{\"isSSR\":false,\"detail\":\" \",\"timestamp\":1554290551232},\"seq\":1}"]
[2019-04-03 14:31:17,018: INFO/ForkPoolWorker-3] Received packet MESSAGE data 2/1.0/deep,["message","{\"symbol\":\"AAPL\",\"messageType\":\"ssr\",\"data\":{\"isSSR\":false,\"detail\":\" \",\"timestamp\":1554290551232},\"seq\":1}"]
Received event "message" [/1.0/deep]
...
[2019-04-03 14:31:17,033: WARNING/ForkPoolWorker-3] I have a new set of data = {"symbol":"AAPL","messageType":"trades","data":{"price":195.3500,"size":100,"tradeId":678815147,"isISO":false,"isOddLot":false,"isOutsideRegularHours":false,"isSinglePriceCross":false,"isTradeThroughExempt":false,"timestamp":1554316271992},"seq":4944}
[2019-04-03 14:31:17,042: WARNING/ForkPoolWorker-3] Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 123145538134016

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 514, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 413, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 455, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/user/Documents/folderName/app/utils/socket_utils.py", line 10, in on_message
    status_active = Status.query.filter_by(name='Active').first()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 74, in __call__
    return self.registry()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
[2019-04-03 14:31:17,043: WARNING/ForkPoolWorker-3] Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 123145522368512

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 514, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 413, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/socketio/client.py", line 455, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/user/Documents/folderName/app/utils/socket_utils.py", line 10, in on_message
    status_active = Status.query.filter_by(name='Active').first()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 74, in __call__
    return self.registry()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
[2019-04-03 14:31:17,044: WARNING/ForkPoolWorker-3] Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Users/user/Documents/folderName/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 123145527623680

During handling of the above exception, another exception occurred:
...
```

I feel like i need to have something of the form: **with app.app_context():** in the function **connect_for_trading**

**Comment by miguelgrinberg** [comment]
The error is on the `on_message()` handler. It looks like you are doing database work there. To use the Flask-SQLAlchemy database you need the app context, so you need to wrap the contents of that function (or at least the database part) with 

    with app.app_context():
        # do database stuff here

**Comment by drewbutcher** [comment]
Thank you @miguelgrinberg. You are correct, I'm making Database calls in the on_message function.  

I'm not sure how to reference app in the file socket_utils.py (and which app I need to reference).

I followed the [Celery and the Flask Application Factory Pattern](https://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern) tutorial (thank you again). 
So if have a folder structure similar to the following.
```
folderName
|--app 
    |--auth
    |--main
    |--templates
    |--utils
        |-- __init__.py
        |-- celery_task.py
        |-- socket_utils.py
|--run.py
|--celery_worker.py
```

Does this mean that the **app** I need lives in the file celery_worker.py and I need to reference this from within socket_utils.py?

Or do I just make a new app instance like we did in the celery_worker.py file?
```python
from app import celery, create_app

app = create_app(os.environ.get('FLASK_CONFIG', 'development'))
```

Or should I use current_app from flask and do the following?
```python
from flask import current_app
...
with current_app.app_context():
    # do database stuff
```

Could I get around all this by using the celery decorator?  So something like this
```python
from app import db, sio, celery
...

@celery.task
@sio.on('message', namespace='/1.0/deep')
def on_message(payload):
    print("I have a new set of data = {}".format(payload))
```

I looked into Flask-SocketIO but I believe I'm the client in this situation and it sounds like Flask-SocketIO is not setup to act as a client.  I did look at the code to see how app_context was handled in the test file.    
```python
sio.connect('https://ws-api.iextrading.com', namespaces=['/1.0/deep'])
```

**Comment by miguelgrinberg** [comment]
> I looked into Flask-SocketIO but I believe I'm the client in this situation and it sounds like Flask-SocketIO is not setup to act as a client.

Oh, sorry, that's my mistake then. You are correct, Flask-SocketIO is only for the server.

The `on_message()` handler runs in the context of your server, not your celery worker. The `app` needs to be the application instance that you are using for the server. It looks like you are using the app factory pattern, so you'll have to figure out a way for your Socket.IO handler to be able to get that app instance so that it can set up an application context.

**Comment by drewbutcher** [comment]
@miguelgrinberg Thank you.

Any suggestion on how to import app from within the app folder in a factory pattern?  
I keep running into circular import issues.

**Comment by miguelgrinberg** [comment]
What worked for me many times is to put the import inside the function, not outside.

**Comment by drewbutcher** [comment]
I'm tired
```python
@sio.on('message', namespace='/1.0/deep')
def on_message(payload_string):
    from ....run import app
    with app.app_context():
```
which gave me the error: **ValueError: attempted relative import beyond top-level package**

This worked but I can't image it's a good solution.
```python
@sio.on('message', namespace='/1.0/deep')
def on_message(payload_string):
    app = create_app(os.environ.get('FLASK_CONFIG', 'development'))
    with app.app_context():
```

Thank you @miguelgrinberg for your time!

**Comment by miguelgrinberg** [comment]
Sorry I missed this. Instead of:

    from ....run import app

you could have used

    from run import app

Your second solution is bad, you are creating a brand new app object, unrelated to the one used by the server.

**Comment by drewbutcher** [comment]
run.py is on the same level as app and I'm calling this from within a blueprint (now main/events.py).  When I add the import to this file

`from run import app`

I receive **ImportError: cannot import name 'app'**

**Comment by miguelgrinberg** [comment]
@drewbutcher what do you have in run.py?

**Comment by drewbutcher** [comment]
```python
import eventlet
import os
import stripe
from flask_cors import CORS
from app import create_app, db, socketio_server
from app.models import Account, Action, Historical, Holiday, Like, Order, \
    OrderType, Profile, Role, Search, Security, Social, Status, Time, \
    Trade, User
from app.database import DatabaseSeeder
from app.utils import update_securities, connect_for_trading


app = create_app(os.getenv('FLASK_CONFIG') or 'development')
stripe.api_key = app.config['STRIPE_SECRET_KEY']
eventlet.monkey_patch()

@app.shell_context_processor
def make_shell_context():
    return dict(db=db,
                Account=Account,
                Action=Action,
                Historical=Historical,
                Holiday=Holiday,
                Like=Like,
                Order=Order,
                OrderType=OrderType,
                Profile=Profile,
                Role=Role,
                Search=Search,
                Security=Security,
                Social=Social,
                Status=Status,
                Time=Time,
                Trade=Trade,
                User=User,
                connect_for_trading=connect_for_trading,
                update_securities=update_securities)


with app.app_context():
    db.create_all()
    if app.config['FLASK_CONFIG'] == 'development':
        CORS(app)
        database = DatabaseSeeder()
        database.run()
    if app.config['FLASK_CONFIG'] == 'production':
        pass

if __name__ == '__main__':
    socketio_server.run(app, debug=True)
```

**Comment by miguelgrinberg** [comment]
The problem is circular dependencies. You are importing the Socket.IO code before you create `app`. This code then imports run.py, but at the time it does, this file hasn't been completely parsed. If you move the import for the socket.io code down to a place in run.py after app has been created the problem will be avoided. You can also look at lots of guides on how to better structure a Flask app. My Flask Mega-Tutorial includes a chapter on this.
