### ISSUE TITLE
Error handling request: in _get_socket raise KeyError('Session is disconnected')

### ISSUE THREAD

**Issue by jlustk** [miguelgrinberg/python-socketio#302]
Hello! I'm use python-soketio + Flask + gunicorn (eventlet) and I see this error:

    [2019-05-31 09:20:43 +0200] [16820] [ERROR] Error handling request /socket.io/?transport=polling&b64=1&sid=0abbe7ffd3fb4d9c9df4a910d08b139d
    Traceback (most recent call last):
      File "/home/user/new/virt/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 56, in handle
        self.handle_request(listener_name, req, client, addr)
      File "/home/user/new/virt/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/home/user/new/virt/lib/python3.5/site-packages/flask/app.py", line 2328, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/user/new/virt/lib/python3.5/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
      File "/home/user/new/virt/lib/python3.5/site-packages/engineio/middleware.py", line 59, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "/home/user/new/virt/lib/python3.5/site-packages/socketio/server.py", line 487, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "/home/user/new/virt/lib/python3.5/site-packages/engineio/server.py", line 348, in handle_request
        socket = self._get_socket(sid)
      File "/home/user/new/virt/lib/python3.5/site-packages/engineio/server.py", line 536, in _get_socket
        raise KeyError('Session is disconnected')
    KeyError: 'Session is disconnected'

How do I solve this problem?

**Comment by miguelgrinberg** [comment]
Your client was disconnected for some reason, and after that it tried to talk to the server. This could be caused by a client that is misbehaving, or by a server that is too busy and cannot handle the messages from clients in a timely manner. Based on what I've seen, most people have problems with the latter.

**Comment by jlustk** [comment]
Thanks for your reply! Can you tell me what to pay attention to?
This is my gunicorn config:

    bind = '127.0.0.1:8000'
    backlog = 4096
    workers = 1
    worker_class = 'eventlet'
    worker_connections = 4000
    timeout = 30
    keepalive = 2

**Comment by miguelgrinberg** [comment]
This is a problem in the client or server application, it does not have to do with the deployment settings. Do you have any long running or CPU heavy tasks in your server? Anything long running that could block other server tasks?

**Comment by jlustk** [comment]
As for the server application, everything is standard, requests to the database and network requests seem to be nothing heavy for the processor. Thanks, I will try to optimize the server and see what the problem may be on the client
