### ISSUE TITLE
Is it possible to: Get the cookie, retrieve responses that do not have an event name?

### ISSUE THREAD

**Issue by Poussiereuh** [miguelgrinberg/python-socketio#313]
Hello I have two small questions (I searched in the doc and on the internet but I didn't find it)

I use the python socket.io client and I would like to know if **it is possible to retrieve the session cookie**, if so, how?

Another question, **is it possible to get the answer from an .emit without going through an `@sio.event` or `@sio.on()`?** As with the websockets library: 
 
```
websocket.send('Hi')
response = websocket.rcv()
print(response) -> "Hi :)"
```

If not, **is it possible to create an event/on that retrieves messages from the server that do not contain an event name?**

For example I send from the client: `sio.emit("GetNbrPlayers")` but the server answers me `[{"data": "5"}]` without an event before the data (it is a server/api that uses socket.io too), I would like to get this message but impossible with an event/on because there is no event name in the answer.

Thank you in advance!

**Comment by miguelgrinberg** [comment]
> it is possible to retrieve the session cookie,

What do you mean by session cookie? If you mean something like the Flask session cookie, then no, there is no session cookie. The user session is stored in the server, not in a cookie.

If you mean the `sid` cookie that contains the session id assigned to the client, you can obtain this id from the `sid` attribute of your client object, for example as `sio.sid`.

> is it possible to get the answer from an .emit without going through an @sio.event or @sio.on()?

No. The Socket.IO protocol is based on events, if you need to read or write raw packets of information, then I recommend that you use WebSocket directly.

>  is it possible to create an event/on that retrieves messages from the server that do not contain an event name?

Yes, you can use the "ack" feature of the Socket.IO protocol for this. If the server is a Python server, you can just return the response from your handler function. For example:

```python
@sio.event
def GetNbrPlayers():
    return [{"data": "5"}]
```

In the Python client you have two ways to receive this information. You can use a callback function:

```python
def get_response(data):
    print(data)

sio.emit("GetNbrPlayers", callback=get_response)
```

Or you can use `call()` instead of `emit()` to combine the emit and the callback handling into a single function call:

```python
data = sio.call("GetNbrPlayers")
```

**Comment by Poussiereuh** [comment]
Thank you, I got my answers!

I used "callback" but I received no response from the server, I rewrote my program and it seems to work, I do not know why it did not work before ..

I have another question, I would like to ask it here.

I would like, in the same script, to use the client AND the server to do something like this:
![ddd](https://user-images.githubusercontent.com/36985538/61583643-1083bd00-ab3b-11e9-9723-2522f4ceb426.jpg)

I tried with several clients in the same script and it seems to work, but can not run a client and a server in the same script (By putting the server in a thread for example).

Is it possible ? If yes, would you have an example of a simple script that would launch a client and a server?

**Comment by miguelgrinberg** [comment]
I don't have any examples that do both a client and a server, but I don't see why it wouldn't work. I recommend that you leave the server in the main thread. The client can connect on the main thread but does not block it, so you can connect the client, then start the server.

**Comment by Poussiereuh** [comment]
I tried several possible cases and the only way I found to launch a client AND a server is to launch the client in thread mode (without async) and the server like this:

```
import asyncio
import time
import socketio
import threading
import uvicorn


loop = asyncio.get_event_loop()
sio = socketio.Client()
start_timer = None

sio2 = socketio.AsyncServer(async_mode='asgi')
app = socketio.ASGIApp(sio2)


@sio2.event
async def ping_from_client(sid):
    await sio2.emit('pong_from_server', room=sid)
    print("ping vers client")

def send_ping():
    global start_timer
    start_timer = time.time()
    sio.emit('ping_from_client')
    print("ping vers serveur")


@sio.event
def connect():
    print('connected to server')
    send_ping()


@sio.event
def pong_from_server(data):
    global start_timer
    latency = time.time() - start_timer
    print('latency is {0:.2f} ms'.format(latency * 1000))
    sio.sleep(1)
    send_ping()

if __name__ == '__main__':
    sio.connect('http://127.0.0.1:5000')
    uvicorn.run(app, host='127.0.0.1', port=3000)
```

But if I also want to use the asyncio version of the client it does not work because "run_until_complete" blocks the script so something like that is not possible:
```
async def main():
     await sio.connect('http://127.0.0.1:5000')
     await sio.wait()


if __name__ == '__main__':
    loop.run_until_complete(main())
    uvicorn.run(app, host='127.0.0.1', port=3000)
```
(The server will never be launched)

If I run the server inside the loop I get this error:

```
PS C:\Users\Licourne\Documents\backup-21-07-2019\Quidol\serveur-client>py .\test_client_plus_serveur.py
connected to server
ping vers serveur
INFO: Started server process [9448]
INFO: Waiting for application startup.
Traceback (most recent call last):
  File ".\test_client_plus_serveur.py", line 48, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File ".\test_client_plus_serveur.py", line 44, in main
    uvicorn.run(app, host='127.0.0.1', port=3000)
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uvicorn\main.py", line 279, in run
    server.run()
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uvicorn\main.py", line 307, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<LifespanOn.main() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uvicorn\lifespan\on.py:40>>
C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py:509: RuntimeWarning: coroutine 'LifespanOn.main' was never awaited
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<AsyncClient._ping_loop() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py:415> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x04B60710>()]>>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<AsyncClient._write_loop() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py:508> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x04B60950>()]>>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<AsyncClient._read_loop_websocket() running at
C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\asyncio_client.py:467> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0568A390>()]>>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\locks.py:269> cb=[_release_waiter(<Future pendi...x04B60710>()]>)() at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py:316]>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\queues.py:155> cb=[_release_waiter(<Future pendi...x04B60950>()]>)() at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py:316]>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py:674> wait_for=<Future finished result=None> cb=[<TaskWakeupMethWrapper object at 0x0568AAB0>(), _wait.<locals>._on_completion() at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py:380]>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.keepalive_ping() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py:977> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0568AA90>()]>>
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py:1019> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() running at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py:674> wait_for=<Future finished result=None> cb=[<TaskWakeupMethWrapper object at 0x0568AAB0>(), _wait.<locals>._on_completion() at C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py:380]>>
Exception ignored in: <generator object WebSocketCommonProtocol.close_connection at 0x058DD840>
Traceback (most recent call last):
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 1054, in close_connection
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\streams.py", line 312, in close
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 610, in close
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 591, in call_soon
  File "C:\Users\Licourne\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 377, in _check_closed
RuntimeError: Event loop is closed
```

I do not see how I could do to launch an async client and a server

**Comment by miguelgrinberg** [comment]
Okay, I think if you remove the `await sio.wait()` in `main()` you'll be able to use the asyncio client. The `sio.wait()` function should be used when you don't have anything else to do in the main thread. In this case you will be starting the web server, so no need to wait!
