### ISSUE TITLE
Sanic + ASGI Compatiblity

### ISSUE THREAD

**Issue by sjquant** [miguelgrinberg/python-socketio#349]
Now, sanic can be deployed using asgi (uvicorn, hypercone). 
I made it work when sanic run, but got error like below when using uvicorn.

```
[2019-09-09 14:06:16 +0900] [1110] [ERROR] Invalid response object for url http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=MqKQbW9, Expected Type: HTTPResponse, Actual Type: <class 'sanic.response.HTTPResponse'>
ERROR: Invalid response object for url http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=MqKQbW9, Expected Type: HTTPResponse, Actual Type: <class 'sanic.response.HTTPResponse'>
[2019-09-09 14:06:16 +0900] [1110] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=MqKQbW9'
Traceback (most recent call last):
  File "/home/sjquant/.pyenv/versions/3.7.3/envs/square-price/lib/python3.7/site-packages/sanic/asgi.py", line 297, in stream_callback
    response.headers.items(),
  File "/home/sjquant/.pyenv/versions/3.7.3/envs/square-price/lib/python3.7/site-packages/sanic/asgi.py", line 294, in <dictcomp>
    for _, v in list(
AttributeError: 'str' object has no attribute 'key'
```

Is there any way to make it work?

this is my code (create_app part)

```python
import socketio
from sanic import Sanic
from sanic_cors import CORS
from app.utils import get_config_object



sio = socketio.AsyncServer(
    async_mode="sanic", cors_allowed_origins=[]
)


def create_app():
    """
    Create Sanic Application
    """
    # Sanic
    app = Sanic()
    config = get_config_object()
    app.config.from_object(config)

    # Sanic-Cors
    CORS(app, origins=app.config.get("ORIGINS", "*"))

    # Routers
    from app import routers
    routers.init_app(app)

    # Python-Socketio
    sio.attach(app)
    return app
```

**Comment by sjquant** [comment]
Oh, I solved it as follows.
```python
import socketio
from sanic import Sanic
from sanic_cors import CORS
from app.utils import get_config_object


sio = socketio.AsyncServer(
    async_mode="asgi", cors_allowed_origins=[]
)


def create_app():
    """
    Create Sanic Application
    """
    # Sanic
    app = Sanic()
    config = get_config_object()
    app.config.from_object(config)

    # Sanic-Cors
    CORS(app, origins=app.config.get("ORIGINS", "*"))

    # Routers
    from app import routers
    routers.init_app(app)

    # Python-Socketio
    socket_app = socketio.ASGIApp(sio, app)
    return app, socket_app
```
