### ISSUE TITLE
 Handshake status 502 Bad Gateway

### ISSUE THREAD

**Issue by CarloSandoval** [miguelgrinberg/python-socketio#362]
I'm unable to connect to wss to a remote vps using nodejs socket.ioo server with nginx has reverse proxy using https. The python socket.io client code gets a 502 bad gateway when upgradingg to wss. The code works fine with the same server being hosted locally what makes me think that I'm missing extra configuration in the nginx.config file to handle the python client request. note that: socket.io over https works fine when connection is made from browser using javscript socket.io client library, and nginx -t has no errors.

nginx python client access log

 [11/Oct/2019:20:58:37 +0000] "GET /socket.io/?transport=polling&EIO=3&t=1570827517.3917875 HTTP/1.1" 200 99 "-" "python-requests/2.22.0"
 [11/Oct/2019:20:58:38 +0000] "GET /socket.io/?transport=websocket&EIO=3&sid=vWI53ur1nvYwUnC2AAAB&t=1570827518.059794 HTTP/1.1" 502 182 "-" "-"

nginx python client error log
2019/10/11 20:58:38 [error] 12789#12789: *54 connect() failed (111: Connection refused) while connecting to upstream, client: ##.##.##.## server: sandovalcarlos.com, request: "GET /socket.io/?transport=websocket&EIO=3&sid=vWI53ur1nvYwUnC2AAAB&t=1570827518.059794 HTTP/1.1", upstream: "http://127.0.0.1:5000/socket.io/?transport=websocket&EIO=3&sid=vWI53ur1nvYwUnC2AAAB&t=1570827518.059794", host: "www.sandovalcarlos.com"

python client error log

Attempting polling connection to https://www.sandovalcarlos.com/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'H2Bd3V_w-GzpfIBKAAAA', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
Attempting WebSocket upgrade to wss://www.sandovalcarlos.com/socket.io/?transport=websocket&EIO=3
Traceback (most recent call last):
  File "c:/Users/Carlos/OneDrive/python ssl client test/ssl_client.py", line 22, in <module>
    socket.connect('https://www.sandovalcarlos.com/chat')
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\socketio\client.py", line 262, in connect
    engineio_path=socketio_path)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\client.py", line 170, in connect
    url, headers, engineio_path)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\client.py", line 308, in _connect_polling     
    if self._connect_websocket(url, headers, engineio_path):
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\engineio\client.py", line 346, in _connect_websocket   
    cookie=cookies)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 514, in create_connection    
    websock.connect(url, **options)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_handshake.py", line 79, in handshake        
    status, resp = _get_resp_headers(sock)
  File "C:\Users\Carlos\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_handshake.py", line 160, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway

here is my nginx config file:

`

 # HTTP — redirect all traffic to HTTPS

 server {
    listen 80;
    listen [::]:80 default_server;
    return 301 https://$host$request_uri;
 }

# HTTPS — proxy all requests to the Node app
server {
    # Enable HTTP/2
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sandovalcarlos.com;
    root /home/serv/index.js;

    # Use the Let’s Encrypt certificates
    ssl_certificate /etc/letsencrypt/live/sandovalcarlos.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sandovalcarlos.com/privkey.pem;

    # Include the SSL configuration from cipherli.st
    include snippets/ssl-params.conf;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_ssl_session_reuse on;                    
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off; 

        #extra settings to support wss

        proxy_pass http://127.0.0.1:5000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

    }

}

`

**Comment by miguelgrinberg** [comment]
The 502 is generated by nginx, so you should look there for the problem. I really don't know if this configuration works. I always configure the socket.io endpoint separately, as you can see in the documentation. I suggest you give that a try.

**Comment by CarloSandoval** [comment]
Thank you so much, after refactoring the upstream code and following the nginx config in the socket.io documentation it works!
