### ISSUE TITLE
What is the proper way to disconnect a client from the server side?

### ISSUE THREAD

**Issue by PaulWasTaken** [miguelgrinberg/python-socketio#366]
Greetings,
I am trying to disconnect a client from the server side. I use `aiohttp` with `socketio`.

I use:
```
class GlobalNamespaceServer(AsyncNamespace):
    # namespace for /
    async def on_disconnect(self, sid: str):
        await self.emit('disconnect', room=sid)

    async def on_connect(self, sid, environ):
        # I need to send event 'accessDenied'
        await self.emit('accessDenied', 'smth', room=sid)
        loop.create_task(self.disconnect(sid))
        return True
```

As far as I know, the problem is here:
```
            ret = await s.handle_get_request(environ)
            if s.closed:
                # websocket connection ended, so we are done (socket has already been deleted by `sio.disconnect()`)
                del self.sockets[sid]
            return ret
```
in `_handle_connect` function.

**Logs**
```
2019-10-23 17:46:33,558 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet OPEN data {'sid': 'e6c6d024dd41435084460bd42ffc93bb', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-23 17:46:33,559 [INFO] socketio.server: emitting event "accessDenied" to e6c6d024dd41435084460bd42ffc93bb [/]
2019-10-23 17:46:33,560 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet MESSAGE data 2["accessDenied",{"data":{"code":"notAuthorized","description":"text"},"headers":{}}]
2019-10-23 17:46:33,561 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet MESSAGE data 0
2019-10-23 17:46:33,561 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Received request to upgrade to websocket
2019-10-23 17:46:33,562 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Upgrade to websocket successful
2019-10-23 17:46:38,564 [INFO] socketio.server: emitting event "disconnect" to e6c6d024dd41435084460bd42ffc93bb [/]
2019-10-23 17:46:38,565 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet MESSAGE data 2["disconnect",null]
2019-10-23 17:46:38,565 [INFO] socketio.server: Disconnecting e6c6d024dd41435084460bd42ffc93bb [/]
2019-10-23 17:46:38,565 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet MESSAGE data 1
2019-10-23 17:46:38,565 [INFO] engineio.server: e6c6d024dd41435084460bd42ffc93bb: Sending packet CLOSE data None
2019-10-23 17:46:38,569 [ERROR] aiohttp.server: Error handling request
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "...lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 109, in impl
    return await handler(request)
  File "...lib/python3.7/site-packages/engineio/asyncio_server.py", line 234, in handle_request
    b64, jsonp_index)
  File "...lib/python3.7/site-packages/engineio/asyncio_server.py", line 388, in _handle_connect
    del self.sockets[sid]
KeyError: 'e6c6d024dd41435084460bd42ffc93bb'
```

Could you please give me advice, what is the proper way?

**Comment by miguelgrinberg** [comment]
Why do you emit a `disconnect` event? If your `on_disconnect()` event handler was invoked, that means that the client was already disconnected. You appear to be triggering a recursive disconnection. The `connect` and `disconnect` event names are reserved, in any case, you should not emit those events.

**Comment by miguelgrinberg** [comment]
Sorry, didn't mean to close, just comment.

**Comment by PaulWasTaken** [comment]
Thanks for a quick response :)
I have removed emitting `disconnect` event, but the problem persists.
```
async def on_disconnect(self, sid: str):
    print('disconnect')
```

***Logs***
```
2019-10-24 18:33:00,648 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Sending packet OPEN data {'sid': 'e9b219a113534894961d0d5bd9bf206c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-24 18:33:00,648 [INFO] socketio.server: emitting event "accessDenied" to e9b219a113534894961d0d5bd9bf206c [/]
2019-10-24 18:33:00,649 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Sending packet MESSAGE data 2["accessDenied",{"data":{"code":"notAuthorized","description":"text"},"headers":{}}]
2019-10-24 18:33:00,649 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Sending packet MESSAGE data 0
2019-10-24 18:33:00,649 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Received request to upgrade to websocket
2019-10-24 18:33:00,649 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Upgrade to websocket successful
2019-10-24 18:33:00,650 [INFO] socketio.server: Disconnecting e9b219a113534894961d0d5bd9bf206c [/]
disconnect
2019-10-24 18:33:00,650 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Sending packet MESSAGE data 1
2019-10-24 18:33:00,650 [INFO] engineio.server: e9b219a113534894961d0d5bd9bf206c: Sending packet CLOSE data None
```

**Comment by miguelgrinberg** [comment]
I missed before that you are calling disconnect also on the connect handler. That needs to go as well. If you want to end the connection, just return `False`.

**Comment by PaulWasTaken** [comment]
I tried to return `False`, but I could not send my custom evet (`accessDenied`).
Also, I tried the following modification:
```
class GlobalNamespaceServer(AsyncNamespace):
    # namespace for /
    async def on_disconnect(self, sid: str):
        print('disconnected')

    async def on_connect(self, sid, environ):
        loop.create_task(self._gracefull(sid))
        return True

    async def _graceful(self, sid):
        # just in case there is no time to send packets required by the protocol
        await asyncio.sleep(5)
        await self.diconnect(sid)
```
Unfortunately, I still got an error.
Maybe, we should check that there is a record in `self.sockets`?

**Comment by PaulWasTaken** [comment]
Well, another example:
```
class GlobalNamespaceServer(AsyncNamespace):
    # namespace for /
    async def on_disconnect(self, sid: str):
        print('disconnected')

    async def on_connect(self, sid, environ):
        return True

    async def on_makeDis(self, sid):
        await self.diconnect(sid)
```
I've got the same error after sending `makeDis` to the server.

**Comment by miguelgrinberg** [comment]
@PaulWasTaken can you share either the client that you are using with this last example, or the full stack trace of the error (or both)?

**Comment by PaulWasTaken** [comment]
```
export const socketTransport = {
  connect(): void {
    if (connection) {
      throw new Error('Already connected');
    }

    connection = io('http://localhost:8080/', { path: URL, transports: ['websocket'] });
    patcher(connection);

    connection.on('*', busHandler);
    this.on('disconnect').subscribe((): void => {
      console.log('disconnected');
    });
  },

  disconnect(): void {
    if (connection) {
      connection
        .disconnect()
        .off('*', busHandler);

      connection = null;
      unsubscribe$.next();
    }
  },

  on<T>(...events: Array<string>): Observable<T> {
    return bus$.pipe(
      takeUntil(unsubscribe$),
      filter((event: TSocketEvent<T>): boolean => events.includes(event.name)),
      map((event: TSocketEvent<T>): T => event.data)
    );
  },

  sendRequest<U, T>(event: string, data: U, headers: {} = {}): Promise<T> {
    return new Promise<T>((
      resolve: (value: T) => void,
      reject: (reason: TResponseError) => void
    ): void => {
      if (!connection) {
        console.log('no conn')
        reject({ code: '?', description: '?' });
      } else {
        const body = {
          data,
          headers: {
            ...headers,
            token: getToken(),
          },
        };

        connection.emit(event, body, (response: TResponse<T>): void => {
          if (response.status !== ResponseStatus.ok) {
            reject(response.error);
          } else {
            resolve(response.data);
          }
        });
      }
    });
  },
};
```

Stack trace is the same.

**Comment by miguelgrinberg** [comment]
@PaulWasTaken the stack trace cannot be the same, I disagree. The KeyError might be the same, but it has to be triggered from a different place, so it would be useful to see that stack trace if you have it at hand.

**Comment by PaulWasTaken** [comment]
***Logs**
```
2019-10-25 19:28:04,767 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Sending packet OPEN data {'sid': 'c1d48dfb459042958465f499885ae7f2', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-25 19:28:04,767 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Sending packet MESSAGE data 0
2019-10-25 19:28:04,767 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Received request to upgrade to websocket
2019-10-25 19:28:04,768 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Upgrade to websocket successful
2019-10-25 19:28:09,677 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Received packet MESSAGE data 20["makeDis",{"data":"a","headers":{"token":"123"}}]
2019-10-25 19:28:09,678 [INFO] socketio.server: received event "makeDis" from c1d48dfb459042958465f499885ae7f2 [/]
2019-10-25 19:28:09,678 [INFO] socketio.server: Disconnecting c1d48dfb459042958465f499885ae7f2 [/]
2019-10-25 19:28:09,678 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Sending packet MESSAGE data 1
2019-10-25 19:28:09,678 [INFO] engineio.server: c1d48dfb459042958465f499885ae7f2: Sending packet CLOSE data None
2019-10-25 19:28:09,679 [WARNING] engineio.server: Cannot send to sid c1d48dfb459042958465f499885ae7f2
2019-10-25 19:23:49,803 [ERROR] aiohttp.server: Error handling request
Traceback (most recent call last):
  File "...lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "...lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 109, in impl
    return await handler(request)
  File "..lib/python3.7/site-packages/engineio/asyncio_server.py", line 233, in handle_request
    b64, jsonp_index)
  File "...lib/python3.7/site-packages/engineio/asyncio_server.py", line 387, in _handle_connect
    del self.sockets[sid]
KeyError: '817aaae97f32429ea1e9aeab27d9b5a7'
```

**Comment by miguelgrinberg** [comment]
First of all, your client code does not show when you emit the `makeDis` event.

But in any case, you seem to have missed that the key that is missing is not the one from the disconnected client. The client on which you called `makeDis` is `c1d48dfb459042958465f499885ae7f2`. The client that errored is `817aaae97f32429ea1e9aeab27d9b5a7`. So you seem to have another client that is using the old code still running there.

**Comment by PaulWasTaken** [comment]
Wow, I can not imagine, why `sid`'s are different. I have rerun my code and here is the new logs:

```
2019-10-28 11:21:25,909 [INFO] engineio.server: 2f9681847f064179b052754444590139: Sending packet OPEN data {'sid': '2f9681847f064179b052754444590139', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-28 11:21:25,910 [INFO] engineio.server: 2f9681847f064179b052754444590139: Sending packet MESSAGE data 0
2019-10-28 11:21:25,910 [INFO] engineio.server: 2f9681847f064179b052754444590139: Received request to upgrade to websocket
2019-10-28 11:21:25,910 [INFO] engineio.server: 2f9681847f064179b052754444590139: Upgrade to websocket successful
2019-10-28 11:21:42,596 [INFO] engineio.server: 2f9681847f064179b052754444590139: Received packet MESSAGE data 20["makeDis",{"data":{},"headers":{"token":"123"}}]
2019-10-28 11:21:42,597 [INFO] socketio.server: received event "makeDis" from 2f9681847f064179b052754444590139 [/]
2019-10-28 11:21:42,598 [INFO] socketio.server: Disconnecting 2f9681847f064179b052754444590139 [/]
2019-10-28 11:21:42,599 [INFO] engineio.server: 2f9681847f064179b052754444590139: Sending packet MESSAGE data 1
2019-10-28 11:21:42,600 [INFO] engineio.server: 2f9681847f064179b052754444590139: Sending packet CLOSE data None
2019-10-28 11:21:42,601 [WARNING] engineio.server: Cannot send to sid 2f9681847f064179b052754444590139
2019-10-28 11:21:42,609 [ERROR] aiohttp.server: Error handling request
Traceback (most recent call last):
  File "...lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "...lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "...lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 109, in impl
    return await handler(request)
  File "...lib/python3.7/site-packages/engineio/asyncio_server.py", line 233, in handle_request
    b64, jsonp_index)
  File "...bennu-api/lib/python3.7/site-packages/engineio/asyncio_server.py", line 387, in _handle_connect
    del self.sockets[sid]
KeyError: '2f9681847f064179b052754444590139'
```

I send `makeDis` using `form`:

```
export function TestSocketPageComponent(): JSX.Element {
  const [name, setName] = useState('');
  const [data, setData] = useState('');
  const [answer, setAnswer] = useState('');

  function handleClick(): void {
    try {
      if (!name) {
        return;
      }

      const dataRich = data || '{}';
      const dataJSON = JSON.parse(dataRich);

      socketTransport.sendRequest(name, dataJSON).then(value => {
        setAnswer(JSON.stringify(value));
      }).catch((value => {
        setAnswer(JSON.stringify(value));
      }));

      setName('');
      setData('');
    } catch (error) {
      console.log(error);
    }
  }

  function handleNameChange(event: React.ChangeEvent<HTMLInputElement>): void {
    const value = event.currentTarget.value;

    setName(value.trim());
    setAnswer('');
  }

  function handleDataChange(event: React.ChangeEvent<HTMLInputElement>): void {
    const value = event.currentTarget.value;

    setData(value.trim());
    setAnswer('');
  }

  return (
    <div className="test-socket">
      <TextFieldComponent
        onChange={handleNameChange}
        placeholder="Event name"
        value={name}
      />
      <TextAreaFieldComponent
        onChange={handleDataChange}
        placeholder="JSON"
        value={data}
      />
      <div style={{ marginTop: '25px' }}>
        <ButtonComponent onClick={handleClick}>
        </ButtonComponent>
      </div>
      <div style={{ marginTop: '25px' }}>{answer}</div>
    </div>
  );
}
```

**Comment by miguelgrinberg** [comment]
I'm sorry but where in this client code do you emit `makeDis`?

The logs that you are showing indicate that you haven't changed your client, the `makeDis` event appears to be emitted from the connect handler, which is how all this started.

**Comment by PaulWasTaken** [comment]
Client:
```
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.slim.js">
        </script>
    </head>
    <body>
        <button onclick="handleClick()">Press me</button>
        <script>
            function handleClick() {
		    var connection = io('http://localhost:8081/', { path: '/internal/ws', transports: ['websocket'] });
		    const timeout = 5000;
		    setTimeout(() => {
		      if (connection && connection.connected) {
			connection.emit('makeDis', {});
		      }
		    }, timeout);
            }
        </script>
    </body>
</html>
```

I think you should take a look at the logs I got without sending `makeDis`. `GET` request after `disconnect`?

```
2019-10-28 14:28:13,430 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet OPEN data {'sid': 'd86908b6c2954a48871660c69e42850d', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet MESSAGE data 0
2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received request to upgrade to websocket
2019-10-28 14:28:13,432 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Upgrade to websocket successful
2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
2019-10-28 14:29:03,445 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
2019-10-28 14:29:03,446 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
2019-10-28 14:29:20,731 [INFO] application.handlers.ws.base_event_handler: User with sid: d86908b6c2954a48871660c69e42850d has been disconnected.
2019-10-28 14:29:20,732 [INFO] aiohttp.access: 127.0.0.1 [28/Oct/2019:09:28:13 +0000] "GET /internal/ws/?EIO=3&transport=websocket HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
<WebSocketResponse Switching Protocols GET /internal/ws/ > (I put print at `asyncio_server.py`#383
```

Server side is:

```
class GlobalNamespaceServer(AsyncNamespace):
    # namespace for /
    async def on_disconnect(self, sid: str):
        self._logger.info('User with sid: %s has been disconnected.', sid)

    async def on_connect(self, sid, environ):
        return True

    async def on_makeDis(self, sid):
        await self.disconnect(sid)
```

It is important to me to be able to disconnect a user after an event was triggered. I can not do it without the exception now.

**Comment by miguelgrinberg** [comment]
The log shows requests when they end. If you disconnect a user that is connected with WebSocket, then it is expected that you will see the WebSocket request after the disconnect is issued. You called it a GET request, but look closely, that is the WebSocket upgrade request, and as I said, it is logged at the end, not at the start.

At this point I'm confused. The log that you are showing me as not working is doing exactly what you want.

**Comment by PaulWasTaken** [comment]
No, this log is without `makeDis`. I just decided to check it out.
When I added
```
		    const timeout = 5000;
		    setTimeout(() => {
		      if (connection && connection.connected) {
			connection.emit('makeDis', {});
		      }
		    }, timeout);
```
I got the same exception.

**Comment by PaulWasTaken** [comment]
Here is updated example for the server.
```
from aiohttp import web
from socketio import AsyncServer


def create_app() -> web.Application:
    app: web.Application = web.Application(
        middlewares=(
            web.normalize_path_middleware(remove_slash=True, append_slash=False),
        ),
    )

    ws_app: AsyncServer = AsyncServer(
        async_mode='aiohttp',
        cors_allowed_origins=[],
        allow_upgrades=True,
    )
    ws_app.attach(app, socketio_path='/internal/ws')

    @ws_app.event
    async def connect(sid, environ):
        print('connect ', sid)

    @ws_app.event
    async def makeDis(sid, data):
        await ws_app.disconnect(sid)

    @ws_app.event
    async def disconnect(sid):
        print('disconnect ', sid)

    return app


if __name__ == '__main__':
    app: web.Application = create_app()

    web.run_app(app, host='localhost', port=8081)
```

**Comment by PaulWasTaken** [comment]
There is an interesting thing! I tried the client from the example and I got a similar error.

***Client***
```
from time import sleep

import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')


@sio.event
def disconnect():
    print('disconnected from server')


sio.connect('http://localhost:8081', socketio_path='/internal/ws')
sleep(5) # Communicating with server
sio.emit('makeDis', 'some_data')
```

***Logs***

```
connect  bacf49d9763d4dc9a5992e111d8c1c94
disconnect  bacf49d9763d4dc9a5992e111d8c1c94
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at ...lib/python3.7/site-packages/socketio/asyncio_server.py:437> exception=KeyError('bacf49d9763d4dc9a5992e111d8c1c94')>
Traceback (most recent call last):
  File "...lib/python3.7/site-packages/socketio/asyncio_server.py", line 438, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "...lib/python3.7/site-packages/socketio/asyncio_server.py", line 466, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "...scratches/scratch.py", line 22, in makeDis
    await ws_app.disconnect(sid)
  File "...lib/python3.7/site-packages/socketio/asyncio_server.py", line 316, in disconnect
    await self.eio.disconnect(sid)
  File "...lib/python3.7/site-packages/engineio/asyncio_server.py", line 167, in disconnect
    del self.sockets[sid]
KeyError: 'bacf49d9763d4dc9a5992e111d8c1c94'
```

**Comment by miguelgrinberg** [comment]
No, wait, hold on a second. You showed me some logs in which the `makeDis` event wasn't being triggered. Here is a copy of what you showed:

```
2019-10-28 14:28:13,430 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet OPEN data {'sid': 'd86908b6c2954a48871660c69e42850d', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet MESSAGE data 0
2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received request to upgrade to websocket
2019-10-28 14:28:13,432 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Upgrade to websocket successful
2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
2019-10-28 14:29:03,445 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
2019-10-28 14:29:03,446 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
2019-10-28 14:29:20,731 [INFO] application.handlers.ws.base_event_handler: User with sid: d86908b6c2954a48871660c69e42850d has been disconnected.
2019-10-28 14:29:20,732 [INFO] aiohttp.access: 127.0.0.1 [28/Oct/2019:09:28:13 +0000] "GET /internal/ws/?EIO=3&transport=websocket HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
<WebSocketResponse Switching Protocols GET /internal/ws/ > (I put print at `asyncio_server.py`#383
```

If your goal is to disconnect the user, do you see in these logs that that was achieved? I don't know what you are doing in your application, but the logs are clear, the user got disconnected, and there are no crashes. Who is disconnecting the user here?

**Comment by miguelgrinberg** [comment]
Also your provided server and client code does not cause a crash for me.

Output from the server:

```
(venv) $ python client.py
connection established
disconnected from server
```

Output from the server:

```
(venv) $ python server.py
======== Running on http://localhost:8081 ========
(Press CTRL+C to quit)
connect  821aa13427424e1ba17c0c4d86d6c529
disconnect  821aa13427424e1ba17c0c4d86d6c529
```

**Comment by PaulWasTaken** [comment]
I have just run the code from my messages and I got the error.
I also asked my coworker to run this code and it worked.
The main difference is OS - I am using Ubuntu 19.04, but he is using macOS 10.14.6.
What operating system are you using?

**Comment by PaulWasTaken** [comment]
> No, wait, hold on a second. You showed me some logs in which the `makeDis` event wasn't being triggered. Here is a copy of what you showed:
> 
> ```
> 2019-10-28 14:28:13,430 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet OPEN data {'sid': 'd86908b6c2954a48871660c69e42850d', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
> 2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet MESSAGE data 0
> 2019-10-28 14:28:13,431 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received request to upgrade to websocket
> 2019-10-28 14:28:13,432 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Upgrade to websocket successful
> 2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
> 2019-10-28 14:28:38,441 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
> 2019-10-28 14:29:03,445 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Received packet PING data None
> 2019-10-28 14:29:03,446 [INFO] engineio.server: d86908b6c2954a48871660c69e42850d: Sending packet PONG data None
> 2019-10-28 14:29:20,731 [INFO] application.handlers.ws.base_event_handler: User with sid: d86908b6c2954a48871660c69e42850d has been disconnected.
> 2019-10-28 14:29:20,732 [INFO] aiohttp.access: 127.0.0.1 [28/Oct/2019:09:28:13 +0000] "GET /internal/ws/?EIO=3&transport=websocket HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
> <WebSocketResponse Switching Protocols GET /internal/ws/ > (I put print at `asyncio_server.py`#383
> ```
> 
> If your goal is to disconnect the user, do you see in these logs that that was achieved? I don't know what you are doing in your application, but the logs are clear, the user got disconnected, and there are no crashes. Who is disconnecting the user here?

I just closed my browser)
My goal is to be able to disconnect a user during any event.

**Comment by CtrlC-Root** [comment]
I just ran into this issue myself. I'll put together a minimal complete example to reproduce it. I have tried several things so far and have yet to find a way to cleanly disconnect a client without hitting this exception.

**Comment by miguelgrinberg** [comment]
The example application in this repository has a disconnect button that you can click in the browser to trigger the disconnection of the client. Do you get an exception when you use that?

**Comment by dominikWin** [comment]
I tested the aiohttp example from this repo and it still had this exception

**Comment by dskorykh** [comment]
Hello! I have the same problem but with socketio.Server (using eventlet as async_mode). I found this happening after upgrading python-socketio to v4.3.1 and I get an error what occurs when I call disconnect from the server side, it's not persistent (exception is raised approx one time out of ten). It can be related to doing some stuff in the disconnect handler (cleaning hooks bound to client take a little time), but earlier I didn't see this behavior. 

I saw this PR https://github.com/miguelgrinberg/python-engineio/pull/146, and what do you think about adding the same logic to the engineio/server.py?

Error trace:

```
127.0.0.1 - - [13/Nov/2019 20:05:43] "POST /socket.io/?EIO=3&transport=polling&t=Mvbkc3Z&sid=6152cec661024233ad1108683dfea2ab HTTP/1.1" 200 219 0.000988
127.0.0.1 - - [13/Nov/2019 20:05:43] "GET /socket.io/?EIO=3&transport=polling&t=Mvbkc3a&sid=6152cec661024233ad1108683dfea2ab HTTP/1.1" 200 183 0.054349
reboot called
disconnect hooks
disconnect hooks ended
127.0.0.1 - - [13/Nov/2019 20:05:44] "GET /socket.io/?EIO=3&transport=websocket&sid=6152cec661024233ad1108683dfea2ab HTTP/1.1" 200 0 0.789681
Exception in thread Thread-26:
Traceback (most recent call last):
  File "../lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "../lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../lib/python2.7/dist-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "../lib/python2.7/dist-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "../lib/python2.7/dist-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "../lib/python2.7/dist-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "/home/dmitry/projects/Flask-SocketIO/test_disconnect/app_test.py", line 37, in reboot
    disconnect()
  File "../lib/python2.7/dist-packages/flask_socketio/__init__.py", line 922, in disconnect
    return socketio.server.disconnect(sid, namespace=namespace)
  File "../lib/python2.7/dist-packages/socketio/server.py", line 508, in disconnect
    self.eio.disconnect(sid)
  File "../lib/python2.7/dist-packages/engineio/server.py", line 292, in disconnect
    del self.sockets[sid]
KeyError: '6152cec661024233ad1108683dfea2ab'

```

Simplified server-side code

```python
#!/usr/bin/env python
import eventlet
eventlet.monkey_patch()

from flask import Flask, render_template
from flask_socketio import SocketIO, disconnect


async_mode = 'eventlet'

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)


def do_some_stuff(): # if there is a some cpu-bound hook, chance of failure increases (just to reproduce)
    a = 0
    for i in range(10000000):
        a += i


@app.route('/')
def index():
    return render_template('index.html', async_mode=socketio.async_mode)


@socketio.on('disconnect')
def disconnect_handler():
    print("run disconnect hooks")
    do_some_stuff()
    print("disconnect hooks done")


@socketio.on('reboot')
def reboot():
    print("reboot called")
    disconnect()
    # reboot 


if __name__ == '__main__':
    socketio.run(app, host="0.0.0.0", port=2000, debug=True)

```

**Comment by miguelgrinberg** [comment]
It appears this issue is the same as the one reported in miguelgrinberg/python-engineio#179, which is now fixed.
