### ISSUE TITLE
Socket io client receives "connection closed by server" message

### ISSUE THREAD

**Issue by manju1981** [miguelgrinberg/python-socketio#4]
I am trying to upload a file from socket-io-client to python server using websocket. I am able to upload file sometimes successfully but most of the time i receive above error message.

I am sharing client and server code.

Can you please help  me out to figure this issue?. I had turned on logger=True, engineio_logger=True but could not get information why client connection was disconnected.

Client code:

```
constructor () {
  super();
  //this.socket = new SocketIO('54.186.174.180:8082', {forceWebsockets:true});
  /*, "reconnects": false,
  "reconnectAttempts": 0 */
  this.socket = new SocketIO('127.0.0.1:5000', {forceWebsockets:true});
  this.state = { avatarSource :'http://iphonewallpapers-hd.com/thumbs/firework_iphone_wallpaper_5-t2.jpg' };
}

componentDidMount () {
  console.log("mount");
  this.socket.on('connect', () => {
    console.log("connected");
    this.setState({
      status: 'Connected'
    });
  });

  this.socket.on('error', (error) => {
    console.log('error')
    console.log(error);
    this.setState({
      status: 'error'
    });
  });

  this.socket.on('responseevent', (responseevent) => {
    console.log(responseevent);
  });

  console.log("connect");
  this.socket.connect();
}

onLoadPress() {
      PhotoLibrary.readPhoto(
          (results) => {
              console.log(results)
              this.setState({avatarSource:results.imageUrl});

             RNFS.readFile(results.imageUrl).then((contents) => {
               this.socket.emit('userimage', {
                 imageData: contents
               });
              })
              .catch((err) => {
                console.log("error reading file");
                console.log(err.message, err.code);
              });
          },
          (results) => {
              alert('callback2' );
          }
      );
}
```

Python server code.

```
import socketio
import eventlet
from flask import Flask
from flask_socketio import emit


sio = socketio.Server(logger=False, engineio_logger=False)
app = Flask(__name__)



@sio.on('connect')
def test_connect(arg1, arg2):
    print('Client connected')
    sio.emit('message', {'data': 'Connected'})

@sio.on('error')
def test_connect(arg1, arg2):
    print('error')
#    sio.emit('message', {'data': 'Connected'})

@sio.on('userimage')
def testuserimage(arg1, arg2):
    print('userimage')

@sio.on('randomEvent')
def testemit(arg1, arg2):
    print(arg2)
    sio.emit('responseevent', {'hi':'manju'})

@sio.on('disconnect')
def test_disconnect(arg):
    print('Client disconnected')

if __name__ == '__main__':
    # wrap Flask application with engineio's middleware
    app = socketio.Middleware(sio, app)

    # deploy as an eventlet WSGI server
    eventlet.wsgi.server(eventlet.listen(('127.0.0.1', 5000)), app)    
```

In python console i receive this message after a while
Traceback (most recent call last):
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/eventlet/wsgi.py", line 483, in handle_one_response
    write(b''.join(towrite))
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 338, in writelines
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/eventlet/greenio/base.py", line 376, in sendall
    tail = self.send(data, flags)
  File "/Users/manjurn/virtualEnv/sandalmatching/lib/python2.7/site-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 32] Broken pipe

Thanks and Regards
Manjunath

**Comment by miguelgrinberg** [comment]
@manju1981 the "Broken Pipe" error indicates that the client closed the connection. I haven't used the OSX client so I can't comment on what situation would cause this, but when you have a web browser client, this error happens when the tab that has the client application is closed. Receiving this error on the server is expected in that case.

So I think you need to see why the connection is being dropped from your client.

**Comment by miguelgrinberg** [comment]
Closing due to inactivity. Please reopen if this is still an issue.
