### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by andkirby** [miguelgrinberg/python-socketio#405]
I got a strange behavior for the second call of a socket.
Maybe it's some kinda obvious thing, but I don't get it... I just don't see any recursion.
(it's [asgi server from examples](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/asgi/app.py))
Tech stack:
- python-socketio  4.4.0
- selenium 3.141.0
- python 3.6.7
- env: Git Bash in Win 10
```
ERROR:    Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\andki\.python\Python36\lib\site-packages\socketio\asyncio_server.py:440> exception=RecursionError('maximum recursion depth exceeded while calling a Python object',)>
Traceback (most recent call last):
  File "C:\Users\andki\.python\Python36\lib\site-packages\socketio\asyncio_server.py", line 441, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\andki\.python\Python36\lib\site-packages\socketio\asyncio_server.py", line 469, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "D:/home/py-watcher/webin/app.py", line 179, in search
```

### In `app.py`
It breaks on the line `mov.search(message['search'])` in the code below.
Code snippet in my app.py:
```
@sio.on('movies search')
async def movies_search(sid, message):
    global mov
    error = None
    if not mov:
        mov = Movies()
        mov.start()

    if mov:
        mov.search(message['search'])
    else:
        error = 'No opened browser.'

    await sio.emit('my_response', {
        'data': 'movies search for: ' + message['search'],
        'count': 0, 'error': error},
                   room=sid)
```
inside `search()` I use selenium webdriver, but it cannot get into this method.

### in HTML
In app.html:
```
$('form#movies_search').submit(function (event) {
    socket.emit('movies search', {search: $('#movies_search_text').val()});
    return false;
});
```
The rest methods work fine.

So, what am I doing wrong?

**Comment by andkirby** [comment]
Not sure which side has an issue on, but `sys.setrecursionlimit(5000)` (I had `1000`) helped me.
