### ISSUE TITLE
Aiohttp Server: "TypeError: handle_connect() takes 0 positional arguments but 2 were given"

### ISSUE THREAD

**Issue by secretlyvogon** [miguelgrinberg/python-socketio#428]
I am new to asyncio and socketio libraries. I am trying to build a simple network client-server event-based interaction. The server runs fine initially, however, when I run the client, I see the above error on the server-side and on the client side I see the following:

```
Traceback (most recent call last):
  File "new_node.py", line 96, in <module>
    loop.run_until_complete(node.init_client('http://0.0.0.0',8080))
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "new_node.py", line 32, in init_client
    await self.socket.connect("{}:{}".format(server_add, server_port))
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/site-packages/socketio/asyncio_client.py", line 110, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 401 in server response
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5fad884ba8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5fad8856c8>, 700471.632735238)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5fad884c18>
```

It looked like a connection issue to me, so just to see if my client could connect properly I tried running the latency.py given in the examples of the repo as the server and then tried to connect the client. I get no issues there. The way I have initialized my variables of socketio and aiohttp are exactly the same as in the example except that they are class variables in my case. 

Please help me understand the error messages and codes, and help me figure out what I am doing wrong.

**Comment by miguelgrinberg** [comment]
Do you have the stacktrace for the server error?

**Comment by secretlyvogon** [comment]
@miguelgrinberg  Yes sure. This is what the server gives me:

```
connect async handler error
Traceback (most recent call last):
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/site-packages/engineio/asyncio_server.py", line 419, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/site-packages/socketio/asyncio_server.py", line 487, in _handle_eio_connect
    return await self._handle_connect(sid, '/')
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/site-packages/socketio/asyncio_server.py", line 390, in _handle_connect
    self.environ[sid])
  File "/home/saket/anaconda3/envs/fluid-fl/lib/python3.6/site-packages/socketio/asyncio_server.py", line 469, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given
```

**Comment by miguelgrinberg** [comment]
So you have a function called `handle_connect()`, yes? This function should take two arguments, `sid` and `environ`. See [the docs](https://python-socketio.readthedocs.io/en/latest/server.html#defining-event-handlers).

**Comment by secretlyvogon** [comment]
Hi, thanks that fixed the issue. I was confused by the language of the error thrown `handle connect() takes 0 positional arguments but 2 were given` seemed like I was passing extra arguments instead of me missing those arguments in my code.
