### ISSUE TITLE
stopping socketio with Ctrl+C KeyboardInterrupt on sio.wait()

### ISSUE THREAD

**Issue by BRIDGE-AI** [miguelgrinberg/python-socketio#453]
hi, @miguelgrinberg 

I have a socketio client below.
This code has a background task func() that record audio in put and make it as base64 chunks.
And I'm going to make this stopped and exited when I press `CTRL+C` once.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import threading
import pyaudio
import base64
import socketio

def main():
    RATE = 16000
    CHUNK = int(RATE / 10)

    sio = socketio.Client()
    sio.connect('http://localhost:10001')

    @sio.on('asr')
    def asr(data):
        print('asr:%s' % data)

    audio = pyaudio.PyAudio()

    options = {
        "format":pyaudio.paInt16,
        "channels":1,
        "rate":RATE,
        "input":True,
        "frames_per_buffer":CHUNK,
    }

    stream = audio.open(**options)

    def func():
        n = 0

        data = {
            "lang":"ko-KR",
            "rate":RATE,
            "intr":True,
        }

        sio.emit('asr', data)

        while True:
            chunk = stream.read(CHUNK)

            print("chunk[%d]@%d" % (len(chunk), n + 1))

            chunk = base64.b64encode(bytes(chunk)).decode()
            sio.emit('asr', chunk)
            n += 1

    #threading.Thread(target=func).start()
    sio.start_background_task(func)

    try:
        print("waiting..")
        sio.wait()
    except KeyboardInterrupt as error:
        #sio.emit('asr', {"command":"disconnect"})

        sio.disconnect()
        print("sio.connected:%s" % sio.connected)

        stream.stop_stream()
        stream.close()

    print("end")

if __name__ == '__main__':
    llv = logging.DEBUG
    logging.getLogger('requests').setLevel(llv)
    logging.getLogger('websocket').setLevel(llv)
    logging.getLogger('socketIO-client-2').setLevel(llv)
    logging.getLogger('urllib3.connectionpool').setLevel(llv)
    logfmt = "%(name)-8s [%(levelname)-5s] %(message)-120s (%(filename)s:%(lineno)d)"
    #logging.basicConfig(level=logging.DEBUG, format=logfmt)

    main()
```

But this app does not exit when `CTRL+C` once.
I should press `CTRL+C` once more.

And I finally see `original_signal_handler()`.
It seems that socketio thread (or worker) is still working after connection disconnected and closed.

```
waiting..
chunk[3200]@1
chunk[3200]@2
chunk[3200]@3
...
chunk[3200]@23
chunk[3200]@24
asr:{'idx': 1, 'transcript': '안녕하세요', 'is_final': False}
chunk[3200]@25
chunk[3200]@26
chunk[3200]@27
...
chunk[3200]@35
chunk[3200]@36
asr:{'idx': 2, 'transcript': '안녕하세요', 'is_final': True}
chunk[3200]@37
chunk[3200]@38
...
chunk[3200]@44
chunk[3200]@45
^Csio.connected:False
end
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt

Interrupt: Press ENTER or type command to continue
```

Please help me, how can I fix this problem and complete the feature?
always thank you.

**Comment by miguelgrinberg** [comment]
I believe the problem is that you are not doing anything to stop your `func` background task and end it cleanly. This is what forces you to press Ctrl-C a second time. If you had a signal handler, similar to the one in the socketio client then I think you would have a clean exit.
