### ISSUE TITLE
How to: handle remote-unexpected terminate?

### ISSUE THREAD

**Issue by simingy** [miguelgrinberg/python-socketio#471]
1. start a socketio server with `aiohttp`
2. connect to it using a client and keep sending packets
3. if i kill the server with ctrl-c, the client silently crash in the loop without exception handling

how do I detect this?
Here's my debug output. - Note that I had to modify `engineio/asyncio_client.py` to get this error to show up:
on ctrl-c of the server:

client-output:
```
INFO:engineio.client:Sending packet MESSAGE data 2["message",{"time":1588104387.899488}]
CAUGHT EXCEPTION
Traceback (most recent call last):
  File "/Users/siyuan/workspace/wsg/lib/python3.7/site-packages/engineio/asyncio_client.py", line 515, in _read_loop_websocket
    pkt = packet.Packet(encoded_packet=p)
  File "/Users/siyuan/workspace/wsg/lib/python3.7/site-packages/engineio/packet.py", line 30, in __init__
    self.decode(encoded_packet)
  File "/Users/siyuan/workspace/wsg/lib/python3.7/site-packages/engineio/packet.py", line 60, in decode
    encoded_packet = encoded_packet.encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
INFO:engineio.client:Received packet PONG data None
INFO:engineio.client:Unexpected error "WebSocket read returned None", aborting
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:HTTP GET request to http://localhost:8080/socket.io/?transport=polling&EIO=3&t=1588104388.974071 failed with error Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)].
```
... etc but it doesn't stop.

if I called `sio.wait()` it would, though.

```python
#server code
import socketio
from aiohttp import web

sio = socketio.AsyncServer(async_mode = 'aiohttp')

app = web.Application()
sio.attach(app)

redis = None

@sio.event
async def connect(sid, environ):
    print("connected", sid)

@sio.event
async def message(sid, data):
    print(sid, data)

if __name__ == '__main__':
    web.run_app(app)
```

```python 
#client code
  
import asyncio
import socketio
import time
import logging

logging.basicConfig(level=logging.DEBUG)

loop = asyncio.get_event_loop()
sio = socketio.AsyncClient()

async def start_server():
    await sio.connect('http://localhost:8080')
    while True:
        await asyncio.sleep(0.5)
        await sio.send(data={'time': time.time()})

if __name__ == '__main__':
    loop.run_until_complete(start_server())

```

**Comment by miguelgrinberg** [comment]
This issue has been reported already. The fix is in the master branch of the python-engineio project. Could I ask you to install that branch and report back if the problem is addressed? An official release with this fix is coming soon.

**Comment by simingy** [comment]
awesome! the behavior is much different now:
```text
INFO:engineio.client:Sending packet MESSAGE data 2["message",{"time":1588267728.0543308}]
INFO:engineio.client:Unexpected error decoding packet: "'int' object has no attribute 'encode'", aborting
INFO:engineio.client:Waiting for write loop task to end
INFO:engineio.client:Exiting write loop task
INFO:engineio.client:Waiting for ping loop task to end
INFO:engineio.client:Sending packet PING data None
INFO:engineio.client:PONG response has not been received, aborting
INFO:engineio.client:Exiting ping task
INFO:socketio.client:Engine.IO connection dropped
INFO:engineio.client:Exiting read loop task
INFO:socketio.client:Connection failed, new attempt in 1.33 seconds
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:HTTP GET request to http://localhost:8080/socket.io/?transport=polling&EIO=3&t=1588267729.44606 failed with error Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)].
INFO:socketio.client:Connection failed, new attempt in 2.42 seconds
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:HTTP GET request to http://localhost:8080/socket.io/?transport=polling&EIO=3&t=1588267731.875665 failed with error Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)].
INFO:socketio.client:Connection failed, new attempt in 4.33 seconds
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:HTTP GET request to http://localhost:8080/socket.io/?transport=polling&EIO=3&t=1588267736.216767 failed with error Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)].
INFO:socketio.client:Connection failed, new attempt in 4.97 seconds
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:HTTP GET request to http://localhost:8080/socket.io/?transport=polling&EIO=3&t=1588267741.197052 failed with error Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)].
INFO:socketio.client:Connection failed, new attempt in 5.24 seconds
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:socketio.client:Emitting event "message" [/]
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
INFO:engineio.client:Polling connection accepted with {'sid': '7e038e1dde7a410dbe3c966bf4282c00', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
INFO:socketio.client:Engine.IO connection established
INFO:engineio.client:Received packet MESSAGE data 0
INFO:engineio.client:Attempting WebSocket upgrade to ws://localhost:8080/socket.io/?transport=websocket&EIO=3
INFO:socketio.client:Namespace / is connected
connection established
INFO:engineio.client:WebSocket upgrade was successful
INFO:socketio.client:Reconnection successful
INFO:engineio.client:Sending packet PING data None
INFO:engineio.client:Received packet NOOP data None
INFO:engineio.client:Received packet PONG data None
INFO:socketio.client:Emitting event "message" [/]
```

i'm guessing that new behavior is:
- messages that couldn't get sent will be lost (no queuing/save up)
- socketio will indefinitely retry connection?

**Comment by miguelgrinberg** [comment]
> messages that couldn't get sent will be lost (no queuing/save up)

No, if the connection is not up you should not actually send

> socketio will indefinitely retry connection?

See the reconnection options in the [docs](https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Client).

**Comment by simingy** [comment]
got it, can use `sio.connected` option
