### ISSUE TITLE
BrokenPipeError after calling client.disconnect

### ISSUE THREAD

**Issue by MagnusKriel** [miguelgrinberg/python-socketio#474]
I have simple setup where I client connects to a server, sends a few messges and disconnects.
After the disconnect method is called I get a BrokenPipeError exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/engineio/client.py", line 683, in _write_loop
    self.ws.send(encoded_packet)
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 279, in send_frame
    l = self._send(data)
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/websocket/_core.py", line 449, in _send
    return send(self.sock, data)
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/home/magnus/.virtualenvs/python3.6/lib/python3.6/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```
What I think is happening, there are still messages in the queue to be sent( I can see there are several disconnect packets put in the queue) but the transport(s) are closed before queue is emptied. 
The Client class' disconnect method calls `self.eio.disconnect(abort=True)`. When forcing the abort argument to False, I do not get the exception.

I use python 3.6.9 and version 4.5.1 of the socketio library.

**Comment by miguelgrinberg** [comment]
Do you have code that I can use to reproduce this?

**Comment by MagnusKriel** [comment]
Here is a test script that reproduces the error:
```
import socketio


class SocketIoClient(object):

    def __init__(self):
        super(SocketIoClient, self).__init__()
        self._sio = socketio.Client()

    def connect(self, endpoint):
        self._sio.connect(endpoint, transports=['websocket'])

    def close(self):
        self._sio.disconnect()
        self._sio.wait() # Extra belts and braces

    def send(self, data):
        msg = (data, 'abc')
        self._sio.emit('event-stdout', msg)


"""
My application spawns a thread. In the function executed by the thread, a new socketIO client is created,
messages sent (not receiving any as it is fire and forget).
At the end, the socket is closed before function exits and thread exits normally. 
"""
def simulate_thread_run():
    # Do some stuff
    sio = SocketIoClient()
    sio.connect('http://127.0.0.1:5000')
    sio.send("Lorem ipsum dolor sit amet, ius qualisque theophrastus ad, eum oportere persequeris delicatissimi an.")
    # Do some stuff
    sio.send("Lorem ipsum dolor sit amet, ius qualisque theophrastus ad, eum oportere persequeris delicatissimi an.")
    sio.close()

"""
Might need a few runs to trigger exception, but happens more often than not
"""
for x in range(10):
    simulate_thread_run()
```

**Comment by miguelgrinberg** [comment]
So the problem here is that the `send` is asynchronous, you can just close immediately after issuing one. Basically you are pulling the plug while the background threads are still working on sending your message out.

You may want to wait until the send is acknowledged before closing. You can use a callback for this, or maybe even better is to use the `call()` function instead of send or emit. The `call()` combines an emit with waiting for the callback.
