### ISSUE TITLE
Emit larger data

### ISSUE THREAD

**Issue by Gilks** [miguelgrinberg/python-socketio#511]
I am using the eventlet server on python 3.7. My connections are upgraded to web sockets. If I perform the following, I am able to successfully emit between my client/server.

`client.emit('send_to_server', {'filename': 'test.zip', 'data': 'Smaller data here'})`

Now if I attempt to actually use the real binary data for `test.zip` (~250 MB) there is a delay and then I receive the following stack trace:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
  File "/usr/lib64/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OSError: [Errno 9] Bad file descriptor
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
  File "/usr/lib64/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OSError: [Errno 9] Bad file descriptor

```

I did some digging around and tried increasing the `max_http_buffer_size` and disabling `http_compression` on the server side but the same stack trace occurs. On the client side I attempted to set `binary=True` and I also tried base64 encoding the data. Are there any additional steps I should be taking in order to send larger data?

Additional note: I am not monkey patching. I am using this project in conjunction with CMD2. If I monkey patch, it breaks other portions of the project. I'm not sure if this detail matters but I figured I would mention it.

**Comment by miguelgrinberg** [comment]
This could be an issue with either the websocket client or server packages that are dependencies of the Socket.IO client and server respectively. I had a somewhat similar issue in the server a while ago: https://github.com/miguelgrinberg/python-socketio/issues/479. This is probably similar.

If you can send the file in smaller chunks, that's the best solution.

**Comment by Gilks** [comment]
Interesting. Originally I had a loop setup that would open a screenshot, read it and then emit it. In the case a higher volume (~1000 screenshots) it would stack trace. I assumed that performing less connections would be the fix- which lead to the original problem.

Following the original method of sending smaller files (~250 kB each) here is what happens.

Client:
```
...
for i, screenshot in enumerate(screenshots):
     data = open(screenshot, 'rb').read()
     print('Screenshot number: {0}'.format(i))
     client.emit('send_to_server', {'filename': 'photo.jpg', 'data': data})
...
```

Server:

```
...
send_server_screenshot(message):
     print("Receiving")
...
```

Output:

```
Sending 0
Sending 1
...
Sending 43
Receiving
Sending 44
Sending 45
...
Sending 82
Sending 83
Receiving
Sending 84
Sending 85
...
Sending 949
Sending 950
Sending 951
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
  File "/usr/lib64/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OSError: [Errno 9] Bad file descriptor
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
  File "/usr/lib64/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OSError: [Errno 9] Bad file descriptor
```

**Comment by miguelgrinberg** [comment]
Are you implementing SSL in your Python server? If yes, can you see if the problem persists when you remove that? Eventlet has some bugs in the SSL implementation, I wonder if this is another way those problems manifest.

**Comment by Gilks** [comment]
Yes, SSL was in use. I went ahead and disabled SSL and forced the use of HTTP. It appears to produce the same results as its SSL counterpart. 

```
...
Sending 847
Sending 848
Sending 849
Receiving
Sending 850
Sending 851
...
Sending 895
Receiving
Sending 896
Sending 897
...
Sending 918
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 681, in _write_loop
    self.ws.send_binary(encoded_packet)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 284, in send_binary
    return self.send(payload, ABNF.OPCODE_BINARY)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor

Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
Receiving
```

**Comment by miguelgrinberg** [comment]
What is the server sending?

**Comment by Gilks** [comment]
For debugging purposes the client/server are currently on the same host. What is seen above is the full output from both the client and server. After the stack trace from the client side, the server continues to run without a hitch. 

The actual code for the server side is currently setup to just print "Receiving" and then return. I commented out the production code in an attempt to fix this bug.

Does that answer the question?

**Comment by miguelgrinberg** [comment]
The output you show above have a "Sending <n>" log. Is this just a message, or are you sending from server to client as well? You haven't shown me the logic for the server, if it is in fact sending.

**Comment by Gilks** [comment]
The "Sending \<n\>" message is just a print statement on the client side to showcase that an emit occurred (as seen in the [client](https://github.com/miguelgrinberg/python-socketio/issues/511#issuecomment-651143725) code). The server is not sending anything in response to the client. The server code is currently setup to do nothing more than catch the emits, print and then return. It looks exactly like this:

```
@server.on('send_server_screenshot', namespace='/screenshots')
@authenticated_only
send_server_screenshot(message):
     print("Receiving")
     return
```

**Comment by miguelgrinberg** [comment]
What you are saying does not agree with the code fragments you are showing me. You have server logs that include "Sending N" and "Receiving" prints. The only print I see in your client code is "Screenshot number N", which I'm not asking about.

Besides, how can the "Sending N" message be in the client if it appears in between other server logs?

**Comment by Gilks** [comment]
You are correct. I see the root of the confusion now. When I wrote that pseudo code I mistakenly put "Screenshot number: {0}" instead of the original "Sending {0}". I should have double checked it all matched up before posting it originally.

The reason why the client and server logs are mixed is because the server and client are running in two different threads on the same localhost. I am able to start the client/server from within my framework. For clarity, I am starting a teamserver and then joining it as a client.

Here's the client code unchanged from the source:

```
...
for i, screen in enumerate(screenshots):
	hostname = screen.split('/')[-2]
	filename = screen.split('/')[-1]
	existing_screen = os.path.join(Paths.screenshots, screen)

	with open(existing_screen, 'rb') as screenshot:
		data = screenshot.read()
		print("Sending {0}".format(i))
		client.emit('send_server_screenshot', {'name': filename, 'path': hostname, 'data': data}, namespace='/screenshots')
...
```

Now the actual eventlet logs look like this. Here is the server starting:

```
[+] Teamserver starting: https://0.0.0.0:80
[*] Joining..
(629664) wsgi starting up on https://0.0.0.0:80
(629664) accepted ('10.0.0.32', 56918)
10.0.0.32 - - [30/Jun/2020 18:56:13] "GET / HTTP/1.1" 200 161 0.002012
(629664) accepted ('10.0.0.32', 56920)
10.0.0.32 - - [30/Jun/2020 18:56:13] "POST /login HTTP/1.1" 200 418 0.007955
(629664) accepted ('10.0.0.32', 56922)
10.0.0.32 - - [30/Jun/2020 18:56:13] "GET /socket.io/?transport=polling&EIO=3&t=1593557773.5484352 HTTP/1.1" 200 423 0.004513
(629664) accepted ('10.0.0.32', 56924)
[+] The teamserver has connected as a client
```

Here are the logs for the connecting client:

```
[*] Connecting to the teamserver..
(629664) accepted ('127.0.0.1', 45118)
127.0.0.1 - - [30/Jun/2020 18:56:21] "POST /login HTTP/1.1" 200 420 0.006253
(629664) accepted ('127.0.0.1', 45120)
127.0.0.1 - - [30/Jun/2020 18:56:21] "GET /socket.io/?transport=polling&EIO=3&t=1593557781.0443408 HTTP/1.1" 200 349 0.002099
[+] Gilks (127.0.0.1) has connected to the teamserver
(629664) accepted ('127.0.0.1', 45122)
[+] Gilks has connected to the teamserver
Sending 1
Sending 2
Sending 3
...
```
