### ISSUE TITLE
Bug when try to reconnect from another event loop

### ISSUE THREAD

**Issue by PhpEssential** [miguelgrinberg/python-socketio#514]
Hi,

I have some trouble with the async client.

```
[32mINFO[0m:     Engine.IO connection dropped
Websocket disconnected
[32mINFO[0m:\t Exiting read loop task
[32mINFO[0m:\t Connection failed, new attempt in 0.98 seconds
Exception in thread Thread-1:
Traceback (most recent call last):
[32mINFO[0m:     Exiting read loop task
[32mINFO[0m:     Connection failed, new attempt in 0.98 seconds
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Anaconda3\envs\myProject\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "F:\Anaconda3\envs\myProject\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "application\main.py", line 62, in websocket_connection
    client_loop.run_until_complete(launch_websocket(dispatcher))
  File "F:\Anaconda3\envs\myProject\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "application\main.py", line 83, in launch_websocket
    await dispatcher.wait()
  File "application\..\application\core\socketio\client_socketio.py", line 34, in wait
    await self._client.wait()
  File "F:\Anaconda3\envs\myProject\lib\site-packages\socketio\asyncio_client.py", line 132, in wait
    await self._reconnect_task
  File "F:\Anaconda3\envs\myProject\lib\site-packages\socketio\asyncio_client.py", line 417, in _handle_reconnect
    await asyncio.wait_for(self._reconnect_abort.wait(), delay)
  File "F:\Anaconda3\envs\myProject\lib\asyncio\tasks.py", line 412, in wait_for
    return fut.result()
  File "F:\Anaconda3\envs\myProject\lib\asyncio\locks.py", line 293, in wait
    await fut
RuntimeError: Task <Task pending coro=<Event.wait() running at F:\Anaconda3\envs\myProject\lib\asyncio\locks.py:293> cb=[_release_waiter(<Future pendi...CCA173EE8>()]>)() at F:\Anaconda3\envs\myProject\lib\asyncio\tasks.py:362]> got Future <Future pending> attached to a different loop


# I have my client loop define like that:

client_loop = asyncio.new_event_loop()

#And I launch the client like that:

def websocket_connection(dispatcher): 
    client_loop.run_until_complete(launch_websocket(dispatcher))

async def launch_websocket(dispatcher):
    await dispatcher.connect(url)
    await dispatcher.wait()

# Start Websocket client thread
ws_client = socketio.AsyncClient()
    
t = Thread(target=websocket_connection, args=(ws_client,))
t.start()
```

I think to handle multi-threading you need to allow developpers to pass the loop argument when you use asyncio in socketio and engineio.

In my case I have simultanously client and server in same program, and it's the await dispatcher.wait() which is problematic, I think this bug can be resolve by passing the client_loop to File "F:\Anaconda3\envs\myProject\lib\site-packages\socketio\asyncio_client.py", line 417, in _handle_reconnect
    await asyncio.wait_for(self._reconnect_abort.wait(), delay /** loop=client_loop **/)

**Comment by miguelgrinberg** [comment]
Have you set the loop to yours before instantiating the client? Right now there is no `loop` argument, I may add it in the future.

**Comment by PhpEssential** [comment]
it'is the same for me

`def websocket_connection(dispatcher): 
    asyncio.set_event_loop(client_loop)
    asyncio.get_event_loop().run_until_complete(launch_websocket(dispatcher))`

**Comment by PhpEssential** [comment]
The first try seems to work

**Comment by PhpEssential** [comment]
I got a quick fix but it's not a very clean solution

```
async def launch_websocket(dispatcher):
    loop = True
    while loop:
        try:
            await dispatcher.connect(url)  
            await dispatcher.wait()
        except socketio.exceptions.ConnectionError as e:
            print("Cloud websocket unreachable")
            await dispatcher.sleep(2)
        except Exception as e:   
            if 'got Future <Future pending> attached to a different loop' not in str(e):
                loop = False
                print("Unknow error from cloud websocket")
            else:
                print("Cloud websocket `disconnection")
```

**Comment by miguelgrinberg** [comment]
You are not showing me all the code, but my suggestion is that you set the loop before you instantiate your Socket.IO client.

**Comment by PhpEssential** [comment]
My bad, sorry, I understand connection instead of `instanciation.

```
def websocket_connection(): 
    asyncio.set_event_loop(client_loop)
    ws_client = socketio.AsyncClient()
    client_loop.run_until_complete(launch_websocket(ws_client))

async def launch_websocket(dispatcher):
    loop = True
    while loop:
        try:
            await dispatcher.connect(url)  
            await dispatcher.wait()
        except socketio.exceptions.ConnectionError as e:
            print("Cloud websocket unreachable")
            await dispatcher.sleep(2)
        except Exception as e:   
            loop = False
            print("Unknow error from cloud websocket")
```

Thanks for your fast reply and your good solution
