### ISSUE TITLE
Stand alone emit in thread

### ISSUE THREAD

**Issue by AthanatiusC** [miguelgrinberg/python-socketio#526]
Hello, sorry to bother but i have some trouble figuring out how can i achieve this:

```
def handlesocket(self):
        @self.socketio.on('connect')
        def connected():
            print("User {} connected".format(request.sid))
            emit("message","Connected to recognition")
            self.clients.append(request.sid)

        @self.socketio.on('disconnect')
        def disconnect():
            print("{} Disconnected".format(request.sid))
            emit("message","Disconnected from recognition")
            self.clients.remove(request.sid)

        def test():
            while request.sid in self.clients:
                if self.datas.not_empty:
                    self.socketio.emit("result", self.datas.get(),namespace="")

        @self.socketio.on("result")
        def send():
            t = Thread(target=test)
            t.daemon = True
            t.start()
```

> so i wanted to run the test() function in background because if its not, its gonna hold down the entire program. i tried doing it like this but i got the usual error:

```
`Exception` in thread Thread-16:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\xampp\htdocs\nuxt\smartschool_api\demo\library.py", line 110, in test
    while request.sid in self.clients:
  File "C:\Python35\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Python35\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\Python35\lib\site-packages\flask\globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.
```

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

thank you!

here is the full code : 
https://github.com/AthanatiusC/Python-face-recognition-V2/blob/master/library.py#L95

**Comment by miguelgrinberg** [comment]
Pass the `sid` value as an argument to the thread. The thread itself has not request context, so it does not know who the client is.

**Comment by AthanatiusC** [comment]
ah i see! do i need to pass the argument to the emit?

**Comment by AthanatiusC** [comment]
ops. i just realized my mistake, thank you very much!
