### ISSUE TITLE
Error when using sio.connect() with given example

### ISSUE THREAD

**Issue by ehermellin** [miguelgrinberg/python-socketio#552]
Hi, 

I want that a socket.io server running in nodejs can receive message from client like python client, js client, etc. 
So I chose to use python-socketio for the python part.

I started by trying to run the two examples (server and client) that are on the website : https://python-socketio.readthedocs.io/en/latest/

After installing the last version of python-socketio with pip, I have this error when launching client.py (server.py is already running):

```
>python client.py
Traceback (most recent call last):
  File "client.py", line 18, in <module>
    sio.connect('http://localhost:3000')
  File "C:\ProgramData\Anaconda3\lib\site-packages\socketio\client.py", line 276
, in connect
    self.eio.connect(url, headers=headers, transports=transports,
  File "C:\ProgramData\Anaconda3\lib\site-packages\engineio\client.py", line 187
, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "C:\ProgramData\Anaconda3\lib\site-packages\engineio\client.py", line 299
, in _connect_polling
    r.status_code), r.json())
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 898
, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Does somebody can help me with this ?
Thank a lot !

**Comment by miguelgrinberg** [comment]
What examples specifically are you using? None of the examples run on port 3000 like your application. If you have made changes to the examples, then please post the actual code here.

**Comment by ehermellin** [comment]
Thank you for your answer !
I took the two examples from the Getting Started of the python-socketio website.

**Server side**

```
import eventlet
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio, static_files={
    '/': {'content_type': 'text/html', 'filename': 'index.html'}
})

@sio.event
def connect(sid, environ):
    print('connect ', sid)

@sio.event
def my_message(sid, data):
    print('message ', data)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
```

With following output:

`(10088) wsgi starting up on http://0.0.0.0:5000`

**Client side**

```
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')

@sio.event
def my_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://localhost:5000')
sio.wait()
```

With following output:

```
Traceback (most recent call last):
  File "client.py", line 18, in <module>
    sio.connect('http://localhost:5000')
  File "C:\ProgramData\Anaconda3\lib\site-packages\socketio\client.py", line 276
, in connect
    self.eio.connect(url, headers=headers, transports=transports,
  File "C:\ProgramData\Anaconda3\lib\site-packages\engineio\client.py", line 187
, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "C:\ProgramData\Anaconda3\lib\site-packages\engineio\client.py", line 299
, in _connect_polling
    r.status_code), r.json())
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 898
, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I use python 3.7 and latest python-socketio installed with pip.

Thanks for your help !

**Comment by miguelgrinberg** [comment]
I can't reproduced the error here, sorry.

Output from the server:

```
(96164) wsgi starting up on http://0.0.0.0:5000
(96164) accepted ('127.0.0.1', 64054)
connect  f467813e506e42f190ec3c0e7fe1de82
127.0.0.1 - - [07/Oct/2020 09:25:00] "GET /socket.io/?transport=polling&EIO=3&t=1602059100.398935 HTTP/1.1" 200 371 0.000768
(96164) accepted ('127.0.0.1', 64056)
```

Output from the client:

```
connection established
```

**Comment by ehermellin** [comment]
Do you know what can cause this problem?
The version of python? The OS version?

**Comment by miguelgrinberg** [comment]
I don't, but I suggest you try a standard Python3 distribution. I don't know what version of Python Anaconda3 maps to, so I have no idea if that is a supported version or not.

**Comment by ehermellin** [comment]
I have done another test on a Win10 PC with Anaconda 3 and i have the same issue. So i will try with a standard Python3 distribution on linux and see what is happenning !

**Comment by miguelgrinberg** [comment]
Out of curiosity, can you show me the information printed to the terminal when you run the Anaconda Python shell? Just type "python" to start the shell.

**Comment by ehermellin** [comment]
After a fresh install of Python (standard, not using Anaconda), always the same issue.

```
Traceback (most recent call last):
  File "client.py", line 18, in <module>
    sio.connect('http://localhost:5000')
  File "C:\Python\Python38\lib\site-packages\socketio\client.py", line 276, in c
onnect
    self.eio.connect(url, headers=headers, transports=transports,
  File "C:\Python\Python38\lib\site-packages\engineio\client.py", line 187, in c
onnect
    return getattr(self, '_connect_' + self.transports[0])(
  File "C:\Python\Python38\lib\site-packages\engineio\client.py", line 299, in _
connect_polling
    r.status_code), r.json())
  File "C:\Python\Python38\lib\site-packages\requests\models.py", line 898, in j
son
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is the output of the *python* command in the shell:

```
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by miguelgrinberg** [comment]
Okay. I'll see if I can find a Wndows machine to test on. I don't recall having any issues last I tested, but I don't use Windows often, so I guess this is a good opportunity to retest.

Side note, it is really a bad idea to install packages in the global Python interpreter. I suggest you use virtual environments.

**Comment by ehermellin** [comment]
Thanks for the advice ! 

I just make a test on Ubuntu 20.10 with python 3.8 and the last python-socketio and the examples work fine ! So maybe there is an issue with Windows.

**Comment by miguelgrinberg** [comment]
I just tested these examples in a Windows VM and they work fine for me, so I don't really know what the problem is with your Windows machines.

**Comment by ehermellin** [comment]
Thanks for the test.

Which OS do you use ? Python 3.8 in a venv ?

I also don't know what's going on with these computers.
So you can close this topic. Thanks again for your help.

**Comment by miguelgrinberg** [comment]
Normally I use MacOS and Debian. Today I tested on a Windows 10 VM. All with Python 3.8.
