### ISSUE TITLE
Unexpected response from server

### ISSUE THREAD

**Issue by marktimmerman-dev** [miguelgrinberg/python-socketio#575]
When I use the out-of-the-box async latency client, only changed the url for the server. I connect to a javascript node socket.io server.

```
$ python3 latency_client.py 
Traceback (most recent call last):
  File "latency_client.py", line 37, in <module>
    loop.run_until_complete(start_server())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "latency_client.py", line 32, in start_server
    await sio.connect('http://myhost.changed-for-privacy.org:3000')
  File "/home/xxx/.local/lib/python3.8/site-packages/socketio/asyncio_client.py", line 116, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected response from server
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1b0dbde190>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1b0dbcaee0>, 4411.176322446)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1b0dbde220>

```
==============================================

Wireshark of the http connection:

```
GET /socket.io/?transport=polling&EIO=3&t=1606894638.5849655 HTTP/1.1
Host: myhost.changed-for-privacy.org:3000
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.8 aiohttp/3.7.3

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 96
Date: Wed, 02 Dec 2020 07:37:18 GMT
Connection: keep-alive
Keep-Alive: timeout=5

0{"sid":"qnw3sWopYwTxfRNzAAAp","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}


```

**Comment by marktimmerman-dev** [comment]
excuse me. i searched for this issue, but could not find it. now i see that it is due to protocol version.
