### ISSUE TITLE
TypeError: translate_request() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by AndrewJSchoen** [miguelgrinberg/python-socketio#584]
[python version] 3.9.0
[python-socketio version] 4.6.1
[uvicorn version] 0.13.0

I have a simple example that I was trying to get working using SocketIO/Uvicorn, but am getting an error. 
Here is the code:

```
import socketio
import uvicorn

sio = socketio.AsyncServer()
app = socketio.ASGIApp(sio)

@sio.event
async def connect(sid,environ):
    print("Request: 'connect'")

uvicorn.run(app, host='127.0.0.1', port=5000)
```

I have a React web application running on localhost that is using `socket.io-client` to connect. Here is the error I am getting when I attempt to connect from the web application:

```
INFO:     Started server process [23742]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/engineio/async_drivers/asgi.py", line 54, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_server.py", line 356, in handle_request
    return await self.eio.handle_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/engineio/asyncio_server.py", line 191, in handle_request
    environ = translate_request(*args, **kwargs)
TypeError: translate_request() takes 1 positional argument but 3 were given
INFO:     127.0.0.1:58668 - "GET /socket.io/?EIO=3&transport=polling&t=NPSuD5H HTTP/1.1" 500 Internal Server Error
```

Thanks!

**Comment by miguelgrinberg** [comment]
One possibility is that the system is confused about which web server type you are using. Add `async_mode='asgi'` to make it explicit and maybe that'll help.

**Comment by AndrewJSchoen** [comment]
@miguelgrinberg That seems to have fixed the issue! Thanks!

**Comment by radixiura** [comment]
> @miguelgrinberg That seems to have fixed the issue! Thanks!

Did it really help you?

**Comment by trenta3** [comment]
> Did it really help you?
I can confirm that I incurred in this error and adding `async_mode="asgi"` also solved my problem.
Maybe it can be added to the documentation.
