### ISSUE TITLE
Python client socketio cannot connect to nodejs server socketio (unexpected response from server)

### ISSUE THREAD

**Issue by hyperion2333** [miguelgrinberg/python-socketio#592]
I am trying to connect a python client to NodeJs server but I get some errors. When I connect this py client to a python server it works without problems.. Also connected from web to nodeJS works well, but python client to nodejs not..

```
import socketio

sio = socketio.Client()


@sio.event
def connect():
    print("Connected")

@sio.event
def connect_error():
    print('[INFO] Failed to connect to server.')

@sio.event
def disconnect():
    print('[INFO] Disconnected from server.')


@sio.on("message")
def message_received(message):
    print(message)


sio.connect('http://localhost:5000')

sio.emit("something", "Hello from python.")

```

NodeJS server:

```
var app = require('express')();
var http = require('http').createServer(app);


var server = http.listen(5000, () => {
  console.log('listening on *:5000');
});


var io = require('socket.io')(server,{ /*pingInterval: 500,*/ origins: '*:*'});


app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', (socket) => {
  console.log('a user connected');
});
```

The errors:
```

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\socketio\client.py", line 281, in connect
    engineio_path=socketio_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\engineio\client.py", line 195, in connect
    url, headers or {}, engineio_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\engineio\client.py", line 315, in _connect_polling
    'Unexpected response from server'), None)
  File "<string>", line 3, in raise_from
engineio.exceptions.ConnectionError: Unexpected response from server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 31, in <module>
    sio.connect('http://localhost:5000')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\socketio\client.py", line 285, in connect
    exc.args[1] if len(exc.args) > 1 else exc.args[0])
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\socketio\client.py", line 555, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: connect_error() takes 0 positional arguments but 1 was given
```

How can I solve this issue?

**Comment by miguelgrinberg** [comment]
Are you using compatible versions of your client and server? Check the version compatibility chart in the documentation.

**Comment by hyperion2333** [comment]
I solved the problem! 
Yes you are right, the versions weren't compatible and I didn't think of this.. 
Thank you very much!
