### ISSUE TITLE
Client doesn't work on simple example. Error: simplejson.errors.JSONDecodeError

### ISSUE THREAD

**Issue by ihormihal** [miguelgrinberg/python-socketio#593]
I'm trying to run the simple example:
```
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connected to server')

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('wss://echo.websocket.org')
sio.wait()
```

but I'm getting an error:
`Traceback (most recent call last):
  File "cli.py", line 15, in <module>
    sio.connect('wss://echo.websocket.org')
  File "/home/ihor/.local/lib/python3.6/site-packages/socketio/client.py", line 275, in connect
    engineio_path=socketio_path)
  File "/home/ihor/.local/lib/python3.6/site-packages/engineio/client.py", line 187, in connect
    url, headers or {}, engineio_path)
  File "/home/ihor/.local/lib/python3.6/site-packages/engineio/client.py", line 292, in _connect_polling
    arg = r.json()
  File "/home/ihor/.local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I tried also to import json module and set it to sio.Client(json=json) but got the same error. Please advice the solution.

**Comment by ihormihal** [comment]
Sorry, I was trying to connect to the WebSocket but Socket.IO is not an implementation of WebSocket
