### ISSUE TITLE
socketio.exceptions.BadNamespaceError

### ISSUE THREAD

**Issue by chenray844** [miguelgrinberg/python-socketio#603]
@miguelgrinberg 

I am using `AsyncClient` to test `AsyncServer`, but the `client` will raise `BadNamespaceError` when `emit` data to `server`.

### client
```python
# -*- coding: utf-8 -*- 

import asyncio 
import socketio 

async def main():
  host = 'http://localhost:8080'
  nsp  = '/array'
  event= 'event_array'

  sio = socketio.AsyncClient()

  @sio.on(event,namespace=nsp)
  async def hander_array(msg):
    print(msg)
    await sio.sleep(1.0)
    await sio.disconnect()

  await sio.connect(host)
  data = {

  }

  await sio.emit(event,data=data,namespace=nsp)
  print('emit')
  await sio.wait()
  print('done')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
``` 

### server 

```python
# -*- coding: utf-8 -*-

import asyncio
import time

import numpy as np
from aiohttp import web
import socketio
import aiofiles

sio = socketio.AsyncServer(async_mode='aiohttp')
app = web.Application()
sio.attach(app)

@sio.on('event_array', namespace='/array')
async def test_array(sid, message):
    t1 = time.time()
    event = 'event_array'
    data = {}
    for i in range(4):
        key = 'key_{}'.format(i)
        array = np.arange(int(1e6),dtype=np.float64)
        data.update({key:array.tobytes()})


    t2 = time.time()
    await sio.emit(event, data={event:data}, room=sid, namespace='/array')
    t3 = time.time()

    print('create array cost [{:.3f}] seconds'.format(t2-t1))
    print('emit data cost [{:.3f}] seconds'.format(t3-t2))
    print('total cost [{:.3f}] seconds'.format(t3-t1))


if __name__ == '__main__':
    web.run_app(app,host='localhost',port=8080)

```

### version
```
pip list |grep socketio
python-socketio        5.0.4
```

### exception-info
```
python3 aio_client.py 
Traceback (most recent call last):
  File "aio_client.py", line 30, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "aio_client.py", line 24, in main
    await sio.emit(event,data=data,namespace=nsp)
  File "/home/chenrf/.local/lib/python3.8/site-packages/socketio/asyncio_client.py", line 165, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: /array is not a connected namespace.

```
this `exception` is raised by https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_client.py#L164 .

How can i fix this? can you give me same advice, Thanks.

**Comment by miguelgrinberg** [comment]
You have to wait until the connect handler for the namespace is invoked before you emit on that namespace. Basically you have a race condition, you call `connect()`, which performs some work in the background, and this work hasn't completed by the time you call `emit()`.

**Comment by chenray844** [comment]
I add `await sio.sleep(1.0)` fixed. thanks a lot for your advice.
