### ISSUE TITLE
Python socketio[client] giving the following error in Raspberry pi

### ISSUE THREAD

**Issue by JottaPereira** [miguelgrinberg/python-socketio#615]
Hi,
I have a piece of code, that works fine in windows, but when I trie to run it on my raspberry pi, returns me an error and is not able to connect to the server.

```

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/socketio/client.py", line 279, in connect
    engineio_path=socketio_path)
  File "/home/pi/.local/lib/python3.7/site-packages/engineio/client.py", line 187, in connect
    url, headers or {}, engineio_path)
  File "/home/pi/.local/lib/python3.7/site-packages/engineio/client.py", line 306, in _connect_polling
    'OPEN packet not returned by server')
engineio.exceptions.ConnectionError: OPEN packet not returned by server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    sio.connect("*******")
  File "/home/pi/.local/lib/python3.7/site-packages/socketio/client.py", line 283, in connect
    exc.args[1] if len(exc.args) > 1 else exc.args[0])
  File "/home/pi/.local/lib/python3.7/site-packages/socketio/client.py", line 547, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: connect_error() takes 0 positional arguments but 1 was given

```

My server is working fine. (it is already hosted) A prove of that is that my windows code executed with no errors.

Some of the code:
```

sio = socketio.Client()

@sio.event
def connect():
    print("I'm connected!")
    #print('my sid is', sio.sid)
    sio.emit("**", **)
    open_radio()
@sio.event
def connect_error():
    print("The connection failed!")
@sio.event
def disconnect():
    print("I'm disconnected!")  

sio.connect(SERVER_URL)
sio.wait()

```

**Comment by JottaPereira** [comment]
I discovered why!

I had to downgrade my version to version 4.X.X to be compatible to my server socket.io version (javascript version 2.X.X)
