### ISSUE TITLE
(asyncClient) TypeError: 'WebSocketError' object is not subscriptable

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [miguelgrinberg/python-socketio#621]
### Versions:

I've used installed the package using the following command:
```bash
$ pip install "python-socketio[asyncio_client]"
```
- Python `3.7.9`
- python-socketio (asyncio_client) `5.0.4`
- websockets `8.1`
- python-engineio `4.0.0`
- aiohttp `3.7.3`

### code:
I've tried both  [`fiddle_client.py`](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/asyncio/fiddle_client.py) & [`latency_client.py`](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/asyncio/latency_client.py) examples from your repository and only changed the `port` to connect to my existing `js 3.0.4 server` , both have the same error with slight change

#### [`fiddle_client.py`](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/asyncio/fiddle_client.py) error:
```bash
Traceback (most recent call last):
  File "src/main.py", line 28, in <module>
    asyncio.run(start_server())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "src/main.py", line 23, in start_server
    await sio.connect('http://localhost:3000')
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/socketio/asyncio_client.py", line 112, in connect
    engineio_path=socketio_path)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 111, in connect
    url, headers or {}, engineio_path)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 251, in _connect_polling
    if await self._connect_websocket(url, headers, engineio_path):
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 328, in _connect_websocket
    pkt = packet.Packet(encoded_packet=p)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/packet.py", line 27, in __init__
    self.decode(encoded_packet)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/packet.py", line 51, in decode
    b64 = not self.binary and encoded_packet[0] == 'b'
TypeError: 'WebSocketError' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f37a21372d0>
```

#### [`latency_client.py`](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/asyncio/latency_client.py) error:
```bash
Traceback (most recent call last):
  File "src/main.py", line 38, in <module>
    loop.run_until_complete(start_server())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "src/main.py", line 33, in start_server
    await sio.connect('http://localhost:3000')
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/socketio/asyncio_client.py", line 112, in connect
    engineio_path=socketio_path)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 111, in connect
    url, headers or {}, engineio_path)
  File "/home/<username>Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 251, in _connect_polling
    if await self._connect_websocket(url, headers, engineio_path):
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 328, in _connect_websocket
    pkt = packet.Packet(encoded_packet=p)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/packet.py", line 27, in __init__
    self.decode(encoded_packet)
  File "/home/<username>/Desktop/test/.venv/lib/python3.7/site-packages/engineio/packet.py", line 51, in decode
    b64 = not self.binary and encoded_packet[0] == 'b'
TypeError: 'WebSocketError' object is not subscriptable
```

I appreciate your help to solve this issue as I don't know what went wrong in the process.

**Comment by miguelgrinberg** [comment]
Did you try pointing the examples to the corresponding node based fiddle and latency servers included in this repository? I want to know if this just happens against your own server or if there is some general problem I'm not aware of.

**Comment by AbdallahAlhaddad** [comment]
@miguelgrinberg thank you for your fast response.
I have tried `fiddle js server` example and it works with `fiddle client`, so i started seeing the differences and found that:

**the [peerjs-server](https://github.com/peers/peerjs-server)  I was using on my server was causing this problem**

although it was tricky because:
- The normal `python-socket.io client` (not the async one) was working without any errors.
-  I have noticed now that It was the cause of the following error on my existing `web js client` (but it was also working):
```bash
websocket.js?5f0f:87 WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=4&transport=websocket&sid=4MuA6oXuSmwHcJdWAAAC' failed: Invalid frame header
```

- my faulty server configuration was:
```js
const peerEndpoint = '/cam-stream'
const port = 3000
const express = require('express')
const { ExpressPeerServer } = require('peer')
const app = express()

const server = require('http').createServer(app) 

const io = require('socket.io')(server) 

const peerServer = ExpressPeerServer(server, {
  debug: true,
  path: peerEndpoint //peerjs available at localhost:3000/cam-stream
})

app.use(peerServer)

```

So now i will try to fix `peerjs` instead.
Thank you again for your time and the great library.
