### ISSUE TITLE
Client gets socketio.exceptions.BadNamespaceError on emit

### ISSUE THREAD

**Issue by bartosh** [miguelgrinberg/python-socketio#628]
I've upgraded python-socketio from 4.6.0 to 5.0.4 on both server and client, python-engineio is upgraded from 3.13.2 to 4.0.0

As a result client crashes when trying to emit anything to the server:
```
$ cat test-socketio.py 
#!/usr/bin/env python

import socketio
import time

sio = socketio.Client()
sio.connect("http://localhost:5050")
#while not sio.namespaces:
#    time.sleep(1)

sio.emit('test', {})

sio.disconnect()


$ ./test-socketio.py 
Traceback (most recent call last):
  File "./test-socketio.py", line 11, in <module>
    sio.emit('test', {})
  File "/Users/ed/.virtualenvs/test/lib/python3.8/site-packages/socketio/client.py", line 328, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

However, when I uncomment these 2 lines it starts to work again:
```
while not sio.namespaces:
    time.sleep(1)
```

It looks like Client.connect method returns before Client._handle_connect method is called, so Client.namespaces dictionary is not yet updated when self.emit is called.

server log doesn't seem to have any errors:
```
2021-02-04 18:48:11,749 INFO: socketIO connect: sid: zdaTm6FhTM2GtxK5AAAL, environ: {'wsgi.input': <aiohttp.streams.EmptyStreamReader object at 0x7fad58f72210>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.version': (1, 0), 'wsgi.async': True, 'wsgi.multithread': False, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'SERVER_SOFTWARE': 'aiohttp', 'REQUEST_METHOD': 'GET', 'QUERY_STRING': 'transport=polling&EIO=4&t=1612482491.099972', 'RAW_URI': '/socket.io/?transport=polling&EIO=4&t=1612482491.099972', 'SERVER_PROTOCOL': 'HTTP/1.1', 'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '0', 'SERVER_NAME': 'aiohttp', 'SERVER_PORT': '0', 'aiohttp.request': <Request GET /socket.io/ >, 'HTTP_HOST': 'localhost:5050', 'HTTP_USER_AGENT': 'python-requests/2.25.1', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate', 'HTTP_ACCEPT': '*/*', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.url_scheme': 'http', 'PATH_INFO': '/socket.io/', 'SCRIPT_NAME': ''}
```

Any idea what could be a reason for this?

**Comment by miguelgrinberg** [comment]
Yes, this was asked a few times in this issue board already. The Socket.IO connection happens in the background, it takes a few exchanges until the namespaces are set up and can be written to. Due to some changes in how namespaces are connected this is now an error, while it was handled silently before.

The best way to handle this is to wait until the `connect` handler for the namespace is invoked. I will be looking at ways to handle this better in the future, but for now this is the best option.

**Comment by bartosh** [comment]
Thank you. I knew it's a known issue! Closing the issue.
