### ISSUE TITLE
I've got a very strange problem.It causes my event to fail to receive data

### ISSUE THREAD

**Issue by MISAKIGA** [miguelgrinberg/python-socketio#651]
> The version I used
> python-socketio                    5.0.3
>  websocket-client                  0.58.0

This is the client code and output.

```python
sio = socketio.Client(reconnection=True, logger=True, engineio_logger=True)
Payload.max_decode_packets = 500

def start_server(self):
    sio.connect(self.args['ip'], transports='websocket',namespaces=['/connector', '/telemetry'])
    sio.wait()

@sio.on('connect', namespace='/connector')
def on_connect():
    print('connect')

# 
@sio.on('steer', namespace='/steer')
def telemetry(sid, data):
    print(data)
    img_b64 = img2b64(img)
    sio.emit("telemetry",data={
        'image': img_b64
    }, namespace='/telemetry')
```

> client control log

```sh
Attempting WebSocket connection to ws://192.168.137.1:8828/socket.io/?transport=websocket&EIO=4
WebSocket connection accepted with {'sid': 'TVATwAm1yGJCdgdXAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0/connector
Sending packet MESSAGE data 0/telemetry
Received packet MESSAGE data 0/connector,{"sid":"lQyFX5CRCMkI5RYDAAAB"}
Namespace /connector is connected
connect
Received packet MESSAGE data 0/telemetry,{"sid":"f43IpbI02DRIGDBXAAAC"}
Namespace /telemetry is connected
Received packet PING data 
Sending packet PONG data 
Received packet PING data 
Sending packet PONG data 
Received packet PING data 
```
This is the server code and output

```python
app = Flask(__name__)
sio = socketio.Server(logger=True, engineio_logger=True) 

Payload.max_decode_packets = args['ENGINEIO_MAX_DECODE_PACKETS'] 
# bind web server and socketio
app = socketio.Middleware(sio,app)
# socket event
eventlet.wsgi.server(eventlet.listen(('',8828)),app)

#------ socket
@sio.on('connect', namespace='/connector')
def on_connect(sid, env):
    print("websocket connect")
    
    # return ok is not work
    # return 'ok'

    #  or comment out the on_connect method
    # raise RuntimeError('websocket testError')

@sio.on('telemetry', namespace='/telemetry')
def telemetry(sid, data):
    
    if args['showimg']:
        cv2.imshow('i',image)
        cv2.waitKey(1)

```
> server control log
```sh
(21400) wsgi starting up on http://0.0.0.0:8828
(21400) accepted ('192.168.137.219', 43052)
7w5n6cZpVKjosudnAAAA: Sending packet OPEN data {'sid': '7w5n6cZpVKjosudnAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
7w5n6cZpVKjosudnAAAA: Received request to upgrade to websocket
7w5n6cZpVKjosudnAAAA: Upgrade to websocket successful
7w5n6cZpVKjosudnAAAA: Received packet MESSAGE data 0/connector
websocket connect
7w5n6cZpVKjosudnAAAA: Sending packet MESSAGE data 0/connector,{"sid":"JQzsNurM2vsBWTXFAAAB"}
7w5n6cZpVKjosudnAAAA: Received packet MESSAGE data 0/telemetry
7w5n6cZpVKjosudnAAAA: Sending packet MESSAGE data 0/telemetry,{"sid":"Ku_ks7V4II6Q39xSAAAC"}
7w5n6cZpVKjosudnAAAA: Sending packet PING data None
7w5n6cZpVKjosudnAAAA: Received packet PONG data
```

## __When I use the above code, I find that this causes the Telemetry event to be disconnected.__

But I try to uncomment the following code and it works.

```sh
    raise RuntimeError('websocket testError')
```

> this is the log output from the client console

```sh
Attempting WebSocket connection to ws://192.168.137.1:8828/socket.io/?transport=websocket&EIO=4
WebSocket connection accepted with {'sid': 'RRIbzqYlTkIAtv1bAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0/connector
Sending packet MESSAGE data 0/telemetry
Received packet MESSAGE data 0/telemetry,{"sid":"ggiYa8L742J32WnDAAAC"}
Namespace /telemetry is connected
Emitting event "telemetry" [/telemetry]
Sending packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
Sending packet MESSAGE data <binary>
Emitting event "telemetry" [/telemetry]
Sending packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
Sending packet MESSAGE data <binary>
Emitting event "telemetry" [/telemetry]
Sending packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
Sending packet MESSAGE data <binary>
Emitting event "telemetry" [/telemetry]
Sending packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
Sending packet MESSAGE data <binary>
```

> this is the server side console log

```sh
RRIbzqYlTkIAtv1bAAAA: Sending packet OPEN data {'sid': 'RRIbzqYlTkIAtv1bAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
RRIbzqYlTkIAtv1bAAAA: Received request to upgrade to websocket
RRIbzqYlTkIAtv1bAAAA: Upgrade to websocket successful
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 0/connector
websocket connect
message handler error
Traceback (most recent call last):
  File "E:\AISystem\software\lib\site-packages\engineio\server.py", line 595, in _trigger_event
    return self.handlers[event](*args)
  File "E:\AISystem\software\lib\site-packages\socketio\server.py", line 724, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace)
  File "E:\AISystem\software\lib\site-packages\socketio\server.py", line 624, in _handle_connect
    self.environ[eio_sid])
  File "E:\AISystem\software\lib\site-packages\socketio\server.py", line 696, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "ai_socket_service_showimg.py", line 239, in on_connect
    raise RuntimeError('websocket testError')
RuntimeError: websocket testError
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 0/telemetry
RRIbzqYlTkIAtv1bAAAA: Sending packet MESSAGE data 0/telemetry,{"sid":"ggiYa8L742J32WnDAAAC"}
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data <binary>
received event "telemetry" from ggiYa8L742J32WnDAAAC [/telemetry]
ai_socket_service_showimg.py:223: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  nparr = np.fromstring(bimage, np.uint8)
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data <binary>
received event "telemetry" from ggiYa8L742J32WnDAAAC [/telemetry]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data <binary>
received event "telemetry" from ggiYa8L742J32WnDAAAC [/telemetry]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data 51-/telemetry,["telemetry",{"image":{"_placeholder":true,"num":0}}]
RRIbzqYlTkIAtv1bAAAA: Received packet MESSAGE data <binary>
```

> It is not elegant to throw an error every time to solve the problem. Is there a way to solve this problem?
> In addition, my client uses Raspberry Pi to send video streams.
> python-socketio               5.0.4
> requests-unixsocket           0.1.5
> websocket-client              0.58.0

**Comment by miguelgrinberg** [comment]
The code appears to be just a simplification of the code that generate the logs, correct?

What is the purpose of the `/connector` namespace? Can you show me the complete connect handler for it?

**Comment by MISAKIGA** [comment]
thank you for your help. I seem to have missed some key code.

> after a search I found that I had found the problem.

```python

@sio.on('connect')
def on_connect():
    print('connect')
    
   # I see the problem here, when I comment out this line, everything works fine
   # When I do not use <kbd>/connector</kbd>, the program will report <kbd>socketio.exceptions.BadNamespaceError: / is not a connected namespace.</kbd> error
    zxcar_client.STATE = 1
```

this is the code that repeats the problem.

> socket_client
```python
#! /usr/bin/env python3.7
import cv2
from threading import Thread
import numpy as np
import time
import socketio
import base64
from engineio.payload import Payload

# debug: logger=True, engineio_logger=True
sio = socketio.Client(reconnection=True, logger=True, engineio_logger=True)

class ZXCarClient:
    def __init__(self, args):
        
        self.args = args
        self.cam_id = self.args['cam_id']
        self.camera = cv2.VideoCapture(self.cam_id)
        self.camera.set(cv2.CAP_PROP_FRAME_WIDTH, self.args['width'])
        self.camera.set(cv2.CAP_PROP_FRAME_HEIGHT, self.args['height'])
        self.STATE = 0

        
        try:
            Thread(target=self.__do_camera_image).start()
        except Exception as e:
            print('[Thread_ERROR] Exception： ', str(e))
            print(e)

    def img2b64(self, frame):
        img_encode = cv2.imencode('.jpg',frame)[1]
        data_encode = np.array(img_encode)
        data_encode = data_encode.tostring()
        img_b64 = base64.b64encode(data_encode) 
        return img_b64

    def send_car_data(self, angle, throttle, img_b64):

        if self.STATE == 0:
            
            sio.emit("telemetry",data={
                'image': img_b64
            })

    def __do_camera_image(self):
        print('[camera_sub_thread] running')

        while True:
            ret, frame = self.camera.read()
            if not ret:
                print('[ERROR]: frame error')

            img_b64 = self.img2b64(frame)

            angle = 0
            throttle = 0

            self.send_car_data(angle, throttle, img_b64)


    def close(self):
        self.camera.release()
        sio.disconnect()

    def start_server(self):
        sio.connect(self.args['ip'], transports='websocket')
        sio.wait()

@sio.on('connect')
def on_connect():
    print('connect')

    # I see the problem here, when I comment out this line, everything works fine
    zxcar_client.STATE = 1

@sio.on('steer')
def telemetry(sid, data):

    angular = float(data['steering_angle'])
    throttle = float(data['throttle'])

    print(angular, throttle)


if __name__=='__main__':


    args = {
        'cam_id'           : 0,
        'ip'               : 'http://192.168.137.1:8828',
        'width'            : 320,   
        'height'           : 120,
        'channel'          : 3,
        'ENGINEIO_MAX_DECODE_PACKETS' : 500
    }

    Payload.max_decode_packets = args['ENGINEIO_MAX_DECODE_PACKETS'] 

    zxcar_client = ZXCarClient(args)

    if not zxcar_client.camera.isOpened():
        print("[ERROR] camera not opened")
    else:

        zxcar_client.start_server()

       # rate = rospy.Rate(20)
        while zxcar_client.STATE != -1:
            pass
        #    rate.sleep()

        zxcar_client.close()

```

> socket_server
```python
import eventlet
import socketio
from flask import Flask
import cv2
import base64
import numpy as np
#import tensorflow as tf
#from tensorflow.keras import backend as K
from threading import Thread
from engineio.payload import Payload
from queue import Queue 

import time

app = Flask(__name__)

sio = socketio.Server(logger=True, engineio_logger=True) 

class ZXCarServer:
    def __init__(self, args):
        self.args = args

    def send_car_data(self):

        sio.emit("steer",data={
            'steering_angle':'1',
            'throttle': '1'
        })

    def b64_to_cvimg(self, data):
        bimage = base64.b64decode(data)
        nparr = np.fromstring(bimage, np.uint8)
        img_decode = cv2.imdecode(nparr,1)
        image = cv2.cvtColor(img_decode,cv2.COLOR_BGR2RGB)
        return image

#------ socket
@sio.on('connect')
def on_connect(sid, env):
    print("websocket connect")

    # raise RuntimeError('websocket testError')
 
@sio.on('telemetry')
def telemetry(sid, data):
    
    global zxcar_server

    image = zxcar_server.b64_to_cvimg(data['image'])
    
    if args['showimg']:
        cv2.imshow('i',image)
        cv2.waitKey(1)

args = { 
    'showimg'          : True,
    'ENGINEIO_MAX_DECODE_PACKETS' : 500
}

zxcar_server = ZXCarServer(args)

Payload.max_decode_packets = args['ENGINEIO_MAX_DECODE_PACKETS'] 

# bind web server and socketio
app = socketio.Middleware(sio,app)
# socket event
eventlet.wsgi.server(eventlet.listen(('',8828)),app)
```

> although I could have solved this problem in other ways, I still want to know why.Forgive me, I'm new to Python. XD

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand what answers you need. You had some error. I asked you to show me the complete code. The code that you are showing above does not match the incomplete code that you showed first.

**Comment by MISAKIGA** [comment]
I'm sorry, I have made some modifications, please refer to the last code.I solved this problem by using global variables.      
Thank you for your help.

**Comment by MISAKIGA** [comment]
Thank you. We have solved my problem. Thank you for your help.I'm going to close this issue
