### ISSUE TITLE
socketio.ASGIApp with static_files arg considers every request as a request for a static file

### ISSUE THREAD

**Issue by max-l** [miguelgrinberg/python-socketio#653]
I only need to serve a single static html file for the path "/", 
and for all other requests, serve it with dynamic (json) sync and async requess

When I supplu the following static_files rules, ASGIApp considers all requests as static
example: http://127.0.0.1/api/123   is interpreted as a static file request

```
app = socketio.ASGIApp(
    sio,
    other_asgi_app=App(),
    static_files={
        '/': {
            'filename': "....some file /ui/index.html",
            'content_type': 'text/plain'
        }
    }
)
```
```

INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/maxou/dev/dry_pipe/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/maxou/dev/dry_pipe/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/maxou/dev/dry_pipe/venv/lib/python3.8/site-packages/engineio/async_drivers/asgi.py", line 56, in __call__
    static_file = get_static_file(scope['path'], self.static_files) \
  File "/home/maxou/dev/dry_pipe/venv/lib/python3.8/site-packages/engineio/static_files.py", line 36, in get_static_file
    f = static_files[path + '/'] + rest[1:]


```

**Comment by miguelgrinberg** [comment]
@max-l can I ask you to install the python-engineio package from the master git branch to confirm that this problem has been addressed? Thanks!
