### ISSUE TITLE
Client examples causes "socketio.exceptions.ConnectionError: One or more namespaces failed to connect"

### ISSUE THREAD

**Issue by Torxed** [miguelgrinberg/python-socketio#672]
Using your examples [Flask-SocketIO #Initialization](https://flask-socketio.readthedocs.io/en/latest/):
```python
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

if __name__ == '__main__':
    socketio.run(app)
```

And your client examples for [python-socketio Intro->Client Examples](https://python-socketio.readthedocs.io/en/latest/intro.html):
```python
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')

@sio.event
def my_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://localhost:5000')
sio.wait()
```

You will get (on the client side):
```
<module '_brotli' from 'C:\\Users\\anton\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_brotli.cp39-win_amd64.pyd'>
Traceback (most recent call last):
  File "C:\Users\anton\prodout_scanner.py", line 18, in <module>
    sio.connect('http://localhost:5000')
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\socketio\client.py", line 308, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
connection established
```

Not sure if this is related to https://github.com/miguelgrinberg/Flask-SocketIO/issues/1432#issuecomment-819335302?

**Comment by Torxed** [comment]
Turns out localhost isn't always the case. Closing because it's a network issue (although `connection established` shows up)

**Comment by njavilas2015** [comment]
In my case server in nodejs 4.2.0 its work fine but 4.4.0 not work!
