### ISSUE TITLE
ClientConnectorCertificateError raised by aiohttp gets silenced

### ISSUE THREAD

**Issue by max-l** [miguelgrinberg/python-socketio#706]
I was getting this exception : 

```
Traceback (most recent call last):
  File "/vagrant/ibio_singlecell/drypipe/dry_pipe/websocket_client.py", line 39, in start_client
    await self.socketio_client.connect(self.url)
  File "/ibio_venv/lib/python3.8/site-packages/socketio/asyncio_client.py", line 117, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection refused by the server

```

The error message was not helpful in finding the cause,  and I then disabled the verification of the server certificate with:

socketio_client = socketio.AsyncClient(ssl_verify=False)

And sure enough, I the connection was no longer being refused.

I then tried calling the same URL with the underlying aiohttp library, with: 

```
    async with aiohttp.ClientSession() as session:
        async with session.get("https://...") as response:

            print("Status:", response.status)
            print("Content-type:", response.headers['content-type'])

            html = await response.text()
            print("Body:", html[:15], "...")
```

And got this very useful exception : 

```
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/vagrant/ibio_singlecell/drypipe/dry_pipe/websocket_client.py", line 83, in main
    async with session.get("https://ibio-test.genap.ca") as response:
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/ibio_venv/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host ibio-test.genap.ca:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]

```

It appears that somewhere the exception gets silenced, I wasn't able to find exactly where and why.

**Comment by miguelgrinberg** [comment]
Yeah, I do see the problem here. Request errors are logged, but I have them at info level, which means that you will not see these errors unless you explicitly turn on logs.
