### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by buendiya** [miguelgrinberg/python-socketio#746]
I came across this exception when I try to close socketio Client.

```txt
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/engineio/client.py", line 687, in _write_loop
    self.ws.send(encoded_packet)
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/websocket/_core.py", line 279, in send_frame
    l = self._send(data)
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/websocket/_core.py", line 449, in _send
    return send(self.sock, data)
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/home/jingsz/.virtualenvs/webrtc_peer/lib/python3.6/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor
```

The reason maybe is that it is sending STOP packet after the connection have been closed.

**Comment by miguelgrinberg** [comment]
You must be using an old version of the python-engineio package, because this was fixed a few months ago. See https://github.com/miguelgrinberg/python-engineio/issues/177.
