### ISSUE TITLE
asyncio.exceptions.CancelledError on shutdown of aiohttp deployment.

### ISSUE THREAD

**Issue by shasan-beanfield** [miguelgrinberg/python-socketio#750]
**Describe the bug**
I get pretty consistent printout of the folowing traceback every time there is a server restart.  This should have been handled in asyncio_redis_manager.py as an additional exception which simply stops listening (by terminating the infinite loop there).  Unless there is a different graceful shutdown pathway I'm not considering.

**To Reproduce**
1. Setup python-socketio with aiohttp deployment strategy
2. run server
3. stop server

**Expected behavior**
I wouldn't expect this to be thrown as an issue at all.  We know the server is shutting down, and ultimately cancelling all asyncio tasks related to the current loop.

**Logs**
Traceback (most recent call last):
  File ".venv/lib/python3.8/site-packages/socketio/asyncio_pubsub_manager.py", line 152, in _thread
    message = await self._listen()
  File ".venv/lib/python3.8/site-packages/socketio/asyncio_redis_manager.py", line 98, in _listen
    return await self.ch.get()
  File ".venv/lib/python3.8/site-packages/aioredis/pubsub.py", line 73, in get
    msg = await self._queue.get()
  File ".venv/lib/python3.8/site-packages/aioredis/pubsub.py", line 416, in get
    await self.wait()
  File ".venv/lib/python3.8/site-packages/aioredis/pubsub.py", line 412, in wait
    await self._event.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

**Additional context**

**Comment by miguelgrinberg** [comment]
Thanks. Can I ask you to install python-socketio from the main branch and confirm the bug is fixed?

**Comment by shasan-beanfield** [comment]
Hi, Our app is not yet compatible with this version of socket.io  I will update this ticket once it is.
