### ISSUE TITLE
socketio requires asyncio

### ISSUE THREAD

**Issue by sibbi77** [miguelgrinberg/python-socketio#765]
I'm on yocto zeus and my python is therefore stripped down.
My requirements.txt:
```
python-socketio[client]==5.4.0
```

From the documentation this should work without requiring asyncio.

Stack trace:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import socketio
  File "/root/lte-roundtrip-test-master/client/venv/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/root/lte-roundtrip-test-master/client/venv/lib/python3.7/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/root/lte-roundtrip-test-master/client/venv/lib/python3.7/site-packages/engineio/__init__.py", line 7, in <module>
    from .asyncio_server import AsyncServer
  File "/root/lte-roundtrip-test-master/client/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 1, in <module>
    import asyncio
ModuleNotFoundError: No module named 'asyncio'
```

**Expected behavior**
I thought I can use socketio without asyncio by installing python-socketio[client]. Isn't that the case?

**Additional context**
I believe this will happen only in constrained environments, like Yocto.

**Comment by miguelgrinberg** [comment]
I haven't considered a stripped down platform. The package expects a standard Python 3.7+ version.

**Comment by sibbi77** [comment]
ok, thanks.
