### ISSUE TITLE
Documentation client example throws an error using latest python release

### ISSUE THREAD

**Issue by ahmedabt** [miguelgrinberg/python-socketio#843]
**Describe the bug**
Using Python 3.9.9 on MacOS 12.1, asyncio client example throws the following error

```
DEBUG:asyncio:Using selector: KqueueSelector
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '4 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/PycharmProjects/proxy-over-http/websocket_client.py", line 30, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 39, in run
    loop = events.new_event_loop()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 112, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
Exception ignored in: <function BaseEventLoop.__del__ at 0x104f64a60>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 63, in close
    if self._signal_handlers:
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'
sys:1: RuntimeWarning: coroutine 'main' was never awaited
```

**To Reproduce**
Run the mentioned code below using latest python v3.9.9 on MacOS 
python -m venv
venv/bin/pip install eventlet python-socketio
venv/bin/python <file_path>

**Code**
```
import asyncio

import socketio

sio = socketio.AsyncClient()


@sio.event
async def connect():
    print('connection established')


@sio.event
async def my_message(data):
    print('message received with ', data)
    await sio.emit('my response', {'response': 'my response'})


@sio.event
async def disconnect():
    print('disconnected from server')


async def main():
    await sio.connect('http://127.0.0.1:8000')
    await sio.wait()


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by ahmedabt** [comment]
It is somehow related to eventlet; If eventlet is installed in your python env, it breaks. Even if you are not using eventlet in your code.

**Comment by miguelgrinberg** [comment]
You haven't provided a server to go with this client. Using one of the server examples in this repository, I do not see any errors.

**Comment by ahmedabt** [comment]
Without even running a server, the error always occurs by running the above code. It is 100% reproducible.

It is somehow linked to eventlet (pip install eventlet).

**Comment by miguelgrinberg** [comment]
This is strange. I can't reproduce the problem here.

**Comment by ahmedabt** [comment]
just checking, are you using the same python version on macOS? Also, are you using virtual env to exclude any other pre-installed packages?

**Comment by miguelgrinberg** [comment]
I still can't reproduce, but I just realized that there is a rogue `import eventlet` in the code. Assuming there is some sort of incompatibility between eventlet and asyncio, this import is what triggering the problem. I'll think about how to remove that import when eventlet isn't used.

**Comment by LC-06** [comment]
Remove Eventlet in pip did it for me
