### ISSUE TITLE
client connect: url parameter is always truncated to hostname:port ?

### ISSUE THREAD

**Issue by bialix** [miguelgrinberg/python-socketio#845]
**Describe the bug**

Using simple code:

```
sio = socketio.Client(logger=True, engineio_logger=True)
sio.connect('https://my.host.name/chat/')
```

I got 404 from my server because library changed URL to be just `https://my.host.name` and appends `/socket.io/?transport=polling&EIO=4`

Resulting:

```
Attempting polling connection to https://my.host.name/socket.io/?transport=polling&EIO=4
The connection failed!
Traceback (most recent call last):
File "chat-client.py", line 34, in <module>                                                                                                                     sio.connect('https://my.host.name/chat/')                                                                                                       
File "sio-chat-test\py-client\venv\lib\site-packages\socketio\client.py", line 338, in connect                                       
raise exceptions.ConnectionError(exc.args[0]) from None                                                                                                   socketio.exceptions.ConnectionError: Unexpected status code 404 in server response 
```

**To Reproduce**

**Expected behavior**

**Logs**
Please provide relevant logs from the server and the client. On the Python server and client, add the `logger=True` and `engineio_logger=True` arguments to your `Server()` or `Client()` objects to get logs dumped on your terminal. If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Additional context**

**Comment by bialix** [comment]
Changing my code to use socketio_path helps but it looks like url parameters doc either misleading or actually a bug.

```
sio.connect('https://my.host.name/', socketio_path='chat/socket.io')
```
