### ISSUE TITLE
i use aiohttp2.0.1,throw error "AttributeError: module 'aiohttp' has no attribute 'HttpMessage'"

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#86]
`
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/Volumes/macsource/01-Project/03-Pyvirtual/aiohttp/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/Volumes/macsource/01-Project/03-Pyvirtual/aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 289, in _handle
    resp = yield from handler(request)
  File "/Volumes/macsource/01-Project/03-Pyvirtual/aiohttp/lib/python3.5/site-packages/engineio/asyncio_server.py", line 107, in handle_request
    environ = self._async['translate_request'](*args, **kwargs)
  File "/Volumes/macsource/01-Project/03-Pyvirtual/aiohttp/lib/python3.5/site-packages/engineio/async_aiohttp.py", line 35, in translate_request
    'SERVER_SOFTWARE': aiohttp.HttpMessage.SERVER_SOFTWARE,
AttributeError: module 'aiohttp' has no attribute 'HttpMessage'
`

**Comment by iad42** [comment]
For me - the solution is to use sanic, because aiohttp.HttpMessage became deprecated. I did not find a way to fix that. So just stopped using that.

**Comment by miguelgrinberg** [comment]
@iad42 this is an old bug, you can use aiohttp now.
