### ISSUE TITLE
GeneratoeExit / Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by PhpEssential** [miguelgrinberg/python-socketio#863]
Hi, 

I don't know why I've got this exception and I don't kown how to debug it. I have multiple asyncio task and multiple asyncio loop in the same program. 

The stack trace seems to indicate a problem in asyncio_server.py:

```
Exception ignored in: <coroutine object AsyncServer._handle_event_internal at 0x0000021EA39205C0>
Traceback (most recent call last):
  File "C:\Users\Livepick\.conda\envs\livepick-dispatcher-test\lib\site-packages\socketio\asyncio_server.py", line 504, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\Livepick\.conda\envs\livepick-dispatcher-test\lib\site-packages\socketio\asyncio_server.py", line 531, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
RuntimeError: coroutine ignored GeneratorExit
2022-01-30 21:40:27 - [asyncio][ERROR](Thread-3  ) Task was destroyed but it is pending!
task: <Task pending name='Task-435' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\Livepick\.conda\envs\livepick-dispatcher-test\lib\site-packages\socketio\asyncio_server.py:502> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000021EA974DFA0>()]>>
```

It's difficult to have a complete code sample without share you the all project, have you an idea for debug this error?

It's seems to occur when I cancel futures in the run function:

main.py
```
import uvicorn
import socketio
import time

import asyncio
from threading import Thread
from socketio.asyncio_server import AsyncServer

THREAD_DICT = {}
IMAGE_THREAD_DICT = {}
_LOCK = None
src_picture_list, dst_picture_list = [] # 9 numpy image load with opencv

class Context:
    def __init__(self):
        self.ws_server = AsyncServer(cors_allowed_origins='*', async_mode='asgi')
        self.server_loop = asyncio.new_event_loop()
        self.analyze_loop = asyncio.new_event_loop()

class Controller:
    def __init__(self, context:Context) -> None:
        self.context = context

    async def launch_analyze(self, sid):
        try:
            await run(1, src_picture_list, dst_picture_list, self.context)
        except:
            print("Error when try to launch analyze")

async def run(ticket_id, src_picture_list, dst_picture_list, context): 
    if _LOCK is None:
        _LOCK = asyncio.Lock()
    if ticket_id in THREAD_DICT and _LOCK.locked():
        futures = IMAGE_THREAD_DICT[ticket_id]
        for future in futures:
            future.cancel()
        for future in futures:
            while not future.done():
                print("Waiting previous image analyze future stop")
                await asyncio.sleep(0.5)    
        
        THREAD_DICT[ticket_id].cancel()
        while not THREAD_DICT[ticket_id].done():
            print("Waiting previous ticket analyze task stop")
            await asyncio.sleep(0.5)
  
    async with _LOCK:
        IMAGE_THREAD_DICT[ticket_id] = []
        THREAD_DICT[ticket_id] = asyncio.create_task(analyze_ticket(ticket_id, src_picture_list, dst_picture_list, context))
        await THREAD_DICT[ticket_id]
        THREAD_DICT.pop(ticket_id)

async def analyze_ticket(ticket_id, src_picture_list, dst_picture_list, context):
    try:
        picture_count = len(src_picture_list)
        for i in range(picture_count):
            process_analyze(ticket_id, src_picture_list[i], dst_picture_list[i], context)

        thread_count = len(IMAGE_THREAD_DICT[ticket_id])
        for i in range(thread_count):
            while not IMAGE_THREAD_DICT[ticket_id][i].done():
                await asyncio.sleep(0.1)
    except:
        print("Unable to analyze ticket")

def process_analyze(ticket_id, src_picture, dst_picture, context:Context):
        analyze_thread = AnalyzeImage(src_picture, dst_picture, ticket_id)
        IMAGE_THREAD_DICT[ticket_id].append(asyncio.run_coroutine_threadsafe(analyze_thread.run(), context.analyze_loop))

class AnalyzeThread(Thread):
    def __init__(self, context:Context):    
        Thread.__init__(self)
        self.context = context
        self.runing = True
        self.daemon = True

    def run(self):
        asyncio.set_event_loop(self.context.analyze_loop)
        asyncio.get_event_loop().run_forever() 

class WebSocketServer(Thread):
    def __init__(self, context:Context):    
        Thread.__init__(self)
        self.context = context
        self.daemon = True

    async def on_disconnect(self, sid):
        print('Client disconnected ' + sid)

    def run(self):
        asyncio.set_event_loop(self.context.server_loop)

        ctrl = Controller(self.context)
        self.context.ws_server.on('disconnect', self.on_disconnect)

        self.context.ws_server.on("launch-analyze", ctrl.launch_analyze)

        print("Starting websocket server ....")
        app = socketio.ASGIApp(self.context.ws_server)
        uvicorn.run(app, host=127.0.0.1, port=5678)

class AnalyzeImage:
    _LOCK = None

    def __init__(self, src_picture, dst_picture, ticket_id):
        self.src_picture = src_picture
        self.dst_picture = dst_picture
        self.ticket_id = ticket_id
        self.endded = False
        self.cancelled = False
        self.height, self.width, channel = self.src_picture.shape

    async def run(self):
        try:
            if AnalyzeImage._LOCK is None:
                AnalyzeImage._LOCK = asyncio.Lock()

            print("Analyze[" + str(self.ticket_id) + "] Access lock")
            async with AnalyzeImage._LOCK:
                if not self.cancelled:
                    print("Analyze[" + str(self.ticket_id) + "]: Lock passed")
                    start = time.time()
         
                    # Here onnxruntime-gpu analyze
                    await self.start_analyze()
        except:
            print("Unexpected error when try to analyze image")
        finally:
            self.endded = True


async def main():
    context = Context()

    websocket_server = WebSocketServer(context)
    analyze_thread = AnalyzeThread(context)

    websocket_server.start()
    analyze_thread.start()

    try:
        while True:
            await asyncio.sleep(1)
    except:
        print("Unknow error")        

if __name__ == "__main__":
    asyncio.run(main())
```

And the client look like that:

main.js
```
let socket = io("ws://127.0.0.1:5678");
socket.emit("launch-analyze");
```

This is all libraries installed in my environment:
aiohttp            3.8.1
aiomysql           0.0.22
aiosignal          1.2.0
asgiref            3.5.0
async-timeout      4.0.2
asyncssh           2.9.0
attrs              21.4.0
bidict             0.21.2
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.10
click              8.0.3
colorama           0.4.4
cryptography       36.0.1
flatbuffers        2.0
frozenlist         1.3.0
h11                0.13.0
httptools          0.3.0
idna               3.3
imageio            2.14.1
imantics           0.1.12
imutils            0.5.4
lxml               4.7.1
multidict          6.0.2
networkx           2.6.3
numpy              1.22.1
onnxruntime-gpu    1.8.1
opencv-python      4.5.5.62
packaging          21.3
passlib            1.7.4
Pillow             9.0.0
pip                21.2.4
protobuf           3.19.4
pycparser          2.21
PyMySQL            0.9.3
pyparsing          3.0.7
pytesseract        0.3.8
python-dotenv      0.19.2
python-engineio    4.1.0
python-socketio    5.3.0
PyWavelets         1.2.0
PyYAML             6.0
qrcode             7.3.1
scikit-image       0.19.1
scipy              1.7.3
setuptools         58.0.4
simplejson         3.17.6
six                1.16.0
tifffile           2021.11.2
typing_extensions  4.0.1
uvicorn            0.17.1
watchgod           0.7
websockets         10.1
wheel              0.37.1
wincertstore       0.2
xmljson            0.2.1
yarl               1.7.2

Python 3.9.7

**Comment by miguelgrinberg** [comment]
I can't really follow your code in detail, but you have two asyncio loops running on separate threads that are communicating, so something can be wrong on how you implemented this communication. If you can simplify the code and provide a complete, runnable example that I can debug maybe I can find out more.

**Comment by PhpEssential** [comment]
Thanks for fast reply, I will try to send you a runnable sample tomorrow. Seems to be more stable with python 3.7 and python-socketio 5.0.3.

The problem does not always occur, I will confirm this hypothesis later

**Comment by miguelgrinberg** [comment]
Please reopen if you have any new information to add.

**Comment by thhung** [comment]
Hi @PhpEssential, do you have solutions for this problem? I think I have some similar issues.

**Comment by PhpEssential** [comment]
Hi @thhung, I rearrange the code to do all blocking operations in different thread and downgrade python and python-sockets version as mention
