### ISSUE TITLE
"KeyError: 0" while calling emit to a room from a celery + gevent task

### ISSUE THREAD

**Issue by MaxwellDPS** [miguelgrinberg/python-socketio#868]
**Describe the bug**
Howdy, I am seeing the following error `KeyError: 0` while calling emit to a room from a celery + gevent task. Thanks in advance!

**To Reproduce**
1. Setup with Celery with gevent and Kombu
2. Send event to room from celery task with gevent
3. receive error on emit

Python 3.9
Django / Celery app

**Expected behavior**

**Logs**
```
trunk-player-worker_1  | [2022-02-06 17:55:07,941: INFO/MainProcess] Task radio.tasks.broadcast_transmission[fc227c55-2ddc-4fae-86a7-8bc83c9faba9] succeeded in 0.028156599029898643s: None
trunk-player_1         | Traceback (most recent call last):
trunk-player_1         |   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
trunk-player_1         |   File "/usr/local/lib/python3.9/site-packages/socketio/pubsub_manager.py", line 168, in _thread
trunk-player_1         |     self._handle_emit(data)
trunk-player_1         |   File "/usr/local/lib/python3.9/site-packages/socketio/pubsub_manager.py", line 116, in _handle_emit
trunk-player_1         |     super(PubSubManager, self).emit(message['event'], message['data'],
trunk-player_1         |   File "/usr/local/lib/python3.9/site-packages/socketio/base_manager.py", line 165, in emit
trunk-player_1         |     for sid, eio_sid in self.get_participants(namespace, room):
trunk-player_1         |   File "/usr/local/lib/python3.9/site-packages/socketio/base_manager.py", line 43, in get_participants
trunk-player_1         |     participants = ns[room[0]]._fwdm.copy() if room[0] in ns else {}
trunk-player_1         | KeyError: 0
trunk-player_1         | 2022-02-06T23:55:07Z <Thread at 0x7ff4b49339d0: <bound method PubSubManager._thread of <socketio.kombu_manager.KombuManager object at 0x7ff4b5fbcb20>>> failed with KeyError
```

**Additional context**
The sio.emit is running in a celery task
This also seems to stall the rabbitMQ Queue
This also appears to break the UWSGI socket io as it stops responding but stays connected

code:
```python
@shared_task
def broadcast_transmission(event: str, room: str, data: dict):
    try:
        mgr = socketio.KombuManager(
            os.getenv("CELERY_BROKER_URL", "ampq://user:pass@127.0.0.1/")
        )
        sio = socketio.Server(
            async_mode="gevent", client_manager=mgr, logger=False, engineio_logger=False
        )
        sio.emit(event, data, room=room)
    except Exception as e:
        if settings.SEND_TELEMETRY:
            capture_exception(e)
        raise(e)
```

**Comment by MaxwellDPS** [comment]
Apologies this was my bad. I had the data and room params out of order
