### ISSUE TITLE
uWSGI gevent_uwsgi, ValueError: invalid literal for int() with base 10: b'\x00'

### ISSUE THREAD

**Issue by MartinX80** [miguelgrinberg/python-socketio#879]
@miguelgrinberg, I'm sorry but it seems that your measure discussed in here [https://github.com/miguelgrinberg/python-socketio/issues/39] did not entirely fix the problem. Problem still exists under uWSGI with gevent_uwsgi.

Everything works like a charm on standalone Flask with gevent, but behaind uWSGI, binary decoding fails.

```
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'\x00'
02/21 14:56:57 ERROR   engineio.server              message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'\x00'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'\x00'
02/21 14:56:57 ERROR   engineio.server              message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'\x00'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'%'
02/21 14:56:57 ERROR   engineio.server              message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 40, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 74, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'%'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 589, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 398, in handle_request
    r = self._handle_connect(environ, start_response,
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 573, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/async_drivers/gevent_uwsgi.py", line 61, in __call__
    self.app(self)
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 242, in _websocket_handler
    pkt = packet.Packet(encoded_packet=p)
  File "/usr/local/lib/python3.8/dist-packages/engineio/packet.py", line 27, in __init__
    self.decode(encoded_packet)
  File "/usr/local/lib/python3.8/dist-packages/engineio/packet.py", line 63, in decode
    self.packet_type = int(encoded_packet[0])
ValueError: invalid literal for int() with base 10: 'd'
```

pocket.py decode() got -> 
```
    print(ep, type(encoded_packet), self.packet_type, isinstance(encoded_packet, bytes))
    ----
    ep == bytes('...') # Normal object, nothing strange here
    type(ep) == <class 'bytes'>
    self.packet_type == 2
    isinstance(encoded_packet, bytes) == True
```

Client:

```
	async upload(index) {
		let start = this.size * index;
		let blob = this.file.slice(start, this.size * (index + 1));

		this.socket.emit('slice', {'hash': this.hash,
			'file': this.file.name, 
			'index': index,
			'start': start,
			'size': blob.size,
			'blob': blob,
			'length': this.file.size});
	}
```
Server:

```
FROM ubuntu:latest
COPY requirements.txt /
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install --no-install-recommends --yes \
                        liblzma-dev wget xz-utils gcc \
                        python3-dev python3-pip python3-setuptools \
                        libmemcached-dev zlib1g-dev libssl-dev \
                        netbase wget xz-utils gcc libpcre3 \
                        libpcre3-dev nginx memcached curl nano \
                        jq lz4 && \
  python3 -m pip install --upgrade pip setuptools wheel && \
  CFLAGS="-g0" pip install --no-cache-dir -r /requirements.txt && \
  rm /requirements.txt && \
  pip install gevent gevent-websocket uwsgi uwsgitop --upgrade && \
  rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
```

Driver:
Flask-SocketIO==5.1.1
python-engineio==4.3.0
python-socketio==5.4.1

**Comment by MartinX80** [comment]
Even if data are base64 encoded -> 

ValueError: invalid literal for int() with base 10: b'\x00'
02/21 19:34:29 ERROR   engineio.server              message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 765, in _handle_eio_message
    pkt = self.packet_class(encoded_packet=data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 42, in __init__
    self.attachment_count = self.decode(encoded_packet) or 0
  File "/usr/local/lib/python3.8/dist-packages/socketio/packet.py", line 78, in decode
    self.packet_type = int(ep[0:1])
ValueError: invalid literal for int() with base 10: b'\x00'

{"hash":"774330925113260429","file":"Attachment_0.pdf","index":4,"start":1000000,"size":128402,"blob":"vGfeI78xvyG/MyeB0vP9Hu/3S+YlcsFcIHtmjyzMghyYA7IyKzI9PTw9PT08PT09PP2GeZOykCvgCrkCrpAr4Aq5Aq6QK+AKuQKukCvgCrkCrpAr4Aq5MnO3zFtk9iboTdiboDdhb4LehL0JegvsLaC3QOcA50DnAOdA5wDnQOcA50DnAOdA5wDnQOcA50DPAE9lP4p+lCwFS8lSsJQsBUvJUrCULAVLyVKwlCwFS9mPoh8lV2cu+1H0o+xH0Y+yH0U/yn4U/Sj7UfRj7MfQj9HZ4Gx0NjgbnQ3ORmeDs9HZ4Gx0NjgbnQ3OR ..."}

**Comment by miguelgrinberg** [comment]
The issue #39 you are referring to is from 6 years ago. I have to think that this was broken someone would have reported it long ago.

May I ask what client are you using?

**Comment by MartinX80** [comment]
Hey @miguelgrinberg, it's a pleasure to meet you :) Do you mean browser? Brave Browser, this maybe a reason, but Chrome and Firefox results this:


print('is binary?', binary, self._data_is_binary(self.data), data, self.packet_type, encoded_packet)
```
<class 'str'> 2 False
is binary? None False ['pong', 'OK'] 2 None
is binary? None False None 2 51-["slice",{"hash":"1813563177959953727","file":"CORPSE - MISS YOU!.mp3","index":11,"start":825000,"size":75000,"blob":{"_placeholder":true,"num":0},"length":3839896}]
<class 'str'> 2 False
02/21 20:26:44 DEBUG   app.routes.main              Disconnecting, hash 73b09ad6c52f96ba.
02/21 20:26:44 TRACE   app.routes.main              Closing [192.168.68.106].
02/21 20:26:44 NOTIFY  app.routes.main              Save job ee17d018-7506-4f8c-ae40-2e646ceb0898, enqueded.
02/21 20:26:44 NOTIFY  app.routes.main              Close job a088c001-768e-4186-aeaf-7c728841d57f, enqueded.
02/21 20:26:44 NOTIFY  app.routes.main              removing request 73b09ad6c52f96ba from local.io,
02/21 20:26:44 SPEED                                Total disconnect: [8.61ms]
```

**Comment by miguelgrinberg** [comment]
I meant what Socket.IO client are you using.

**Comment by MartinX80** [comment]
I started to suspect clients to send different packets :XD 

socket.io-3.0.4

**Comment by MartinX80** [comment]
Upgrade to 4.4.1, unfortunately didn't resolve the problem.

**Comment by miguelgrinberg** [comment]
It appears this is a bug in uwsgi's WebSocket implementation, which does not use the correct method to determine if a websocket packet is binary or text and for some types of packets it reports them as text when they are in fact binary. This issue is indirectly referenced here: https://github.com/unbit/uwsgi/issues/1167.

**Comment by MartinX80** [comment]
Looks like, this bug is more than only a binary problem. I still have this ValueError, but when data are properly base64.encoded they can be correctly sent and received, despite the ValueError. On route osx -> ubuntu -> docker -> nginx -> uwsgi -> SocketIO -> RQ -> Cassandra (after solving some problems with decoding JS B64) files are stored without problems. For sure this is the problem of uWSGI, what do you think about this little trick in pocket.py?

```
    def decode(self, encoded_packet):
        """Decode a transmitted package.

        The return value indicates how many binary attachment packets are
        necessary to fully decode the packet.
        """
        ep = encoded_packet
        try:
            self.packet_type = int(ep[0:1])
        except ValueError:
            if env.get('SOCKETIO_ENGINE', False):
                logging.error('uWSGI transport detected, see https://github.com/miguelgrinberg/python-socketio/issues/879')
            self.data = (None,)
            return None
        except TypeError:
            self.packet_type = ep
            ep = ''
```

**Comment by miguelgrinberg** [comment]
Your fix is silently discarding packages that fail to parse. I don't see how this can be a good solution, sorry.

**Comment by MartinX80** [comment]
After testing different configurations, this problem occurs only in uWSGI, but of course, it's a switch for silent discarding. All the best, truly thank you for your time.
