### ISSUE TITLE
[Client] Reconnection attemps won't stop even if a connection has successfully established.

### ISSUE THREAD

**Issue by hugocornago** [miguelgrinberg/python-socketio#914]
### Summary
When a connection can't be made, it tries to reconnect multiple times at the same time. When a connection is finally established, the other recconectionn threads don't stop.

### My Code
**wss.py**
```python
import socketio
import threading

class WSSocket(threading.Thread):
    def __init__(self, wss, debug=False):
        super(WSSocket,self).__init__()
        self.sio = socketio.Client() if not debug else socketio.Client(engineio_logger=True, logger=True, reconnection_delay=3)
        self._wss = wss
        self._debug = debug

    def __callbacks(self):
        @self.sio.event
        def connect():
            self.conn_event.set()
            print("### connect ###")

        @self.sio.event
        def disconnect():
            print("### disconnect ###")

        @self.sio.event
        def message(data):
            print(f"[MSG] {data}")

    def loop(self):
        self.sio.wait()

    def setup(self):
        self.__callbacks()
        self.sio.connect(self._wss)

    def run(self):
        self.conn_event = threading.Event()
        self.setup()
        self.loop()
```

**main.py**
```python
rom wss import WSSocket
import threading

if __name__ == "__main__":
    sck = WSSocket("wss://falcon.jklm.fun/socket.io", debug=True)
    sck.start()
    if not sck.conn_event.wait(timeout=20):
        raise Exception("SERVER", "Can't connect")
    room = str(input("Bird Bot room code: "))
    sck.login(room)
    people = sck.getPeople()
    if people[0]['nickname'] == "BirdBot":
        # TODO
        pass
    else:
        raise Exception("BirdBot is not present in room " + room)
```
### Output
```code
$ python main.py
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'vQaHiton2LzcySvCACa_', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
WebSocket connection was closed, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 2.65 seconds
Exiting read loop task
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/home/wss.py", line 40, in run
    self.setup()
  File "/data/data/com.termux/files/home/wss.py", line 36, in setup
    self.sio.connect(self._wss)
  File "/data/data/com.termux/files/home/env/lib/python3.10/site-packages/socketio/client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'E7Wv0W99sMf8VtaqACbp', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
WebSocket connection was closed, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 3.45 seconds 
Exiting read loop task
Connection failed, new attempt in 4.91 seconds
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': '6Z2FO1Vc_-sfzHXkACb7', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
WebSocket connection was closed, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 3.48 seconds
Exiting read loop task
Connection failed, new attempt in 4.97 seconds
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'Bk3YO2X-VuhBf-nOACcR', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
WebSocket connection was closed, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 3.44 seconds
Exiting read loop task
Connection failed, new attempt in 5.11 seconds
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'D35HRBnfAn-I6EebACcq', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
WebSocket connection was closed, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 3.05 seconds
Exiting read loop task
Connection failed, new attempt in 5.46 seconds
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Attempting polling connection to https://[REDACTED]/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'RYiGKpFL2hG_3ltlACc3', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
Polling connection accepted with {'sid': 'Cly4nTqpc-Ldt-f4ACc8', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to wss://[REDACTED]/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet MESSAGE data 0{"sid":"ZlH_lUWcSY3mLy3hACc9"}
Namespace / is connected
### connect ###
Bird Bot room code: Received packet MESSAGE data 0{"sid":"-sLjQelqoHWkyXyxACc-"}
Reconnection successful
WebSocket upgrade was successful
Connection failed, new attempt in 4.63 seconds
Reconnection successful
Connection failed, new attempt in 5.22 seconds
^C
Sending packet CLOSE data None
Engine.IO connection dropped
### disconnect ###
Exiting write loop task
Exiting write loop task
Connection failed, new attempt in 5.13 seconds
Unexpected error decoding packet: "string index out of range", aborting
Waiting for write loop task to end
Exiting read loop task
```

**Comment by miguelgrinberg** [comment]
What do you mean by "other threads"? There is only one reconnection thread. Help me understand what you are seeing, because the log seems to indicate that your connection is constantly dropping and reconnecting.
