### ISSUE TITLE
AttributeError: module 'redis.asyncio' has no attribute 'exceptions'

### ISSUE THREAD

**Issue by ba1dr** [miguelgrinberg/python-socketio#919]
```python
Traceback (most recent call last):
  File "/myproject/venv/lib/python3.10/site-packages/socketio/asyncio_pubsub_manager.py", line 151, in _thread
    async for message in self._listen():  # pragma: no branch
  File "/myproject/venv/lib/python3.10/site-packages/socketio/asyncio_redis_manager.py", line 100, in _listen
    async for message in self._redis_listen_with_retries():
  File "/myproject/venv/lib/python3.10/site-packages/socketio/asyncio_redis_manager.py", line 87, in _redis_listen_with_retries
    except aioredis.exceptions.RedisError:
AttributeError: module 'redis.asyncio' has no attribute 'exceptions'
```

Most likely the file `asyncio_redis_manager.py` should be fixed as:
```python
try:
    from redis import asyncio as aioredis
    from redis.exceptions import RedisError
except ImportError:
    try:
        import aioredis
        from aioredis.exceptions import RedisError
    except ImportError:
        aioredis = None

...
try
    ...
except RedisError:
    ....
```

**Comment by miguelgrinberg** [comment]
@ba1dr Can I ask you to confirm that the main branch fixes the issue? Thanks!

**Comment by ba1dr** [comment]
@miguelgrinberg Works for me for my use case now, thank you. Great app by the way!

**Comment by SebastianLuebke** [comment]
@miguelgrinberg when will this fix be on pypi?
