### ISSUE TITLE
error with websocekt transport and  sanic

### ISSUE THREAD

**Issue by notedit** [miguelgrinberg/python-socketio#92]
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 785, in uvloop.loop.__uv_stream_on_read_impl (uvloop/loop.c:76261)
  File "uvloop/handles/stream.pyx", line 559, in uvloop.loop.UVStream._on_read (uvloop/loop.c:73531)
  File "/Users/xiang/.local/share/virtualenvs/hongpa-backend-q7vBF3kd/lib/python3.5/site-packages/sanic/server.py", line 132, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 174, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2781)
httptools.parser.errors.HttpParserUpgrade: 239

**Comment by miguelgrinberg** [comment]
What version of sanic are you using? You need the 0.5 pre-releases out of master to use WebSocket, the 0.4 releases do not have this functionality.

**Comment by notedit** [comment]
i  am using  0.4.1,  i will try 0.5 pre-releases

**Comment by notedit** [comment]
i see the latest release is 0.4.1,  where i can find the 0.5 pre-releases?

**Comment by miguelgrinberg** [comment]
You have to install direct from the master branch on git.

**Comment by notedit** [comment]
i install the master branch, but it does not work.  

i change to aiohttp, it works well.  will try sanic when 0.5 release.
