### ISSUE TITLE
Socket connection cannot be made.

### ISSUE THREAD

**Issue by MK272008** [miguelgrinberg/python-socketio#939]
**Describe the bug**
Whenever I try to start my django server which uses python socketio, I get the following error: 
```
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

ValueError: too many file descriptors in select()
```

**To Reproduce**
1. Run the exact django example in the documentation on your computer after installing all the dependencies.

**Expected behavior**
I expected the server to run successfully along with the socket connection to be made successfully.

**Logs**
```
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43Br.0&b64=1 HTTP/1.1" 200 0 0.071805
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43Bj&b64=1 HTTP/1.1" 200 0 0.078790
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43BW&b64=1 HTTP/1.1" 200 0 0.096741
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43BY&b64=1 HTTP/1.1" 200 0 0.100729
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43Bz&b64=1 HTTP/1.1" 200 0 0.087763
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43Bs&b64=1 HTTP/1.1" 200 0 0.093747
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 605, in handle_one_response
    write(b''.join(towrite))
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 533, in write
    wfile.flush()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

127.0.0.1 - - [22/Jun/2022 16:28:23] "GET /socket.io/?EIO=4&transport=polling&t=O6B43BZ&b64=1 HTTP/1.1" 200 0 0.113695
Traceback (most recent call last):
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "server\venv\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "server\venv\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "Programs\Python\Python39\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "server\venv\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "server\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "server\venv\lib\site-packages\django\core\management\commands\runserver.py", line 157, in inner_run
    handler = self.get_handler(*args, **options)
  File "server\venv\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 31, in get_handler
    handler = super().get_handler(*args, **options)
  File "server\venv\lib\site-packages\django\core\management\commands\runserver.py", line 78, in get_handler
    return get_internal_wsgi_application()
  File "server\venv\lib\site-packages\django\core\servers\basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "server\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string  
    return cached_import(module_path, class_name)
  File "server\venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import  
    import_module(module_path)
  File "Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "server\server\wsgi.py", line 33, in <module>
    eventlet.wsgi.server(eventlet.listen(('', 8000)), application)
  File "server\venv\lib\site-packages\eventlet\wsgi.py", line 1020, in server
    pool.waitall()
  File "server\venv\lib\site-packages\eventlet\greenpool.py", line 126, in waitall
    self.no_coros_running.wait()
  File "server\venv\lib\site-packages\eventlet\event.py", line 125, in wait
    result = hub.switch()
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 313, in switch
    return self.greenlet.switch()
  File "server\venv\lib\site-packages\eventlet\hubs\hub.py", line 367, in run
    self.wait(0)
  File "server\venv\lib\site-packages\eventlet\hubs\selects.py", line 42, in wait
    r, w, er = select.select(reader_fds, writer_fds, all_fds, seconds)
ValueError: too many file descriptors in select()
```

**System Config**
OS: Windows 11
Python Version: Python 3.9

**Comment by miguelgrinberg** [comment]
This does not look like it has anything to do with this package. The `select()` function on Windows can manage only 64 file descriptors maximum ([documentation](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select?redirectedfrom=MSDN)). I suspect eventlet does not account for this limitation when running on Windows.

I suggest you either use the WSL, which should work just fine, or else drop eventlet and work with a standard multi-threaded web server.
