### ISSUE TITLE
v5.7 does not work with JavaScript socket.io-client v4.1.2

### ISSUE THREAD

**Issue by KarolBorkowski** [miguelgrinberg/python-socketio#955]
**Describe the bug**
socket.io-client v4.1.2 client does not connect to v5.7 server. Version 5.6 works without issues.

**To Reproduce**
Set up a server and connect a client in given versions.

**Expected behavior**
Connections is established

**Logs**
Client side: 
socket.on("connect_error", err => console.log(err)); gives:
Error
    at Socket.onpacket (socket.js:229:1)
    at __webpack_modules__../node_modules/component-emitter/index.js.Emitter.emit (index.js:145:1)
    at Manager.emitReserved (typed-events.js:59:1)
    at Manager.ondecoded (manager.js:207:1)
    at __webpack_modules__../node_modules/component-emitter/index.js.Emitter.emit (index.js:145:1)
    at Decoder.add (index.js:117:1)
    at Manager.ondata (manager.js:199:1)
    at __webpack_modules__../node_modules/component-emitter/index.js.Emitter.emit (index.js:145:1)
    at Socket.onPacket (socket.js:400:1)
    at __webpack_modules__../node_modules/component-emitter/index.js.Emitter.emit (index.js:145:1)

Sever side:
Sending packet MESSAGE data 4"Unable to connect"

**Comment by KarolBorkowski** [comment]
app = Flask(__name__)
app.app_context().push()
socketio = SocketIO(app, cors_allowed_origins=['123.123.123.123'])
socketio.run(app,
                     host='0.0.0.0',
                     port=5000)

**Comment by KarolBorkowski** [comment]
Perhaps that was the problem. I use the WebSocket connection only for server -> client communication. Do I need to add some dummy handlers in such a case?

**Comment by miguelgrinberg** [comment]
@KarolBorkowski did you try what I suggested? Just add a connect handler, you do not need to do anything, just have the handler there. Something like this:

```python
@sio.event
def connect(sid, environ, auth):
    pass
```

**Comment by miguelgrinberg** [comment]
The 5.7.1 release allows connections to the default namespace, even if there is no handlers for it.
