### ISSUE TITLE
How to add connection to the database(PostgreSQL)

### ISSUE THREAD

**Issue by MaxOvcharov** [miguelgrinberg/python-socketio#98]
I try add connection to the DB in my app. 
```
# -*- coding: utf-8 -*-
import asyncio
import base64
import gzip
import hashlib
import pathlib

import aiofiles
import socketio
from aiohttp import web

from models import setup_pg
from settings import logger, options
from utils import load_config

PROJ_ROOT = pathlib.Path(__file__).parent.parent
TEMPLATES_ROOT = pathlib.Path(__file__).parent / 'templates'

global sio

async def index(request):
    """
    Simple client in web browser
    :param request: request from page
    :return: response app.html file
    """
    with open(str(PROJ_ROOT / 'templates' / 'app.html')) as f:
        return web.Response(text=f.read(), content_type='text/html')


@sio.on('my event', namespace='/test')
async def test_message(sid, message):
    """
    Custom event handler with event_name and
    Socket.IO namespace for the event. This handler works like echo-server.
    :param sid: Session ID of the client
    :param message: message payload
    :return: None
    """
    # Added transport mode checker
    transport_mode = sio.transport(sid)
    logger.debug('MESSAGE TRANSPORT MODE (%s): %s' % (sid, transport_mode))
    try:
        if isinstance(message, dict):
            await sio.emit('my response',
                           {'data': message.get('data', 'Message should be dict: {"data": "some text"}')},
                           room=sid, namespace='/test')
            logger.debug('event: "my event"(ECHO), SID: %s Message: %s' % (sid, message))
        else:
            raise TypeError('Message should be dict: {"data": "some text"}')
    except ValueError as e:
        logger.error('Handle ERROR: %s' % e)
    except TypeError as e1:
        logger.error('Handle ERROR: %s' % e1)


def call_back_from_client(*args, **kwargs):
    """
    Handle callback from client with any parameters
    :param args: positional arguments
    :param kwargs: named arguments
    :return: none
    """

    for arg in args:
        logger.debug('My EVENT(FILE CALLBACK - args) %s' % arg)

    for key, value in kwargs:
        logger.debug('My EVENT(FILE CALLBACK - kwargs) %s:%s' % (key, value))


@sio.on('file', namespace='/test')
async def test_binary_message(sid):
    """
    Custom event handler with event_name and
    Socket.IO namespace for the event. This handler send
    image file in base64 gzip.
    :param sid: Session ID of the client
    :return: emit file base64 gzip
    """
    content_b64 = ''
    hash_sum = ''
    try:
        async with aiofiles.open('static/test.png', mode='rb') as image_file:
            content = await image_file.read()
            gzip_file = gzip.compress(content)
            content_b64 = base64.b64encode(gzip_file)
            hash_sum = hashlib.md5(content_b64).hexdigest()
    except OSError as e:
        logger.error('Handle ERROR: %s' % e)
    await sio.emit('file response',
                   {'data': content_b64.decode('utf-8'), 'hash_sum': hash_sum},
                   room=sid,
                   namespace='/test',
                   callback=call_back_from_client)
    logger.debug('My EVENT(FILE) (%s): %s' % (sid, content_b64[:20]))
    del content_b64


@sio.on('message received', namespace='/test')
async def test_message(sid, message):
    logger.debug('My EVENT(CALL BACK) (%s): %s' % (sid, message))
    return True


@sio.on('my broadcast event', namespace='/test')
async def broadcast_message(sid, message):
    await sio.emit('my response', {'data': message['data']}, namespace='/test')
    logger.debug('BROADCAST MESSAGE(%s): %s' % (sid, message))


@sio.on('join', namespace='/test')
async def join(sid, message):
    sio.enter_room(sid, message['room'], namespace='/test')
    await sio.emit('my response', {'data': 'Entered room: ' + message['room']},
                   room=sid, namespace='/test')
    logger.debug('JOIN ROOM (%s): %s' % (sid, message))


@sio.on('leave', namespace='/test')
async def leave(sid, message):
    sio.leave_room(sid, message['room'], namespace='/test')
    await sio.emit('my response', {'data': 'Left room: ' + message['room']},
                   room=sid, namespace='/test')
    logger.debug('LEAVE ROOM (%s): %s' % (sid, message))


@sio.on('close room', namespace='/test')
async def close(sid, message):
    await sio.emit('my response', {'data': 'Room %s is closing' % message['room']},
                   room=message['room'], namespace='/test')
    await sio.close_room(message['room'], namespace='/test')
    logger.debug('CLOSE ROOM (%s): %s' % (sid, message))


@sio.on('my room event', namespace='/test')
async def send_room_message(sid, message):
    # Added transport mode checker
    # transport_mode = sio.transport(sid)
    # logger.debug('TRANSPORT MODE(%s): %s' % (sid, transport_mode))

    await sio.emit('my response', {'data': message['data']},
                   room=message['room'], namespace='/test')
    logger.debug('ROOM EVENT (%s): %s' % (sid, message))


@sio.on('disconnect request', namespace='/test')
async def disconnect_request(sid):
    await sio.disconnect(sid, namespace='/test')
    logger.debug('DISCONNECT REQUEST: %s' % sid)


@sio.on('connect', namespace='/test')
async def test_connect(sid, environ):
    # Added transport mode checker
    transport_mode = sio.transport(sid)
    logger.debug('CONNECT TRANSPORT MODE (%s): %s' % (sid, transport_mode))

    await sio.emit('my response', {'data': 'Connected', 'count': 0},
                   room=sid, namespace='/test')
    logger.debug('CONNECT USER: %s, ENVIRON: %s' % (sid, environ))


@sio.on('disconnect', namespace='/test')
def test_disconnect(sid):
    logger.debug('DISCONNECT USER: %s' % sid)

async def init(loop):
    # load config from yaml file
    conf = load_config(str(PROJ_ROOT / 'config' / 'dev.yml'))

    # setup application and extensions
    sio = socketio.AsyncServer(async_mode='aiohttp',
                               allow_upgrades=True)
    app = web.Application(loop=loop)
    sio.attach(app)
    pg = await setup_pg(app, conf, loop)

    # setup views and routes
    app.router.add_static('/static', path=str(PROJ_ROOT / 'static'))
    app.router.add_get('/', index)
    return app


def main():

    # Run background task
    # sio.start_background_task(background_task)
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(init(loop))
    # Run app
    web.run_app(app, host=options.host, path=options.path, port=options.port)


if __name__ == '__main__':

    main()
```
I use global for sio, but I have this ERROR. 
`Traceback (most recent call last):
  File "simple_chat.py", line 31, in <module>
    @sio.on('my event', namespace='/test')
NameError: name 'sio' is not defined
`
Is this a correct way of DB connection?

**Comment by notedit** [comment]
you use sio  before it define

**Comment by MaxOvcharov** [comment]
Yes, I know it, but how can I setup application and extensions(pg connect) in init() without including all event handlers in it?

**Comment by MaxOvcharov** [comment]
But my question is how can add my DB connect into main loop. Does the engineio his own loop and I have to attach  DB connect into it, like my app?

**Comment by miguelgrinberg** [comment]
Can you import `sio` from the place it is defined? You don't want that to be a global variable, you just want that variable from the other module imported in this one.

**Comment by MaxOvcharov** [comment]
I solved this problem. But my question was how can I use db connection in my socket.io event handlers 
For example I have:
1) run_server.py
```
# -*- coding: utf-8 -*-
import asyncio
import os

from aiohttp import web

from chat import sio, index
from settings import set_logger, BASE_DIR, parse_args

from models import setup_pg
from utils import load_config

logger = set_logger()

async def init(loop):

    app = web.Application(loop=loop)
    sio.attach(app)

    # load config from yaml file
    conf = load_config(os.path.join(BASE_DIR, "config/dev.yml"))
    pg = await setup_pg(app, conf, loop)

    # setup views and routes
    app.router.add_static('/static', os.path.join(BASE_DIR, "chat/static/"))
    app.router.add_get('/', index)
    return app


def main():
    options = parse_args()
    # Run background task
    # sio.start_background_task(background_task)
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(init(loop))
    # Run app
    web.run_app(app, host=options.host, path=options.path, port=options.port)


if __name__ == '__main__':
    main()
```
2) chat.py
```
import aiofiles
import base64
import gzip
import hashlib
import os
import socketio

from aiohttp import web
from settings import set_logger, BASE_DIR

# setup application and extensions
sio = socketio.AsyncServer(async_mode='aiohttp',
                           allow_upgrades=True)

# setup logger for app
logger = set_logger()

async def index(request):
    """
    Simple client in web browser
    :param request: request from page
    :return: response app.html file
    """
    with open(os.path.join(BASE_DIR, "chat/templates/app.html")) as f:
        return web.Response(text=f.read(), content_type='text/html')


def call_back_from_client(self, *args, **kwargs):
    """
    Handle callback from client with any parameters
    :param args: positional arguments
    :param kwargs: named arguments
    :return: none
    """

    for arg in args:
        logger.debug('My EVENT(FILE CALLBACK - args) %s' % arg)

    for key, value in kwargs:
        logger.debug('My EVENT(FILE CALLBACK - kwargs) %s:%s' % (key, value))


@sio.on('my event', namespace='/test')
async def test_message(sid, message):
    """
    Custom event handler with event_name and
    Socket.IO namespace for the event. This handler works like echo-server.
    :param sid: Session ID of the client
    :param message: message payload
    :return: None
    """
    # Added transport mode checker
    transport_mode = sio.transport(sid)
    logger.debug('MESSAGE TRANSPORT MODE (%s): %s' % (sid, transport_mode))
    try:
        if isinstance(message, dict):
            await sio.emit('my response',
                           {'data': message.get('data', 'Message should be dict: {"data": "some text"}')},
                           room=sid, namespace='/test')
            logger.debug('EVENT: "my event"(ECHO), SID: %s Message: %s' % (sid, message))
        else:
            raise TypeError('Message should be dict: {"data": "some text"}')
    except ValueError as e:
        logger.error('Handle ERROR: %s' % e)
    except TypeError as e1:
        logger.error('Handle ERROR: %s' % e1)


@sio.on('file', namespace='/test')
async def test_binary_message(sid):
    """
    Custom event handler with event_name and
    Socket.IO namespace for the event. This handler send
    image file in base64 gzip.
    :param sid: Session ID of the client
    :return: emit file base64 gzip
    """
    content_b64 = ''
    hash_sum = ''
    try:
        async with aiofiles.open('static/test.png', mode='rb') as image_file:
            content = await image_file.read()
            gzip_file = gzip.compress(content)
            content_b64 = base64.b64encode(gzip_file)
            hash_sum = hashlib.md5(content_b64).hexdigest()
    except OSError as e:
        logger.error('Handle ERROR: %s' % e)
    await sio.emit('file response',
                   {'data': content_b64.decode('utf-8'), 'hash_sum': hash_sum},
                   room=sid,
                   namespace='/test',
                   callback=call_back_from_client)
    logger.debug('My EVENT(FILE) (%s): %s' % (sid, content_b64[:20]))
    del content_b64


@sio.on('message received', namespace='/test')
async def test_message(sid, message):
    logger.debug('My EVENT(CALL BACK) (%s): %s' % (sid, message))
    return True


@sio.on('my broadcast event', namespace='/test')
async def broadcast_message(sid, message):
    await sio.emit('my response', {'data': message['data']}, namespace='/test')
    logger.debug('BROADCAST MESSAGE(%s): %s' % (sid, message))


@sio.on('join', namespace='/test')
async def join(sid, message):
    sio.enter_room(sid, message['room'], namespace='/test')
    await sio.emit('my response', {'data': 'Entered room: ' + message['room']},
                   room=sid, namespace='/test')
    logger.debug('JOIN ROOM (%s): %s' % (sid, message))


@sio.on('leave', namespace='/test')
async def leave(sid, message):
    sio.leave_room(sid, message['room'], namespace='/test')
    await sio.emit('my response', {'data': 'Left room: ' + message['room']},
                   room=sid, namespace='/test')
    logger.debug('LEAVE ROOM (%s): %s' % (sid, message))


@sio.on('close room', namespace='/test')
async def close(sid, message):
    await sio.emit('my response', {'data': 'Room %s is closing' % message['room']},
                   room=message['room'], namespace='/test')
    await sio.close_room(message['room'], namespace='/test')
    logger.debug('CLOSE ROOM (%s): %s' % (sid, message))


@sio.on('my room event', namespace='/test')
async def send_room_message(sid, message):
    # Added transport mode checker
    # transport_mode = sio.transport(sid)
    # logger.debug('TRANSPORT MODE(%s): %s' % (sid, transport_mode))

    await sio.emit('my response', {'data': message['data']},
                   room=message['room'], namespace='/test')
    logger.debug('ROOM EVENT (%s): %s' % (sid, message))


@sio.on('disconnect request', namespace='/test')
async def disconnect_request(sid):
    await sio.disconnect(sid, namespace='/test')
    logger.debug('DISCONNECT REQUEST: %s' % sid)


@sio.on('connect', namespace='/test')
async def test_connect(sid, environ):
    # Added transport mode checker
    transport_mode = sio.transport(sid)
    logger.debug('CONNECT TRANSPORT MODE (%s): %s' % (sid, transport_mode))

    await sio.emit('my response', {'data': 'Connected', 'count': 0},
                   room=sid, namespace='/test')
    logger.debug('CONNECT USER: %s, ENVIRON: %s' % (sid, environ))


@sio.on('disconnect', namespace='/test')
def test_disconnect(sid):
    logger.debug('DISCONNECT USER: %s' % sid)
```
3) models.py
```
# -*- coding: utf-8 -*-
import aiopg.sa

async def setup_pg(app, conf, loop):
    # create connection to the database
    pg = await init_postgres(conf['postgres'], loop)

    async def close_pg(app):
        pg.close()
        await pg.wait_closed()

    app.on_cleanup.append(close_pg)
    return pg


async def init_postgres(conf, loop):
    engine = await aiopg.sa.create_engine(
        database=conf['database'],
        user=conf['user'],
        password=conf['password'],
        host=conf['host'],
        port=conf['port'],
        minsize=conf['minsize'],
        maxsize=conf['maxsize'],
        loop=loop)
    return engine
```

**Comment by MaxOvcharov** [comment]
How can I use **pg** from run_server.py in chat.py(socket.io event handlers)

**Comment by miguelgrinberg** [comment]
You have `pg` as a local variable. Shouldn't you make that global, so that you can import it from other modules?

**Comment by MaxOvcharov** [comment]
I should make it global in run_server.py or I have to define it in another model?

**Comment by miguelgrinberg** [comment]
Does not really matter, as long as you can import it in the module where you need it.

**Comment by MaxOvcharov** [comment]
I fixed my imports, but now my method(**run_chat**) from **chat.py** starts 3 times on every events. I use **run_chat** in the method(**init**) of **run_server.py**.
1) run_server.py
```
# -*- coding: utf-8 -*-
import asyncio
import os

from aiohttp import web

from chat import sio, run_chat
from models import setup_pg
from settings import set_logger, BASE_DIR, parse_args
from utils import load_config
from views import index

# setup logger for app
logger = set_logger()


async def init(loop):
    # global pg
    app = web.Application(loop=loop)

    # load config from yaml file
    conf = load_config(os.path.join(BASE_DIR, "config/dev.yml"))
    pg = await setup_pg(app, conf, loop)

    # Attach app to the Socket.io server
    sio.attach(app)
    async with pg.acquire() as conn:
        await  run_chat(conn)
    # setup views and routes
    app.router.add_static('/static', os.path.join(BASE_DIR, "chat/static/"))
    app.router.add_get('/', index)
    return app


def main():
    options = parse_args()
    # Run background task
    # sio.start_background_task(background_task)
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(init(loop))
    # Run app
    web.run_app(app, host=options.host, path=options.path, port=options.port)

if __name__ == '__main__':
    main()
```
 2. chat.py
```
import aiofiles
import base64
import gzip
import json
import hashlib
import socketio

# from run_server import pg
from settings import set_logger
from models import users, private_history

# setup logger for app
logger = set_logger()

# setup application and extensions
sio = socketio.AsyncServer(async_mode='aiohttp',
                           allow_upgrades=True)

async def run_chat(conn):

    def call_back_from_client(*args, **kwargs):
        """
        Handle callback from client with any parameters
        :param args: positional arguments
        :param kwargs: named arguments
        :return: none
        """

        for arg in args:
            logger.debug('My EVENT(FILE CALLBACK - args) %s' % arg)

        for key, value in kwargs:
            logger.debug('My EVENT(FILE CALLBACK - kwargs) %s:%s' % (key, value))

    @sio.on('my event', namespace='/test')
    async def test_message(sid, message):
        """
        Custom event handler with event_name and
        Socket.IO namespace for the event. This handler works like echo-server.
        :param sid: Session ID of the client
        :param message: message payload
        :return: None
        """
        # Added transport mode checker
        transport_mode = sio.transport(sid)
        logger.debug('MESSAGE TRANSPORT MODE (%s): %s' % (sid, transport_mode))
        try:
            if isinstance(message, dict):
                await sio.emit('my response',
                               {'data': message.get('data', 'Message should be dict: {"data": "some text"}')},
                               room=sid, namespace='/test')
                async with conn.begin():
                    uid = await conn.scalar(users.insert().values(login='max12', password='121212'))
                    await conn.execute(private_history.
                                       insert().
                                       values(message_id=1,
                                              message_json=json.dumps(
                                                  {'test': message.get('data', 'Wrong data was sent')}),
                                              user_id=uid,
                                              chat_id='test_chat'))
                logger.debug('EVENT: "my event"(ECHO), SID: %s Message: %s' % (sid, message))
            else:
                raise TypeError('Message should be dict: {"data": "some text"}')
        except ValueError as e:
            logger.error('Handle ERROR: %s' % e)
        except TypeError as e1:
            logger.error('Handle ERROR: %s' % e1)

    @sio.on('file', namespace='/test')
    async def test_binary_message(sid):
        """
        Custom event handler with event_name and
        Socket.IO namespace for the event. This handler send
        image file in base64 gzip.
        :param sid: Session ID of the client
        :return: emit file base64 gzip
        """
        content_b64 = ''
        hash_sum = ''
        try:
            async with aiofiles.open('static/test.png', mode='rb') as image_file:
                content = await image_file.read()
                gzip_file = gzip.compress(content)
                content_b64 = base64.b64encode(gzip_file)
                hash_sum = hashlib.md5(content_b64).hexdigest()
        except OSError as e:
            logger.error('Handle ERROR: %s' % e)
        await sio.emit('file response',
                       {'data': content_b64.decode('utf-8'), 'hash_sum': hash_sum},
                       room=sid,
                       namespace='/test',
                       callback=call_back_from_client)
        logger.debug('My EVENT(FILE) (%s): %s' % (sid, content_b64[:20]))
        del content_b64

    @sio.on('message received', namespace='/test')
    async def test_message(sid, message):
        logger.debug('My EVENT(CALL BACK) (%s): %s' % (sid, message))
        return True

    @sio.on('my broadcast event', namespace='/test')
    async def broadcast_message(sid, message):
        await sio.emit('my response', {'data': message['data']}, namespace='/test')
        logger.debug('BROADCAST MESSAGE(%s): %s' % (sid, message))

    @sio.on('join', namespace='/test')
    async def join(sid, message):
        sio.enter_room(sid, message['room'], namespace='/test')
        await sio.emit('my response', {'data': 'Entered room: ' + message['room']},
                       room=sid, namespace='/test')
        logger.debug('JOIN ROOM (%s): %s' % (sid, message))

    @sio.on('leave', namespace='/test')
    async def leave(sid, message):
        sio.leave_room(sid, message['room'], namespace='/test')
        await sio.emit('my response', {'data': 'Left room: ' + message['room']},
                       room=sid, namespace='/test')
        logger.debug('LEAVE ROOM (%s): %s' % (sid, message))

    @sio.on('close room', namespace='/test')
    async def close(sid, message):
        await sio.emit('my response', {'data': 'Room %s is closing' % message['room']},
                       room=message['room'], namespace='/test')
        await sio.close_room(message['room'], namespace='/test')
        logger.debug('CLOSE ROOM (%s): %s' % (sid, message))

    @sio.on('my room event', namespace='/test')
    async def send_room_message(sid, message):
        # Added transport mode checker
        # transport_mode = sio.transport(sid)
        # logger.debug('TRANSPORT MODE(%s): %s' % (sid, transport_mode))

        await sio.emit('my response', {'data': message['data']},
                       room=message['room'], namespace='/test')
        logger.debug('ROOM EVENT (%s): %s' % (sid, message))

    @sio.on('disconnect request', namespace='/test')
    async def disconnect_request(sid):
        await sio.disconnect(sid, namespace='/test')
        logger.debug('DISCONNECT REQUEST: %s' % sid)

    @sio.on('connect', namespace='/test')
    async def test_connect(sid, environ):
        # Added transport mode checker
        transport_mode = sio.transport(sid)
        logger.debug('CONNECT TRANSPORT MODE (%s): %s' % (sid, transport_mode))

        await sio.emit('my response', {'data': 'Connected', 'count': 0},
                       room=sid, namespace='/test')
        logger.debug('CONNECT USER: %s, ENVIRON: %s' % (sid, environ))

    @sio.on('disconnect', namespace='/test')
    def test_disconnect(sid):
        logger.debug('DISCONNECT USER: %s' % sid)
```
 I think it's happens because I use **run_chat** in **init**. Now I have no idea how to fixed it. Can you help me?

**Comment by MaxOvcharov** [comment]
My whole project is here: https://github.com/MaxOvcharov/aiohttp_chat

**Comment by miguelgrinberg** [comment]
`pg` is still a local variable. What I suggested is that you make it a global variable, so you can then import it in the place you need it. I did not suggest any other change, it seems you have made a fundamental change here, but that seems wrong, I don't understand what is the point of calling `run_chat` in `__init__.py`.

**Comment by MaxOvcharov** [comment]
First of all I tried to use global var, but it isn't work. Maybe I do something wrong.

> I don't understand what is the point of calling run_chat in __init__.py.  
I don't calling run_chat in __init__.py, I do it in  method(init) from **run_server.py**

**Comment by MaxOvcharov** [comment]
When I try to use global var I do something like this:
1) run_server.py
```
pg = ''
async def init(loop):
    ...
    pg = await setup_pg(app, conf, loop)
    from chat import sio
    sio.attach(app)
```
 2) chat.py
```
sio = socketio.AsyncServer(async_mode='aiohttp',
                           allow_upgrades=True)
from run_server import pg
@sio.on('my event', namespace='/test')
    async def test_message(sid, message):
        """
        Custom event handler with event_name and
        Socket.IO namespace for the event. This handler works like echo-server.
        :param sid: Session ID of the client
        :param message: message payload
        :return: None
        """
        # Added transport mode checker
        transport_mode = sio.transport(sid)
        logger.debug('MESSAGE TRANSPORT MODE (%s): %s' % (sid, transport_mode))
        try:
            if isinstance(message, dict):
                await sio.emit('my response',
                               {'data': message.get('data', 'Message should be dict: {"data": "some text"}')},
                               room=sid, namespace='/test')
                async with pg.acquire() as conn:
                    async with conn.begin():
                        uid = await conn.scalar(users.insert().values(login='max12', password='121212'))
                        await conn.execute(private_history.
                                           insert().
                                           values(message_id=1,
                                                  message_json=json.dumps(
                                                      {'test': message.get('data', 'Wrong data was sent')}),
                                                  user_id=uid,
                                                  chat_id='test_chat'))
                logger.debug('EVENT: "my event"(ECHO), SID: %s Message: %s' % (sid, message))
            else:
                raise TypeError('Message should be dict: {"data": "some text"}')
        except ValueError as e:
            logger.error('Handle ERROR: %s' % e)
        except TypeError as e1:
            logger.error('Handle ERROR: %s' % e1)
```
And after that I have error - pg doesn't have method acquire because it is a String.

**Comment by miguelgrinberg** [comment]
You need to declare your `pg` variable as global inside your function.

```python
pg = None

async def init(loop):
    global pg

    pg = ...
```

**Comment by MaxOvcharov** [comment]
This is a declaration of pg inside my function, isn't it?
`pg = await setup_pg(app, conf, loop) `

**Comment by MaxOvcharov** [comment]
I have idea, can I get my app in chat.py from sio after I do sio.attach(app) in run_server.py?
If I can do this, it is posible to add pg engine to the app in method- init from run_server.
Here is axample of this code.  
1) run_server.py
 ```
async def init(loop):
    ...
    # create connection to the database
    app.on_startup.append(init_pg)

    # shutdown db connection on exit
    app.on_cleanup.append(close_pg)
    sio.attach(app)
```
2) models.py
```
async def init_pg(app):
    conf = app['config']['postgres']
    engine = await aiopg.sa.create_engine(
        database=conf['database'],
        user=conf['user'],
        password=conf['password'],
        host=conf['host'],
        port=conf['port'],
        minsize=conf['minsize'],
        maxsize=conf['maxsize'],
        loop=app.loop)
    app['db'] = engine


async def close_pg(app):
    app['db'].close()
    await app['db'].wait_closed()
```
3) chat.py
```
...
# setup application and extensions
sio = socketio.AsyncServer(async_mode='aiohttp',
                                                allow_upgrades=True)
pg = sio. ...?????... .app['db']
...
```
What should be here  **...?????...** ?

**Comment by miguelgrinberg** [comment]
The `sio` object does not know what your `app` is. I'm sorry, but I'm having trouble understanding why you complicate things so much. I told you how to fix the "pg is a string" error. Have you done that?

**Comment by MaxOvcharov** [comment]
Ok, here is my code with **pg global** 
1) run_server
```
# -*- coding: utf-8 -*-
import asyncio
import os

from aiohttp import web

# from chat import sio, run_chat
from chat import sio
from models import setup_pg
from settings import set_logger, BASE_DIR, parse_args
from utils import load_config
from views import index

# setup logger for app
logger = set_logger()
pg = None

async def init(loop):
    global pg
    app = web.Application(loop=loop)

    # load config from yaml file
    conf = load_config(os.path.join(BASE_DIR, "config/dev.yml"))
    pg = await setup_pg(app, conf, loop)

    # Attach app to the Socket.io server
    sio.attach(app)
    # await run_chat(pg)
    # setup views and routes
    app.router.add_static('/static', os.path.join(BASE_DIR, "chat/static/"))
    app.router.add_get('/', index)
    return app


def main():
    options = parse_args()
    # Run background task
    # sio.start_background_task(background_task)
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(init(loop))
    # Run app
    web.run_app(app, host=options.host, path=options.path, port=options.port)

if __name__ == '__main__':
    main()
```
2) chat.py
```
import json
import socketio

from settings import set_logger
from models import users, private_history

# setup logger for app
logger = set_logger()

# setup application and extensions
sio = socketio.AsyncServer(async_mode='aiohttp',
                           allow_upgrades=True)
from run_server import pg

@sio.on('my event', namespace='/test')
async def test_message(sid, message):
    """
    Custom event handler with event_name and
    Socket.IO namespace for the event. This handler works like echo-server.
    :param sid: Session ID of the client
    :param message: message payload
    :return: None
    """
    # Added transport mode checker
    transport_mode = sio.transport(sid)
    logger.debug('MESSAGE TRANSPORT MODE (%s): %s' % (sid, transport_mode))
    try:
        if isinstance(message, dict):
            await sio.emit('my response',
                           {'data': message.get('data', 'Message should be dict: {"data": "some text"}')},
                           room=sid, namespace='/test')
            async with pg.acquire() as conn:
                async with conn.begin():
                    uid = await conn.scalar(users.insert().values(login='max12', password='121212'))
                    await conn.execute(private_history.
                                       insert().
                                       values(message_id=1,
                                              message_json=json.dumps(
                                                  {'test': message.get('data', 'Wrong data was sent')}),
                                              user_id=uid,
                                              chat_id='test_chat'))
            logger.debug('EVENT: "my event"(ECHO), SID: %s Message: %s' % (sid, message))
        else:
            raise TypeError('Message should be dict: {"data": "some text"}')
    except ValueError as e:
        logger.error('Handle ERROR: %s' % e)
    except TypeError as e1:
        logger.error('Handle ERROR: %s' % e1)
....
```
And finally I have this error:
```
 Error handling request
Traceback (most recent call last):
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/aiohttp/web.py", line 289, in _handle
    resp = yield from handler(request)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/engineio/asyncio_server.py", line 153, in handle_request
    await socket.handle_post_request(environ)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/engineio/asyncio_socket.py", line 89, in handle_post_request
    await self.receive(pkt)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/engineio/asyncio_socket.py", line 41, in receive
    await self.server._trigger_event('message', self.sid, pkt.data)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/engineio/asyncio_server.py", line 241, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/socketio/asyncio_server.py", line 353, in _handle_eio_message
    await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/socketio/asyncio_server.py", line 283, in _handle_event
    await self._handle_event_internal(self, sid, data, namespace, id)
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/socketio/asyncio_server.py", line 286, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/django/aiohttp_chat/venv/lib/python3.5/site-packages/socketio/asyncio_server.py", line 314, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/django/aiohttp_chat/chat/chat.py", line 51, in test_message
    async with pg.acquire() as conn:
AttributeError: 'NoneType' object has no attribute 'acquire'
```

**Comment by miguelgrinberg** [comment]
Can't really tell you what's wrong. Did you debug it? Is the `pg` global variable being set to the correct thing? Are you sure you don't have any circular imports?

**Comment by MaxOvcharov** [comment]
![default](https://cloud.githubusercontent.com/assets/13488059/25693193/9f5af942-30b0-11e7-9b8a-3fc8a6c0c5b1.png)

**Comment by MaxOvcharov** [comment]
I have circular imports when I use 

`from run_server import pg`

before declaration of  sio in chat.py

```
sio = socketio.AsyncServer(async_mode='aiohttp',
                           allow_upgrades=True)
```
Here is error traceback
```
Traceback (most recent call last):
  File "/home/max/bot_project/aiohttp_chat/chat/run_server.py", line 8, in <module>
    from chat import sio
  File "/home/max/bot_project/aiohttp_chat/chat/chat.py", line 8, in <module>
    from run_server import pg
  File "/home/max/bot_project/aiohttp_chat/chat/run_server.py", line 8, in <module>
    from chat import sio
ImportError: cannot import name 'sio'
```

**Comment by MaxOvcharov** [comment]
I fixed this bug! It is very easy solution:
1) run_server.py
`sio.pg = await setup_pg(app, conf, loop) `
2) chat.py
```
async with sio.pg.acquire() as conn:
    async with conn.begin():
```
